In [1]:
# Clone your GitHub repo (you’ll be prompted to authorize if it's private)
!git clone https://github.com/colterwood/LHL-final-final-project.git

Cloning into 'LHL-final-final-project'...
remote: Enumerating objects: 410, done.
remote: Counting objects: 100% (186/186), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 410 (delta 95), reused 50 (delta 12), pack-reused 224 (from 1)
Receiving objects: 100% (410/410), 6.11 MiB | 4.59 MiB/s, done.
Resolving deltas: 100% (210/210), done.

In [2]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup, Comment
import requests
from io import StringIO
import string
import time
import re
import os

In [3]:
# load the player game logs CSV from the data folder
df_gamelogs = pd.read_csv("LHL-final-final-project/data/2020-2023_basketball_reference_gamelog.csv")


# preview
df_gamelogs.head()

,team,year,home_away,opp,win_loss,team_score,opp_score,team_fg,team_fga,team_fg_pct,...,opponent_ft_pct,opponent_orb,opponent_trb,opponent_ast,opponent_stl,opponent_blk,opponent_tov,opponent_pf,day,month
0,ATL,2020,NaN,DAL,W,105.0,95.0,34,62,.548,...,.700,8,29,18,10,1,13,27,26.0,7.0
1,ATL,2020,@,LVA,L,70.0,100.0,28,70,.400,...,.692,14,47,16,11,1,19,14,29.0,7.0
2,ATL,2020,NaN,NYL,W,84.0,78.0,28,75,.373,...,.882,8,33,13,8,11,15,23,31.0,7.0
3,ATL,2020,@,IND,L,77.0,93.0,33,69,.478,...,.810,9,32,26,5,5,15,13,2.0,8.0
4,ATL,2020,NaN,PHO,L,74.0,81.0,29,62,.468,...,.864,10,33,19,7,2,10,18,4.0,8.0

In [4]:
# load the player game logs CSV from the data folder
df_2024_gamelogs = pd.read_csv("LHL-final-final-project/data/2024_merged_gamelogs.csv")


# preview
df_2024_gamelogs.head()

,team,g_num,month,day,home_away,opp,win_loss,team_score,opp_score,team_fg,...,day_of_week_by_team_travel_distance,team_vs_opp_median_score_by_team_travel_distance,team_vs_opp_homeaway_median_score_by_team_travel_distance,team_home_or_away_median_score_by_team_travel_distance,team_home_or_away_median_allowed_by_team_travel_distance,team_day_median_score_by_team_travel_distance,team_day_median_allowed_by_team_travel_distance,travel_distance_by_team_travel_distance,median_score_for_by_team_travel_distance,median_score_against_by_team_travel_distance
0,ATL,1,5,15,2,LAS,1,92,81,34,...,3.0,75.0,70.0,78.5,79.5,76.0,80.0,0.0,77.0,79.5
1,ATL,2,5,18,2,PHO,2,85,88,27,...,2.0,76.0,76.0,78.0,80.5,76.0,80.0,1.0,77.5,77.5
2,ATL,3,5,21,1,DAL,1,83,78,30,...,4.0,81.0,75.5,78.0,80.5,73.0,78.0,3.0,81.0,85.0
3,ATL,4,5,26,1,MIN,2,79,92,31,...,3.0,75.0,70.0,78.5,79.5,76.0,80.0,0.0,77.0,79.5
4,ATL,5,5,29,2,WAS,1,73,67,26,...,4.0,75.0,76.5,78.0,80.5,76.0,80.0,2.0,78.0,80.0

In [6]:
team = 'ATL'
year = 2023
url = f"https://www.basketball-reference.com/wnba/teams/{team}/{year}/gamelog-advanced/"
headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.content, "html.parser")
table = soup.find("table", id="wnba_tgl_advanced")
print(table is not None)  # Should print True if table exists

True

In [7]:
# Team codes remain the same across years
teams = ['ATL', 'CHI', 'CON', 'DAL', 'IND', 'LAS', 'MIN', 'NYL', 'PHO', 'SEA', 'WAS', 'LVA']

# Base URL with placeholder for team and year
base_url = "https://www.basketball-reference.com/wnba/teams/{team}/{year}/gamelog-advanced/"

# Empty list to store DataFrames
frames = []

# Loop through each year and team
for year in range(2020, 2024):
    for team in teams:
        url = base_url.format(team=team, year=year)
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers)
        time.sleep(5)  # Avoid hitting rate limits

        soup = BeautifulSoup(response.content, "html.parser")
        table = soup.find("table", id="wnba_tgl_advanced")

        if table is not None:
            df_team = pd.read_html(StringIO(str(table)))[0]

            # Combine multi-level headers
            df_team.columns = [f"{a}_{b}" for a, b in df_team.columns]

            # Drop extra unnamed columns
            drop_cols = [
                'Unnamed: 6_level_0_Unnamed: 6_level_1',
                'Unnamed: 9_level_0_Unnamed: 9_level_1',
                'Unnamed: 26_level_0_Unnamed: 26_level_1'
            ]
            df_team = df_team.drop(columns=drop_cols, errors='ignore')

            # Rename key columns
            df_team = df_team.rename(columns={
                'Unnamed: 0_level_0_Rk': 'Rk',
                'Unnamed: 1_level_0_G#': 'G#',
                'Unnamed: 2_level_0_Date': 'Date',
                'Unnamed: 4_level_0_Opp': 'Opp',
                'Unnamed: 5_level_0_W/L': 'W/L',
                'Unnamed: 7_level_0_Tm': 'Team_Score',
                'Unnamed: 8_level_0_Opp': 'Opp_Score'
            })

            # Add team and year columns at the beginning
            df_team.insert(0, "Year", year)
            df_team.insert(0, "Team", team)

            frames.append(df_team)
        else:
            print(f"No table found for {team}, {year}")

# Combine all collected DataFrames into team_gamelog_df
team_advanced_gamelog_df = pd.concat(frames, ignore_index=True)

In [8]:
team_advanced_gamelog_df.shape

(1656, 30)

In [9]:
team_advanced_gamelog_df.head()

,Team,Year,Rk,Unnamed: 1_level_0_Date,Unnamed: 2_level_0_Unnamed: 2_level_1,Unnamed: 3_level_0_Opp,Unnamed: 4_level_0_W/L,Unnamed: 5_level_0_Tm,Unnamed: 6_level_0_Opp,Unnamed: 7_level_0_Unnamed: 7_level_1,...,Unnamed: 18_level_0_Unnamed: 18_level_1,Offensive Four Factors_eFG%,Offensive Four Factors_TOV%,Offensive Four Factors_ORB%,Offensive Four Factors_FT/FGA,Unnamed: 23_level_0_Unnamed: 23_level_1,Defensive Four Factors_eFG%,Defensive Four Factors_TOV%,Defensive Four Factors_DRB%,Defensive Four Factors_FT/FGA
0,ATL,2020,1,2020-07-26,NaN,DAL,W,105,95,NaN,...,NaN,.605,17.2,16.0,.484,NaN,.519,13.0,78.9,.179
1,ATL,2020,2,2020-07-29,@,LVA,L,70,100,NaN,...,NaN,.436,17.4,17.5,.129,NaN,.577,18.7,56.3,.254
2,ATL,2020,3,2020-07-31,NaN,NYL,W,84,78,NaN,...,NaN,.393,14.5,40.5,.333,NaN,.438,15.9,76.5,.208
3,ATL,2020,4,2020-08-02,@,IND,L,77,93,NaN,...,NaN,.507,14.2,17.9,.101,NaN,.576,16.6,70.0,.258
4,ATL,2020,5,2020-08-04,NaN,PHO,L,74,81,NaN,...,NaN,.500,25.4,17.9,.194,NaN,.413,10.6,75.0,.253

In [11]:
# Flatten multi-level column headers
team_advanced_gamelog_df.columns = [col.split('_')[-1] if 'Unnamed' in col else col for col in team_advanced_gamelog_df.columns]

# Verify flattened columns
print(team_advanced_gamelog_df.columns.tolist())

['Team', 'Year', 'Rk', 'Date', '1', 'Opp', 'W/L', 'Tm', 'Opp', '1', 'Advanced_ORtg', 'Advanced_DRtg', 'Advanced_Pace', 'Advanced_FTr', 'Advanced_3PAr', 'Advanced_TS%', 'Advanced_TRB%', 'Advanced_AST%', 'Advanced_STL%', 'Advanced_BLK%', '1', 'Offensive Four Factors_eFG%', 'Offensive Four Factors_TOV%', 'Offensive Four Factors_ORB%', 'Offensive Four Factors_FT/FGA', '1', 'Defensive Four Factors_eFG%', 'Defensive Four Factors_TOV%', 'Defensive Four Factors_DRB%', 'Defensive Four Factors_FT/FGA']

In [12]:
for col in team_advanced_gamelog_df.columns:
    print(col)

Team
Year
Rk
Date
1
Opp
W/L
Tm
Opp
1
Advanced_ORtg
Advanced_DRtg
Advanced_Pace
Advanced_FTr
Advanced_3PAr
Advanced_TS%
Advanced_TRB%
Advanced_AST%
Advanced_STL%
Advanced_BLK%
1
Offensive Four Factors_eFG%
Offensive Four Factors_TOV%
Offensive Four Factors_ORB%
Offensive Four Factors_FT/FGA
1
Defensive Four Factors_eFG%
Defensive Four Factors_TOV%
Defensive Four Factors_DRB%
Defensive Four Factors_FT/FGA

In [14]:
correct_headers = [
    'Team', 'Year', 'Rk', 'Date', 'home_away', 'Opp', 'win_loss', 'team_score', 'opp_score', 'delete1',
    'Advanced_ORtg', 'Advanced_DRtg', 'Advanced_Pace', 'Advanced_FTr', 'Advanced_3PAr',
    'Advanced_TS%', 'Advanced_TRB%', 'Advanced_AST%', 'Advanced_STL%', 'Advanced_BLK%',
    'delete2', 'Offensive_Four_Factors_eFG%', 'Offensive_Four_Factors_TOV%',
    'Offensive_Four_Factors_ORB%', 'Offensive_Four_Factors_FT/FGA', 'delete3',
    'Defensive_Four_Factors_eFG%', 'Defensive_Four_Factors_TOV%',
    'Defensive_Four_Factors_DRB%', 'Defensive_Four_Factors_FT/FGA'
]

In [15]:
team_advanced_gamelog_df.columns = correct_headers

# Quick check
print(team_advanced_gamelog_df.columns.tolist())

['Team', 'Year', 'Rk', 'Date', 'home_away', 'Opp', 'win_loss', 'team_score', 'opp_score', 'delete1', 'Advanced_ORtg', 'Advanced_DRtg', 'Advanced_Pace', 'Advanced_FTr', 'Advanced_3PAr', 'Advanced_TS%', 'Advanced_TRB%', 'Advanced_AST%', 'Advanced_STL%', 'Advanced_BLK%', 'delete2', 'Offensive_Four_Factors_eFG%', 'Offensive_Four_Factors_TOV%', 'Offensive_Four_Factors_ORB%', 'Offensive_Four_Factors_FT/FGA', 'delete3', 'Defensive_Four_Factors_eFG%', 'Defensive_Four_Factors_TOV%', 'Defensive_Four_Factors_DRB%', 'Defensive_Four_Factors_FT/FGA']

In [16]:
for col in team_advanced_gamelog_df.columns:
    print(col)

Team
Year
Rk
Date
home_away
Opp
win_loss
team_score
opp_score
delete1
Advanced_ORtg
Advanced_DRtg
Advanced_Pace
Advanced_FTr
Advanced_3PAr
Advanced_TS%
Advanced_TRB%
Advanced_AST%
Advanced_STL%
Advanced_BLK%
delete2
Offensive_Four_Factors_eFG%
Offensive_Four_Factors_TOV%
Offensive_Four_Factors_ORB%
Offensive_Four_Factors_FT/FGA
delete3
Defensive_Four_Factors_eFG%
Defensive_Four_Factors_TOV%
Defensive_Four_Factors_DRB%
Defensive_Four_Factors_FT/FGA

In [17]:
# Drop unnecessary columns
team_advanced_gamelog_df = team_advanced_gamelog_df.drop(columns=['delete1', 'delete2', 'delete3'])

# Verify columns after drop
print(team_advanced_gamelog_df.columns.tolist())

['Team', 'Year', 'Rk', 'Date', 'home_away', 'Opp', 'win_loss', 'team_score', 'opp_score', 'Advanced_ORtg', 'Advanced_DRtg', 'Advanced_Pace', 'Advanced_FTr', 'Advanced_3PAr', 'Advanced_TS%', 'Advanced_TRB%', 'Advanced_AST%', 'Advanced_STL%', 'Advanced_BLK%', 'Offensive_Four_Factors_eFG%', 'Offensive_Four_Factors_TOV%', 'Offensive_Four_Factors_ORB%', 'Offensive_Four_Factors_FT/FGA', 'Defensive_Four_Factors_eFG%', 'Defensive_Four_Factors_TOV%', 'Defensive_Four_Factors_DRB%', 'Defensive_Four_Factors_FT/FGA']

In [18]:
# Lowercase all column names
team_advanced_gamelog_df.columns = team_advanced_gamelog_df.columns.str.lower()

In [20]:
# Drop rows where 'opp' column is null
team_advanced_gamelog_df = team_advanced_gamelog_df.dropna(subset=['opp'])

# Verify rows dropped
print(team_advanced_gamelog_df['opp'].isnull().sum())  # should print 0

0

In [22]:
# Remove header rows mistakenly included in data
team_advanced_gamelog_df = team_advanced_gamelog_df[team_advanced_gamelog_df['date'] != 'Date']

# Confirm the rows were removed
print((team_advanced_gamelog_df['date'] == 'Date').sum())  # should print 0

0

In [23]:
# Ensure 'date' is datetime
team_advanced_gamelog_df['date'] = pd.to_datetime(team_advanced_gamelog_df['date'])

# Create 'day' and 'month' columns
team_advanced_gamelog_df['day'] = team_advanced_gamelog_df['date'].dt.day
team_advanced_gamelog_df['month'] = team_advanced_gamelog_df['date'].dt.month

# Drop original 'date' column
team_advanced_gamelog_df = team_advanced_gamelog_df.drop(columns=['date'])

In [24]:
# Replace specific characters in column names
team_advanced_gamelog_df.columns = (
    team_advanced_gamelog_df.columns
    .str.replace('%', '_pct', regex=False)
    .str.replace('/', '_', regex=False)
    .str.replace('-', '_', regex=False)
)

In [26]:
# Drop original 'rk' column
team_advanced_gamelog_df = team_advanced_gamelog_df.drop(columns=['rk'])

In [27]:
for col in team_advanced_gamelog_df.columns:
    print(col)

team
year
home_away
opp
win_loss
team_score
opp_score
advanced_ortg
advanced_drtg
advanced_pace
advanced_ftr
advanced_3par
advanced_ts_pct
advanced_trb_pct
advanced_ast_pct
advanced_stl_pct
advanced_blk_pct
offensive_four_factors_efg_pct
offensive_four_factors_tov_pct
offensive_four_factors_orb_pct
offensive_four_factors_ft_fga
defensive_four_factors_efg_pct
defensive_four_factors_tov_pct
defensive_four_factors_drb_pct
defensive_four_factors_ft_fga
day
month

In [28]:
df_gamelogs.shape

(1608, 41)

In [29]:
team_advanced_gamelog_df.shape

(1560, 27)

In [31]:
print(df_gamelogs['team_score'].dtype)
print(team_advanced_gamelog_df['team_score'].dtype)

float64
object

In [32]:
# Convert 'team_score' to numeric safely
team_advanced_gamelog_df['team_score'] = pd.to_numeric(team_advanced_gamelog_df['team_score'], errors='coerce')

In [34]:
# Convert 'team_score' to numeric safely
team_advanced_gamelog_df['opp_score'] = pd.to_numeric(team_advanced_gamelog_df['opp_score'], errors='coerce')

In [35]:
# Merge DataFrames on specified columns
df_merged_gamelogs = pd.merge(
    df_gamelogs,
    team_advanced_gamelog_df,
    on=['team', 'year', 'home_away', 'opp', 'win_loss', 'day', 'month', 'team_score', 'opp_score'],
    how='left'
)

# Verify merged result
print(df_merged_gamelogs.head())
print(df_merged_gamelogs.shape)

  team  year home_away  opp win_loss  team_score  opp_score team_fg team_fga  \
0  ATL  2020       NaN  DAL        W       105.0       95.0      34       62
1  ATL  2020         @  LVA        L        70.0      100.0      28       70
2  ATL  2020       NaN  NYL        W        84.0       78.0      28       75
3  ATL  2020         @  IND        L        77.0       93.0      33       69
4  ATL  2020       NaN  PHO        L        74.0       81.0      29       62

  team_fg_pct  ... advanced_stl_pct advanced_blk_pct  \
0        .548  ...              8.0              8.0
1        .400  ...             14.2              8.1
2        .373  ...              9.7              4.7
3        .478  ...              7.7              0.0
4        .468  ...              8.5              3.6

  offensive_four_factors_efg_pct offensive_four_factors_tov_pct  \
0                           .605                           17.2
1                           .436                           17.4
2                           .393                           14.5
3                           .507                           14.2
4                           .500                           25.4

  offensive_four_factors_orb_pct offensive_four_factors_ft_fga  \
0                           16.0                          .484
1                           17.5                          .129
2                           40.5                          .333
3                           17.9                          .101
4                           17.9                          .194

  defensive_four_factors_efg_pct defensive_four_factors_tov_pct  \
0                           .519                           13.0
1                           .577                           18.7
2                           .438                           15.9
3                           .576                           16.6
4                           .413                           10.6

  defensive_four_factors_drb_pct defensive_four_factors_ft_fga
0                           78.9                          .179
1                           56.3                          .254
2                           76.5                          .208
3                           70.0                          .258
4                           75.0                          .253

[5 rows x 59 columns]
(1608, 59)

In [36]:
# Check columns with nulls, sorted descending
print(df_merged_gamelogs.isnull().sum()[lambda x: x > 0].sort_values(ascending=False))

home_away                         828
opp                                48
win_loss                           48
team_score                         48
opp_score                          48
month                              48
day                                48
advanced_ortg                      48
advanced_drtg                      48
advanced_ftr                       48
advanced_pace                      48
offensive_four_factors_efg_pct     48
offensive_four_factors_tov_pct     48
advanced_3par                      48
advanced_ts_pct                    48
advanced_trb_pct                   48
advanced_ast_pct                   48
advanced_stl_pct                   48
advanced_blk_pct                   48
defensive_four_factors_efg_pct     48
defensive_four_factors_tov_pct     48
offensive_four_factors_orb_pct     48
offensive_four_factors_ft_fga      48
defensive_four_factors_drb_pct     48
defensive_four_factors_ft_fga      48
team_ft_pct                         1
opponent_ft_pct                     1
dtype: int64

In [37]:
# Convert 'home_away': '@' -> 0, else -> 1
df_merged_gamelogs['home_away'] = df_merged_gamelogs['home_away'].apply(lambda x: 0 if x == '@' else 1)

In [39]:
# Drop rows with null 'opp'
df_merged_gamelogs = df_merged_gamelogs.dropna(subset=['opp'])

# Quick verification
print(df_merged_gamelogs['opp'].isnull().sum())  # Should print 0

0

In [40]:
# Check columns with nulls, sorted descending
print(df_merged_gamelogs.isnull().sum()[lambda x: x > 0].sort_values(ascending=False))

team_ft_pct        1
opponent_ft_pct    1
dtype: int64

In [41]:
# Replace nulls with 0 in specified columns
df_merged_gamelogs[['team_ft_pct', 'opponent_ft_pct']] = df_merged_gamelogs[['team_ft_pct', 'opponent_ft_pct']].fillna(0)

# Quick verification
print(df_merged_gamelogs[['team_ft_pct', 'opponent_ft_pct']].isnull().sum())

team_ft_pct        0
opponent_ft_pct    0
dtype: int64

In [42]:
for col in df_merged_gamelogs.columns:
    print(col)

team
year
home_away
opp
win_loss
team_score
opp_score
team_fg
team_fga
team_fg_pct
team_3p
team_3pa
team_3p_pct
team_ft
team_fta
team_ft_pct
team_orb
team_trb
team_ast
team_stl
team_blk
team_tov
team_pf
opponent_fg
opponent_fga
opponent_fg_pct
opponent_3p
opponent_3pa
opponent_3p_pct
opponent_ft
opponent_fta
opponent_ft_pct
opponent_orb
opponent_trb
opponent_ast
opponent_stl
opponent_blk
opponent_tov
opponent_pf
day
month
advanced_ortg
advanced_drtg
advanced_pace
advanced_ftr
advanced_3par
advanced_ts_pct
advanced_trb_pct
advanced_ast_pct
advanced_stl_pct
advanced_blk_pct
offensive_four_factors_efg_pct
offensive_four_factors_tov_pct
offensive_four_factors_orb_pct
offensive_four_factors_ft_fga
defensive_four_factors_efg_pct
defensive_four_factors_tov_pct
defensive_four_factors_drb_pct
defensive_four_factors_ft_fga

In [44]:
# Add 'year' column set to 2024
df_2024_gamelogs['year'] = 2024

In [45]:
# Columns unique to df_merged_gamelogs
unique_to_merged = set(df_merged_gamelogs.columns) - set(df_2024_gamelogs.columns)

# Columns unique to df_2024_gamelogs
unique_to_2024 = set(df_2024_gamelogs.columns) - set(df_merged_gamelogs.columns)

# Print clearly
print("Unique to df_merged_gamelogs:", unique_to_merged)
print("Unique to df_2024_gamelogs:", unique_to_2024)

Unique to df_merged_gamelogs: {'defensive_four_factors_ft_fga', 'offensive_four_factors_ft_fga'}
Unique to df_2024_gamelogs: {'defensive_four_factors_efg_pct_by_team_home_away', 'advanced_3par_by_team_day_of_week', 'team_fta_by_team_day_of_week', 'opponent_tov_by_team_travel_distance', 'team_ft_by_team_day_of_week', 'offensive_four_factors_ft_per_fga_by_team_day_of_week', 'team_day_median_allowed_by_team_travel_distance', 'team_pf_by_team_home_away', 'advanced_ftr_by_team_home_away', 'team_day_median_score_by_team_day_of_week', 'defensive_four_factors_tov_pct_by_team_travel_distance', 'team_ft_pct_by_team_home_away', 'travel_distance_by_team_day_of_week', 'team_stl_by_team_home_away', 'advanced_trb_pct_by_team_day_of_week', 'advanced_stl_pct_by_team_day_of_week', 'advanced_ortg_by_team_day_of_week', 'team_vs_opp_homeaway_median_score_by_team_day_of_week', 'team_home_or_away_median_score', 'advanced_ftr_by_team_day_of_week', 'team_orb_by_team_day_of_week', 'team_home_or_away_median_score_by_team_day_of_week', 'opponent_ft_by_team_day_of_week', 'team_fg_pct_by_team_home_away', 'opponent_fta_by_team_travel_distance', 'advanced_stl_pct_by_team_travel_distance', 'team_day_median_allowed_by_team_home_away', 'opponent_fga_by_team_travel_distance', 'team_3p_by_team_home_away', 'team_fga_by_team_day_of_week', 'team_day_median_allowed', 'opponent_3p_pct_by_team_day_of_week', 'team_ft_by_team_home_away', 'advanced_pace_by_team_home_away', 'advanced_drtg_by_team_travel_distance', 'team_trb_by_team_day_of_week', 'advanced_ortg_by_team_home_away', 'team_fga_by_team_travel_distance', 'opponent_ast_by_team_travel_distance', 'opponent_ast_by_team_home_away', 'team_ast_by_team_day_of_week', 'opponent_3pa_by_team_day_of_week', 'team_3pa_by_team_home_away', 'home_away_by_team_day_of_week', 'opponent_pf_by_team_day_of_week', 'advanced_blk_pct_by_team_home_away', 'offensive_four_factors_ft_per_fga_by_team_home_away', 'advanced_stl_pct_by_team_home_away', 'offensive_four_factors_orb_pct_by_team_day_of_week', 'opponent_3p_by_team_travel_distance', 'opponent_3pa_by_team_travel_distance', 'opponent_trb_by_team_home_away', 'team_3pa_by_team_day_of_week', 'team_fg_by_team_travel_distance', 'offensive_four_factors_ft_per_fga', 'team_pf_by_team_day_of_week', 'day_of_week_by_team_day_of_week', 'day_of_week_by_team_travel_distance', 'opponent_blk_by_team_travel_distance', 'opponent_tov_by_team_day_of_week', 'offensive_four_factors_tov_pct_by_team_day_of_week', 'opponent_3p_pct_by_team_home_away', 'median_score_for_by_team_day_of_week', 'team_home_or_away_median_allowed_by_team_day_of_week', 'offensive_four_factors_orb_pct_by_team_home_away', 'median_score_for_by_team_home_away', 'offensive_four_factors_efg_pct_by_team_day_of_week', 'team_orb_by_team_home_away', 'defensive_four_factors_ft_per_fga_by_team_home_away', 'team_vs_opp_median_score_by_team_travel_distance', 'win_loss_by_team_home_away', 'travel_distance_by_team_home_away', 'team_home_or_away_median_allowed', 'travel_distance', 'offensive_four_factors_ft_per_fga_by_team_travel_distance', 'offensive_four_factors_efg_pct_by_team_home_away', 'day_by_team_home_away', 'opponent_fg_pct_by_team_home_away', 'opponent_fta_by_team_home_away', 'defensive_four_factors_drb_pct_by_team_home_away', 'team_vs_opp_median_score_by_team_day_of_week', 'advanced_ast_pct_by_team_home_away', 'team_vs_opp_homeaway_median_score_by_team_home_away', 'team_trb_by_team_home_away', 'day_of_week', 'month_by_team_day_of_week', 'opponent_fg_pct_by_team_day_of_week', 'month_by_team_home_away', 'team_vs_opp_homeaway_median_score', 'day_by_team_travel_distance', 'day_by_team_day_of_week', 'opponent_fta_by_team_day_of_week', 'team_day_median_allowed_by_team_day_of_week', 'defensive_four_factors_tov_pct_by_team_day_of_week', 'team_3p_by_team_day_of_week', 'opponent_fg_by_team_day_of_week', 'offensive_four_factors_tov_pct_by_team_home_away', 'offensive_four_factors_tov_pct_by_team_travel_distance', 'team_blk_by_team_day_of_week', 'opponent_fg_pct_by_team_travel_distance', 'win_loss_by_team_travel_distance', 'team_tov_by_team_travel_distance', 'opponent_stl_by_team_home_away', 'team_stl_by_team_travel_distance', 'opponent_ft_pct_by_team_home_away', 'team_3p_pct_by_team_day_of_week', 'defensive_four_factors_ft_per_fga_by_team_travel_distance', 'team_blk_by_team_home_away', 'advanced_ast_pct_by_team_day_of_week', 'median_score_against_by_team_travel_distance', 'defensive_four_factors_ft_per_fga', 'opponent_orb_by_team_day_of_week', 'advanced_drtg_by_team_day_of_week', 'team_home_or_away_median_score_by_team_travel_distance', 'team_vs_opp_homeaway_median_score_by_team_travel_distance', 'advanced_trb_pct_by_team_travel_distance', 'opponent_3p_by_team_home_away', 'opponent_stl_by_team_day_of_week', 'opponent_ft_pct_by_team_travel_distance', 'team_tov_by_team_home_away', 'opponent_ft_by_team_home_away', 'team_fg_pct_by_team_travel_distance', 'team_pf_by_team_travel_distance', 'median_score_against', 'advanced_ts_pct_by_team_travel_distance', 'travel_distance_by_team_travel_distance', 'team_fg_by_team_day_of_week', 'team_ft_pct_by_team_day_of_week', 'advanced_blk_pct_by_team_travel_distance', 'team_home_or_away_median_score_by_team_home_away', 'opponent_fg_by_team_home_away', 'opponent_3pa_by_team_home_away', 'opponent_ft_pct_by_team_day_of_week', 'opponent_ft_by_team_travel_distance', 'opponent_fga_by_team_home_away', 'day_of_week_by_team_home_away', 'opponent_blk_by_team_day_of_week', 'defensive_four_factors_drb_pct_by_team_travel_distance', 'team_tov_by_team_day_of_week', 'team_day_median_score_by_team_travel_distance', 'advanced_3par_by_team_travel_distance', 'team_fga_by_team_home_away', 'team_fta_by_team_home_away', 'defensive_four_factors_ft_per_fga_by_team_day_of_week', 'advanced_blk_pct_by_team_day_of_week', 'team_ast_by_team_travel_distance', 'opponent_trb_by_team_travel_distance', 'opponent_ast_by_team_day_of_week', 'team_fg_by_team_home_away', 'defensive_four_factors_efg_pct_by_team_day_of_week', 'team_blk_by_team_travel_distance', 'team_fta_by_team_travel_distance', 'opponent_fga_by_team_day_of_week', 'month_by_team_travel_distance', 'home_away_by_team_travel_distance', 'opponent_fg_by_team_travel_distance', 'win_loss_by_team_day_of_week', 'team_stl_by_team_day_of_week', 'team_fg_pct_by_team_day_of_week', 'advanced_ts_pct_by_team_day_of_week', 'team_3p_pct_by_team_travel_distance', 'team_trb_by_team_travel_distance', 'team_ft_by_team_travel_distance', 'advanced_pace_by_team_travel_distance', 'median_score_against_by_team_home_away', 'median_score_for_by_team_travel_distance', 'median_score_for', 'home_away_by_team_home_away', 'defensive_four_factors_drb_pct_by_team_day_of_week', 'team_3p_pct_by_team_home_away', 'opponent_orb_by_team_home_away', 'offensive_four_factors_efg_pct_by_team_travel_distance', 'opponent_pf_by_team_home_away', 'advanced_trb_pct_by_team_home_away', 'team_ft_pct_by_team_travel_distance', 'advanced_pace_by_team_day_of_week', 'team_3p_by_team_travel_distance', 'advanced_ftr_by_team_travel_distance', 'team_3pa_by_team_travel_distance', 'team_day_median_score', 'opponent_3p_pct_by_team_travel_distance', 'advanced_ts_pct_by_team_home_away', 'g_num', 'opponent_orb_by_team_travel_distance', 'advanced_ortg_by_team_travel_distance', 'opponent_3p_by_team_day_of_week', 'median_score_against_by_team_day_of_week', 'team_home_or_away_median_allowed_by_team_home_away', 'defensive_four_factors_tov_pct_by_team_home_away', 'opponent_blk_by_team_home_away', 'advanced_ast_pct_by_team_travel_distance', 'team_day_median_score_by_team_home_away', 'opponent_stl_by_team_travel_distance', 'opponent_trb_by_team_day_of_week', 'opponent_tov_by_team_home_away', 'offensive_four_factors_orb_pct_by_team_travel_distance', 'team_orb_by_team_travel_distance', 'opponent_pf_by_team_travel_distance', 'defensive_four_factors_efg_pct_by_team_travel_distance', 'team_home_or_away_median_allowed_by_team_travel_distance', 'team_ast_by_team_home_away', 'advanced_drtg_by_team_home_away', 'team_vs_opp_median_score', 'advanced_3par_by_team_home_away', 'team_vs_opp_median_score_by_team_home_away'}

In [46]:
# Concatenate vertically into df
df = pd.concat([df_merged_gamelogs, df_2024_gamelogs], ignore_index=True)

# Verify shape clearly
print(df.shape)
print(df.head())

(2040, 264)
  team  year  home_away  opp win_loss  team_score  opp_score team_fg team_fga  \
0  ATL  2020          1  DAL        W       105.0       95.0      34       62
1  ATL  2020          0  LVA        L        70.0      100.0      28       70
2  ATL  2020          1  NYL        W        84.0       78.0      28       75
3  ATL  2020          0  IND        L        77.0       93.0      33       69
4  ATL  2020          1  PHO        L        74.0       81.0      29       62

  team_fg_pct  ... day_of_week_by_team_travel_distance  \
0        .548  ...                                 NaN
1        .400  ...                                 NaN
2        .373  ...                                 NaN
3        .478  ...                                 NaN
4        .468  ...                                 NaN

  team_vs_opp_median_score_by_team_travel_distance  \
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4                                              NaN

  team_vs_opp_homeaway_median_score_by_team_travel_distance  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  team_home_or_away_median_score_by_team_travel_distance  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  team_home_or_away_median_allowed_by_team_travel_distance  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

  team_day_median_score_by_team_travel_distance  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN

  team_day_median_allowed_by_team_travel_distance  \
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN

  travel_distance_by_team_travel_distance  \
0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4                                     NaN

  median_score_for_by_team_travel_distance  \
0                                      NaN
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN

  median_score_against_by_team_travel_distance
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN

[5 rows x 264 columns]

In [48]:
# Check columns with nulls, sorted descending
print(df.isnull().sum()[lambda x: x > 0].sort_values(ascending=False))

g_num                                            1560
defensive_four_factors_ft_per_fga                1560
offensive_four_factors_ft_per_fga                1560
day_of_week                                      1560
team_vs_opp_median_score                         1560
                                                 ...
team_day_median_score_by_team_travel_distance    1560
median_score_for_by_team_travel_distance         1560
median_score_against_by_team_travel_distance     1560
offensive_four_factors_ft_fga                     480
defensive_four_factors_ft_fga                     480
Length: 207, dtype: int64

In [49]:
# Drop columns with any null values
df = df.dropna(axis=1)

# Verify no null columns remain
print(df.isnull().sum().sum())  # Should print 0
print(df.shape)  # Confirm new dimensions

0
(2040, 57)

In [50]:
# load the player game logs CSV from the data folder
df_personas = pd.read_csv("LHL-final-final-project/data/all_persona_and_team_data.csv")


# preview
df_personas.head()

,team,year,home_away,opp,team_score,opp_score,day,month,all_around_star,and_one_machine,...,team_3par,team_ts%,team_efg%,team_tov%,team_orb%,team_ft/fga,team_efg%.1,team_tov%.1,team_drb%,team_ft/fga.1
0,ATL,2020,1.0,DAL,105,95,26.0,7.0,0.0,0.0,...,0.237,0.518,0.484,15.5,25.3,0.172,0.513,14.1,75.7,0.231
1,ATL,2020,0.0,LVA,70,100,29.0,7.0,0.0,0.0,...,0.237,0.518,0.484,15.5,25.3,0.172,0.513,14.1,75.7,0.231
2,ATL,2020,1.0,NYL,84,78,31.0,7.0,0.0,0.0,...,0.237,0.518,0.484,15.5,25.3,0.172,0.513,14.1,75.7,0.231
3,ATL,2020,0.0,IND,77,93,2.0,8.0,0.0,0.0,...,0.237,0.518,0.484,15.5,25.3,0.172,0.513,14.1,75.7,0.231
4,ATL,2020,1.0,PHO,74,81,4.0,8.0,0.0,0.0,...,0.237,0.518,0.484,15.5,25.3,0.172,0.513,14.1,75.7,0.231

In [51]:
for col in df_personas.columns:
    print(col)

team
year
home_away
opp
team_score
opp_score
day
month
all_around_star
and_one_machine
catch_and_shoot
corner_3_specialist
defensive_anchor
defensive_rebounder
efficient_scorer
elite_scorer
fast_break_threat
floor_general
free_throw_generator
glass_cleaner
heave_chucker
impact_bench
midrange_sniper
offensive_hub
offensive_rebounder
playmaker
plus_minus_driver
rim_protector
self_creator
slasher
steal_artist
stretch_big
three_point_specialist
turnover_prone
volume_shooter
team_per_game_fg
team_per_game_fga
team_per_game_fg%
team_per_game_3p
team_per_game_3pa
team_per_game_3p%
team_per_game_2p
team_per_game_2pa
team_per_game_2p%
team_per_game_ft
team_per_game_fta
team_per_game_ft%
team_per_game_orb
team_per_game_drb
team_per_game_trb
team_per_game_ast
team_per_game_stl
team_per_game_blk
team_per_game_tov
team_per_game_pf
team_per_game_pts
opp_per_game_fg
opp_per_game_fga
opp_per_game_fg%
opp_per_game_3p
opp_per_game_3pa
opp_per_game_3p%
opp_per_game_2p
opp_per_game_2pa
opp_per_game_2p%
opp_per_game_ft
opp_per_game_fta
opp_per_game_ft%
opp_per_game_orb
opp_per_game_drb
opp_per_game_trb
opp_per_game_ast
opp_per_game_stl
opp_per_game_blk
opp_per_game_tov
opp_per_game_pf
opp_per_game_pts
team_per_poss_fg
team_per_poss_fga
team_per_poss_fg%
team_per_poss_3p
team_per_poss_3pa
team_per_poss_3p%
team_per_poss_2p
team_per_poss_2pa
team_per_poss_2p%
team_per_poss_ft
team_per_poss_fta
team_per_poss_ft%
team_per_poss_orb
team_per_poss_drb
team_per_poss_trb
team_per_poss_ast
team_per_poss_stl
team_per_poss_blk
team_per_poss_tov
team_per_poss_pf
team_per_poss_pts
opp_per_poss_fg
opp_per_poss_fga
opp_per_poss_fg%
opp_per_poss_3p
opp_per_poss_3pa
opp_per_poss_3p%
opp_per_poss_2p
opp_per_poss_2pa
opp_per_poss_2p%
opp_per_poss_ft
opp_per_poss_fta
opp_per_poss_ft%
opp_per_poss_orb
opp_per_poss_drb
opp_per_poss_trb
opp_per_poss_ast
opp_per_poss_stl
opp_per_poss_blk
opp_per_poss_tov
opp_per_poss_pf
opp_per_poss_pts
team_fg%
team_dist.
team_% of fga by distance_2p
team_% of fga by distance_0-3
team_% of fga by distance_3-10
team_% of fga by distance_10-16
team_% of fga by distance_16-3p
team_% of fga by distance_3p
team_fg% by distance_2p
team_fg% by distance_0-3
team_fg% by distance_3-10
team_fg% by distance_10-16
team_fg% by distance_16-3p
team_fg% by distance_3p
team_% of fg ast'd_2p
team_% of fg ast'd_3p
team_corner_%3pa
team_corner_3p%
opp_fg%
opp_dist.
opp_% of fga by distance_2p
opp_% of fga by distance_0-3
opp_% of fga by distance_3-10
opp_% of fga by distance_10-16
opp_% of fga by distance_16-3p
opp_% of fga by distance_3p
opp_fg% by distance_2p
opp_fg% by distance_0-3
opp_fg% by distance_3-10
opp_fg% by distance_10-16
opp_fg% by distance_16-3p
opp_fg% by distance_3p
opp_% of fg ast'd_2p
opp_% of fg ast'd_3p
opp_corner_%3pa
opp_corner_3p%
team_age
team_mov
team_sos
team_srs
team_ortg
team_drtg
team_nrtg
team_pace
team_ftr
team_3par
team_ts%
team_efg%
team_tov%
team_orb%
team_ft/fga
team_efg%.1
team_tov%.1
team_drb%
team_ft/fga.1

In [52]:
# List of columns to merge
persona_cols = [
    'team', 'year', 'opp', 'day', 'month',
    'all_around_star', 'and_one_machine', 'catch_and_shoot', 'corner_3_specialist',
    'defensive_anchor', 'defensive_rebounder', 'efficient_scorer', 'elite_scorer',
    'fast_break_threat', 'floor_general', 'free_throw_generator', 'glass_cleaner',
    'heave_chucker', 'impact_bench', 'midrange_sniper', 'offensive_hub',
    'offensive_rebounder', 'playmaker', 'plus_minus_driver', 'rim_protector',
    'self_creator', 'slasher', 'steal_artist', 'stretch_big',
    'three_point_specialist', 'turnover_prone', 'volume_shooter'
]

# Merge clearly into df
df = pd.merge(
    df,
    df_personas[persona_cols],
    on=['team', 'year', 'opp', 'day', 'month'],
    how='left'
)

# Verify merge results
print(df.shape)
print(df.head())

(2040, 84)
  team  year  home_away  opp win_loss  team_score  opp_score team_fg team_fga  \
0  ATL  2020          1  DAL        W       105.0       95.0      34       62
1  ATL  2020          0  LVA        L        70.0      100.0      28       70
2  ATL  2020          1  NYL        W        84.0       78.0      28       75
3  ATL  2020          0  IND        L        77.0       93.0      33       69
4  ATL  2020          1  PHO        L        74.0       81.0      29       62

  team_fg_pct  ... playmaker plus_minus_driver rim_protector self_creator  \
0        .548  ...       0.0               0.0           0.0          1.0
1        .400  ...       0.0               0.0           0.0          1.0
2        .373  ...       0.0               0.0           0.0          1.0
3        .478  ...       0.0               0.0           0.0          1.0
4        .468  ...       0.0               0.0           0.0          1.0

  slasher steal_artist stretch_big three_point_specialist turnover_prone  \
0     0.0          0.0         0.0                    0.0            1.0
1     0.0          0.0         0.0                    0.0            1.0
2     0.0          0.0         0.0                    0.0            1.0
3     0.0          0.0         0.0                    0.0            1.0
4     0.0          0.0         0.0                    0.0            1.0

  volume_shooter
0            1.0
1            1.0
2            1.0
3            1.0
4            1.0

[5 rows x 84 columns]

In [53]:
for col in df.columns:
  print(col)

team
year
home_away
opp
win_loss
team_score
opp_score
team_fg
team_fga
team_fg_pct
team_3p
team_3pa
team_3p_pct
team_ft
team_fta
team_ft_pct
team_orb
team_trb
team_ast
team_stl
team_blk
team_tov
team_pf
opponent_fg
opponent_fga
opponent_fg_pct
opponent_3p
opponent_3pa
opponent_3p_pct
opponent_ft
opponent_fta
opponent_ft_pct
opponent_orb
opponent_trb
opponent_ast
opponent_stl
opponent_blk
opponent_tov
opponent_pf
day
month
advanced_ortg
advanced_drtg
advanced_pace
advanced_ftr
advanced_3par
advanced_ts_pct
advanced_trb_pct
advanced_ast_pct
advanced_stl_pct
advanced_blk_pct
offensive_four_factors_efg_pct
offensive_four_factors_tov_pct
offensive_four_factors_orb_pct
defensive_four_factors_efg_pct
defensive_four_factors_tov_pct
defensive_four_factors_drb_pct
all_around_star
and_one_machine
catch_and_shoot
corner_3_specialist
defensive_anchor
defensive_rebounder
efficient_scorer
elite_scorer
fast_break_threat
floor_general
free_throw_generator
glass_cleaner
heave_chucker
impact_bench
midrange_sniper
offensive_hub
offensive_rebounder
playmaker
plus_minus_driver
rim_protector
self_creator
slasher
steal_artist
stretch_big
three_point_specialist
turnover_prone
volume_shooter

In [55]:
# Group by 'team' and sort clearly
df = df.sort_values(by=['team', 'year', 'month', 'day'], ascending=[True, True, True, True])

# Verify sorting
print(df[['team', 'year', 'month', 'day']].head(90))

    team  year  month   day
0    ATL  2020    7.0  26.0
1    ATL  2020    7.0  29.0
2    ATL  2020    7.0  31.0
3    ATL  2020    8.0   2.0
4    ATL  2020    8.0   4.0
..   ...   ...    ...   ...
679  ATL  2022    8.0   5.0
680  ATL  2022    8.0   7.0
681  ATL  2022    8.0   9.0
682  ATL  2022    8.0  12.0
683  ATL  2022    8.0  14.0

[90 rows x 4 columns]

In [57]:
# Create 'game_num' column counting each team's games
df['game_num'] = df.groupby('team').cumcount() + 1

# Verify results
print(df[['team', 'game_num']])

     team  game_num
0     ATL         1
1     ATL         2
2     ATL         3
3     ATL         4
4     ATL         5
...   ...       ...
2035  WAS       166
2036  WAS       167
2037  WAS       168
2038  WAS       169
2039  WAS       170

[2040 rows x 2 columns]

In [59]:
# Compute YTD mean team_score (excluding current game)
df['ytd_team_score_mean'] = (
    df.groupby(['team', 'year'])['team_score']
      .transform(lambda x: x.shift().expanding().mean())
      .fillna(0)
)

# Verify clearly
print(df[['team', 'year', 'team_score', 'ytd_team_score_mean']])

     team  year  team_score  ytd_team_score_mean
0     ATL  2020       105.0             0.000000
1     ATL  2020        70.0           105.000000
2     ATL  2020        84.0            87.500000
3     ATL  2020        77.0            86.333333
4     ATL  2020        74.0            84.000000
...   ...   ...         ...                  ...
2035  WAS  2024        89.0            79.285714
2036  WAS  2024        72.0            79.555556
2037  WAS  2024        73.0            79.351351
2038  WAS  2024        71.0            79.184211
2039  WAS  2024        92.0            78.974359

[2040 rows x 4 columns]

In [60]:
# Compute YTD median team_score (excluding current game)
df['ytd_team_score_median'] = (
    df.groupby(['team', 'year'])['team_score']
      .transform(lambda x: x.shift().expanding().median())
      .fillna(0)
)

# Verify result clearly
print(df[['team', 'year', 'team_score', 'ytd_team_score_median']].head(15))

   team  year  team_score  ytd_team_score_median
0   ATL  2020       105.0                    0.0
1   ATL  2020        70.0                  105.0
2   ATL  2020        84.0                   87.5
3   ATL  2020        77.0                   84.0
4   ATL  2020        74.0                   80.5
5   ATL  2020        92.0                   77.0
6   ATL  2020        75.0                   80.5
7   ATL  2020        82.0                   77.0
8   ATL  2020        63.0                   79.5
9   ATL  2020        80.0                   77.0
10  ATL  2020        67.0                   78.5
11  ATL  2020        91.0                   77.0
12  ATL  2020        85.0                   78.5
13  ATL  2020        78.0                   80.0
14  ATL  2020        79.0                   79.0

In [61]:
# Compute YTD minimum team_score (excluding current game)
df['ytd_team_score_min'] = (
    df.groupby(['team', 'year'])['team_score']
      .transform(lambda x: x.shift().expanding().min())
      .fillna(0)
)

# Verify result clearly
print(df[['team', 'year', 'team_score', 'ytd_team_score_min']].head(15))

   team  year  team_score  ytd_team_score_min
0   ATL  2020       105.0                 0.0
1   ATL  2020        70.0               105.0
2   ATL  2020        84.0                70.0
3   ATL  2020        77.0                70.0
4   ATL  2020        74.0                70.0
5   ATL  2020        92.0                70.0
6   ATL  2020        75.0                70.0
7   ATL  2020        82.0                70.0
8   ATL  2020        63.0                70.0
9   ATL  2020        80.0                63.0
10  ATL  2020        67.0                63.0
11  ATL  2020        91.0                63.0
12  ATL  2020        85.0                63.0
13  ATL  2020        78.0                63.0
14  ATL  2020        79.0                63.0

In [62]:
# Compute YTD maximum team_score (excluding current game)
df['ytd_team_score_max'] = (
    df.groupby(['team', 'year'])['team_score']
      .transform(lambda x: x.shift().expanding().max())
      .fillna(0)
)

# Quick verification
print(df[['team', 'year', 'team_score', 'ytd_team_score_max']].head(15))

   team  year  team_score  ytd_team_score_max
0   ATL  2020       105.0                 0.0
1   ATL  2020        70.0               105.0
2   ATL  2020        84.0               105.0
3   ATL  2020        77.0               105.0
4   ATL  2020        74.0               105.0
5   ATL  2020        92.0               105.0
6   ATL  2020        75.0               105.0
7   ATL  2020        82.0               105.0
8   ATL  2020        63.0               105.0
9   ATL  2020        80.0               105.0
10  ATL  2020        67.0               105.0
11  ATL  2020        91.0               105.0
12  ATL  2020        85.0               105.0
13  ATL  2020        78.0               105.0
14  ATL  2020        79.0               105.0

In [76]:
def correct_ytd_opp_mean(row):
    opp_games = df[
        (df['team'] == row['opp']) &
        (
            (df['year'] < row['year']) |
            ((df['year'] == row['year']) & (df['month'] < row['month'])) |
            ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
        )
    ]
    return opp_games['team_score'].mean() if not opp_games.empty else 0

# Apply directly and safely into df
df['ytd_opp_score_mean'] = df.apply(correct_ytd_opp_mean, axis=1)

# Verify clearly with your requested print
print(
    df.loc[
        (df['year'] == 2020) & ((df['team'] == 'NYL') | (df['opp'] == 'NYL')),
        ['team', 'opp', 'year', 'month', 'day', 'team_score', 'ytd_team_score_mean', 'ytd_opp_score_mean']
    ].sort_values(['month', 'day']).to_string(index=False)
)

team opp  year  month  day  team_score  ytd_team_score_mean  ytd_opp_score_mean
 NYL SEA  2020    7.0 25.0        71.0             0.000000            0.000000
 SEA NYL  2020    7.0 25.0        87.0             0.000000            0.000000
 DAL NYL  2020    7.0 29.0        93.0            95.000000           71.000000
 NYL DAL  2020    7.0 29.0        80.0            71.000000           95.000000
 ATL NYL  2020    7.0 31.0        84.0            87.500000           75.500000
 NYL ATL  2020    7.0 31.0        78.0            75.500000           87.500000
 NYL PHO  2020    8.0  2.0        67.0            76.333333           92.666667
 PHO NYL  2020    8.0  2.0        96.0            92.666667           76.333333
 MIN NYL  2020    8.0  5.0        92.0            76.000000           74.000000
 NYL MIN  2020    8.0  5.0        66.0            74.000000           76.000000
 NYL WAS  2020    8.0  7.0        74.0            72.400000           89.400000
 WAS NYL  2020    8.0  7.0        66.0            89.400000           72.400000
 LVA NYL  2020    8.0  9.0        78.0            88.166667           72.666667
 NYL LVA  2020    8.0  9.0        76.0            72.666667           88.166667
 LAS NYL  2020    8.0 11.0        93.0            85.428571           73.142857
 NYL LAS  2020    8.0 11.0        78.0            73.142857           85.428571
 IND NYL  2020    8.0 13.0        86.0            84.125000           73.750000
 NYL IND  2020    8.0 13.0        79.0            73.750000           84.125000
 MIN NYL  2020    8.0 15.0        94.0            78.777778           74.333333
 NYL MIN  2020    8.0 15.0        64.0            74.333333           78.777778
 NYL SEA  2020    8.0 18.0        64.0            73.300000           86.363636
 SEA NYL  2020    8.0 18.0       105.0            86.363636           73.300000
 CHI NYL  2020    8.0 20.0       101.0            85.916667           72.454545
 NYL CHI  2020    8.0 20.0        85.0            72.454545           85.916667
 CON NYL  2020    8.0 22.0        82.0            79.615385           73.500000
 NYL CON  2020    8.0 22.0        65.0            73.500000           79.615385
 CHI NYL  2020    8.0 25.0        99.0            87.071429           72.846154
 NYL CHI  2020    8.0 25.0       101.0            72.846154           87.071429
 LVA NYL  2020    8.0 29.0        80.0            88.500000           74.857143
 NYL LVA  2020    8.0 29.0        63.0            74.857143           88.500000
 CON NYL  2020    9.0  1.0        70.0            79.312500           74.066667
 NYL CON  2020    9.0  1.0        65.0            74.066667           79.312500
 ATL NYL  2020    9.0  3.0        62.0            81.352941           73.500000
 NYL ATL  2020    9.0  3.0        56.0            73.500000           81.352941
 NYL PHO  2020    9.0  5.0        67.0            72.470588           87.888889
 PHO NYL  2020    9.0  5.0        83.0            87.888889           72.470588
 LAS NYL  2020    9.0  8.0        96.0            85.789474           72.166667
 NYL LAS  2020    9.0  8.0        70.0            72.166667           85.789474
 IND NYL  2020    9.0 10.0        85.0            81.300000           72.052632
 NYL IND  2020    9.0 10.0        75.0            72.052632           81.300000
 NYL WAS  2020    9.0 12.0        58.0            72.200000           80.000000
 WAS NYL  2020    9.0 12.0        75.0            80.000000           72.200000
 DAL NYL  2020    9.0 13.0        82.0            83.476190           71.523810
 NYL DAL  2020    9.0 13.0        79.0            71.523810           83.476190

In [81]:
def correct_ytd_opp_median(row):
    opp_games = df[
        (df['team'] == row['opp']) &
        (
            (df['year'] < row['year']) |
            ((df['year'] == row['year']) & (df['month'] < row['month'])) |
            ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
        )
    ]
    return opp_games['team_score'].median() if not opp_games.empty else 0

# Apply clearly and safely
df['ytd_opp_score_median'] = df.apply(correct_ytd_opp_median, axis=1)

# Quick verification (same NYL example)
print(
    df.loc[
        (df['year'] == 2020) & ((df['team'] == 'NYL') | (df['opp'] == 'NYL')),
        ['team', 'opp', 'year', 'month', 'day', 'team_score', 'ytd_opp_score_median']
    ].sort_values(['month', 'day']).to_string(index=False)
)

team opp  year  month  day  team_score  ytd_opp_score_median
 NYL SEA  2020    7.0 25.0        71.0                   0.0
 SEA NYL  2020    7.0 25.0        87.0                   0.0
 DAL NYL  2020    7.0 29.0        93.0                  71.0
 NYL DAL  2020    7.0 29.0        80.0                  95.0
 ATL NYL  2020    7.0 31.0        84.0                  75.5
 NYL ATL  2020    7.0 31.0        78.0                  87.5
 NYL PHO  2020    8.0  2.0        67.0                 100.0
 PHO NYL  2020    8.0  2.0        96.0                  78.0
 MIN NYL  2020    8.0  5.0        92.0                  74.5
 NYL MIN  2020    8.0  5.0        66.0                  77.5
 NYL WAS  2020    8.0  7.0        74.0                  89.0
 WAS NYL  2020    8.0  7.0        66.0                  71.0
 LVA NYL  2020    8.0  9.0        78.0                  72.5
 NYL LVA  2020    8.0  9.0        76.0                  86.0
 LAS NYL  2020    8.0 11.0        93.0                  74.0
 NYL LAS  2020    8.0 11.0        78.0                  82.0
 IND NYL  2020    8.0 13.0        86.0                  75.0
 NYL IND  2020    8.0 13.0        79.0                  79.5
 MIN NYL  2020    8.0 15.0        94.0                  76.0
 NYL MIN  2020    8.0 15.0        64.0                  78.0
 NYL SEA  2020    8.0 18.0        64.0                  87.0
 SEA NYL  2020    8.0 18.0       105.0                  75.0
 CHI NYL  2020    8.0 20.0       101.0                  74.0
 NYL CHI  2020    8.0 20.0        85.0                  87.0
 CON NYL  2020    8.0 22.0        82.0                  75.0
 NYL CON  2020    8.0 22.0        65.0                  77.0
 CHI NYL  2020    8.0 25.0        99.0                  74.0
 NYL CHI  2020    8.0 25.0       101.0                  87.5
 LVA NYL  2020    8.0 29.0        80.0                  75.0
 NYL LVA  2020    8.0 29.0        63.0                  86.5
 CON NYL  2020    9.0  1.0        70.0                  74.0
 NYL CON  2020    9.0  1.0        65.0                  76.5
 ATL NYL  2020    9.0  3.0        62.0                  72.5
 NYL ATL  2020    9.0  3.0        56.0                  79.0
 NYL PHO  2020    9.0  5.0        67.0                  90.0
 PHO NYL  2020    9.0  5.0        83.0                  71.0
 LAS NYL  2020    9.0  8.0        96.0                  69.0
 NYL LAS  2020    9.0  8.0        70.0                  84.0
 IND NYL  2020    9.0 10.0        85.0                  70.0
 NYL IND  2020    9.0 10.0        75.0                  78.5
 NYL WAS  2020    9.0 12.0        58.0                  82.0
 WAS NYL  2020    9.0 12.0        75.0                  70.5
 DAL NYL  2020    9.0 13.0        82.0                  70.0
 NYL DAL  2020    9.0 13.0        79.0                  83.0

In [82]:
def correct_ytd_opp_min(row):
    opp_games = df[
        (df['team'] == row['opp']) &
        (
            (df['year'] < row['year']) |
            ((df['year'] == row['year']) & (df['month'] < row['month'])) |
            ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
        )
    ]
    return opp_games['team_score'].min() if not opp_games.empty else 0

# Apply clearly
df['ytd_opp_score_min'] = df.apply(correct_ytd_opp_min, axis=1)

# Quick verification clearly
print(
    df.loc[
        (df['year'] == 2020) & ((df['team'] == 'NYL') | (df['opp'] == 'NYL')),
        ['team', 'opp', 'year', 'month', 'day', 'team_score', 'ytd_opp_score_min']
    ].sort_values(['month', 'day']).to_string(index=False)
)

team opp  year  month  day  team_score  ytd_opp_score_min
 NYL SEA  2020    7.0 25.0        71.0                0.0
 SEA NYL  2020    7.0 25.0        87.0                0.0
 DAL NYL  2020    7.0 29.0        93.0               71.0
 NYL DAL  2020    7.0 29.0        80.0               95.0
 ATL NYL  2020    7.0 31.0        84.0               71.0
 NYL ATL  2020    7.0 31.0        78.0               70.0
 NYL PHO  2020    8.0  2.0        67.0               76.0
 PHO NYL  2020    8.0  2.0        96.0               71.0
 MIN NYL  2020    8.0  5.0        92.0               67.0
 NYL MIN  2020    8.0  5.0        66.0               66.0
 NYL WAS  2020    8.0  7.0        74.0               77.0
 WAS NYL  2020    8.0  7.0        66.0               66.0
 LVA NYL  2020    8.0  9.0        78.0               66.0
 NYL LVA  2020    8.0  9.0        76.0               79.0
 LAS NYL  2020    8.0 11.0        93.0               66.0
 NYL LAS  2020    8.0 11.0        78.0               75.0
 IND NYL  2020    8.0 13.0        86.0               66.0
 NYL IND  2020    8.0 13.0        79.0               73.0
 MIN NYL  2020    8.0 15.0        94.0               66.0
 NYL MIN  2020    8.0 15.0        64.0               66.0
 NYL SEA  2020    8.0 18.0        64.0               71.0
 SEA NYL  2020    8.0 18.0       105.0               64.0
 CHI NYL  2020    8.0 20.0       101.0               64.0
 NYL CHI  2020    8.0 20.0        85.0               71.0
 CON NYL  2020    8.0 22.0        82.0               64.0
 NYL CON  2020    8.0 22.0        65.0               69.0
 CHI NYL  2020    8.0 25.0        99.0               64.0
 NYL CHI  2020    8.0 25.0       101.0               71.0
 LVA NYL  2020    8.0 29.0        80.0               64.0
 NYL LVA  2020    8.0 29.0        63.0               78.0
 CON NYL  2020    9.0  1.0        70.0               63.0
 NYL CON  2020    9.0  1.0        65.0               69.0
 ATL NYL  2020    9.0  3.0        62.0               63.0
 NYL ATL  2020    9.0  3.0        56.0               63.0
 NYL PHO  2020    9.0  5.0        67.0               68.0
 PHO NYL  2020    9.0  5.0        83.0               56.0
 LAS NYL  2020    9.0  8.0        96.0               56.0
 NYL LAS  2020    9.0  8.0        70.0               75.0
 IND NYL  2020    9.0 10.0        85.0               56.0
 NYL IND  2020    9.0 10.0        75.0               62.0
 NYL WAS  2020    9.0 12.0        58.0               48.0
 WAS NYL  2020    9.0 12.0        75.0               56.0
 DAL NYL  2020    9.0 13.0        82.0               56.0
 NYL DAL  2020    9.0 13.0        79.0               65.0

In [83]:
def correct_ytd_opp_max(row):
    opp_games = df[
        (df['team'] == row['opp']) &
        (
            (df['year'] < row['year']) |
            ((df['year'] == row['year']) & (df['month'] < row['month'])) |
            ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
        )
    ]
    return opp_games['team_score'].max() if not opp_games.empty else 0

# Apply clearly
df['ytd_opp_score_max'] = df.apply(correct_ytd_opp_max, axis=1)

# Quick verification clearly
print(
    df.loc[
        (df['year'] == 2020) & ((df['team'] == 'NYL') | (df['opp'] == 'NYL')),
        ['team', 'opp', 'year', 'month', 'day', 'team_score', 'ytd_opp_score_max']
    ].sort_values(['month', 'day']).to_string(index=False)
)

team opp  year  month  day  team_score  ytd_opp_score_max
 NYL SEA  2020    7.0 25.0        71.0                0.0
 SEA NYL  2020    7.0 25.0        87.0                0.0
 DAL NYL  2020    7.0 29.0        93.0               71.0
 NYL DAL  2020    7.0 29.0        80.0               95.0
 ATL NYL  2020    7.0 31.0        84.0               80.0
 NYL ATL  2020    7.0 31.0        78.0              105.0
 NYL PHO  2020    8.0  2.0        67.0              102.0
 PHO NYL  2020    8.0  2.0        96.0               80.0
 MIN NYL  2020    8.0  5.0        92.0               80.0
 NYL MIN  2020    8.0  5.0        66.0               83.0
 NYL WAS  2020    8.0  7.0        74.0              101.0
 WAS NYL  2020    8.0  7.0        66.0               80.0
 LVA NYL  2020    8.0  9.0        78.0               80.0
 NYL LVA  2020    8.0  9.0        76.0              100.0
 LAS NYL  2020    8.0 11.0        93.0               80.0
 NYL LAS  2020    8.0 11.0        78.0               99.0
 IND NYL  2020    8.0 13.0        86.0               80.0
 NYL IND  2020    8.0 13.0        79.0              106.0
 MIN NYL  2020    8.0 15.0        94.0               80.0
 NYL MIN  2020    8.0 15.0        64.0               92.0
 NYL SEA  2020    8.0 18.0        64.0              100.0
 SEA NYL  2020    8.0 18.0       105.0               80.0
 CHI NYL  2020    8.0 20.0       101.0               80.0
 NYL CHI  2020    8.0 20.0        85.0              100.0
 CON NYL  2020    8.0 22.0        82.0               85.0
 NYL CON  2020    8.0 22.0        65.0               93.0
 CHI NYL  2020    8.0 25.0        99.0               85.0
 NYL CHI  2020    8.0 25.0       101.0              101.0
 LVA NYL  2020    8.0 29.0        80.0              101.0
 NYL LVA  2020    8.0 29.0        63.0              100.0
 CON NYL  2020    9.0  1.0        70.0              101.0
 NYL CON  2020    9.0  1.0        65.0               93.0
 ATL NYL  2020    9.0  3.0        62.0              101.0
 NYL ATL  2020    9.0  3.0        56.0              105.0
 NYL PHO  2020    9.0  5.0        67.0              105.0
 PHO NYL  2020    9.0  5.0        83.0              101.0
 LAS NYL  2020    9.0  8.0        96.0              101.0
 NYL LAS  2020    9.0  8.0        70.0               99.0
 IND NYL  2020    9.0 10.0        85.0              101.0
 NYL IND  2020    9.0 10.0        75.0              106.0
 NYL WAS  2020    9.0 12.0        58.0              101.0
 WAS NYL  2020    9.0 12.0        75.0              101.0
 DAL NYL  2020    9.0 13.0        82.0              101.0
 NYL DAL  2020    9.0 13.0        79.0              101.0

In [84]:
# Compute YTD mean opp_score (excluding current game)
df['ytd_team_allowed_mean'] = (
    df.groupby(['team', 'year'])['opp_score']
      .transform(lambda x: x.shift().expanding().mean())
      .fillna(0)
)

# Quick verification
print(df[['team', 'year', 'opp_score', 'ytd_team_allowed_mean']].head(15))

   team  year  opp_score  ytd_team_allowed_mean
0   ATL  2020       95.0               0.000000
1   ATL  2020      100.0              95.000000
2   ATL  2020       78.0              97.500000
3   ATL  2020       93.0              91.000000
4   ATL  2020       81.0              91.500000
5   ATL  2020       93.0              89.400000
6   ATL  2020       85.0              90.000000
7   ATL  2020       93.0              89.285714
8   ATL  2020      100.0              89.750000
9   ATL  2020       96.0              90.888889
10  ATL  2020       92.0              91.400000
11  ATL  2020       98.0              91.454545
12  ATL  2020       93.0              92.000000
13  ATL  2020       75.0              92.076923
14  ATL  2020       88.0              90.857143

In [85]:
# Compute YTD median opp_score (excluding current game)
df['ytd_team_allowed_median'] = (
    df.groupby(['team', 'year'])['opp_score']
      .transform(lambda x: x.shift().expanding().median())
      .fillna(0)
)

# Quick verification
print(df[['team', 'year', 'opp_score', 'ytd_team_allowed_median']].head(15))

   team  year  opp_score  ytd_team_allowed_median
0   ATL  2020       95.0                      0.0
1   ATL  2020      100.0                     95.0
2   ATL  2020       78.0                     97.5
3   ATL  2020       93.0                     95.0
4   ATL  2020       81.0                     94.0
5   ATL  2020       93.0                     93.0
6   ATL  2020       85.0                     93.0
7   ATL  2020       93.0                     93.0
8   ATL  2020      100.0                     93.0
9   ATL  2020       96.0                     93.0
10  ATL  2020       92.0                     93.0
11  ATL  2020       98.0                     93.0
12  ATL  2020       93.0                     93.0
13  ATL  2020       75.0                     93.0
14  ATL  2020       88.0                     93.0

In [86]:
# Compute YTD min opp_score (excluding current game)
df['ytd_team_allowed_min'] = (
    df.groupby(['team', 'year'])['opp_score']
      .transform(lambda x: x.shift().expanding().min())
      .fillna(0)
)

# Quick verification
print(df[['team', 'year', 'opp_score', 'ytd_team_allowed_min']].head(15))

   team  year  opp_score  ytd_team_allowed_min
0   ATL  2020       95.0                   0.0
1   ATL  2020      100.0                  95.0
2   ATL  2020       78.0                  95.0
3   ATL  2020       93.0                  78.0
4   ATL  2020       81.0                  78.0
5   ATL  2020       93.0                  78.0
6   ATL  2020       85.0                  78.0
7   ATL  2020       93.0                  78.0
8   ATL  2020      100.0                  78.0
9   ATL  2020       96.0                  78.0
10  ATL  2020       92.0                  78.0
11  ATL  2020       98.0                  78.0
12  ATL  2020       93.0                  78.0
13  ATL  2020       75.0                  78.0
14  ATL  2020       88.0                  75.0

In [87]:
# Compute YTD max opp_score (excluding current game)
df['ytd_team_allowed_max'] = (
    df.groupby(['team', 'year'])['opp_score']
      .transform(lambda x: x.shift().expanding().max())
      .fillna(0)
)

# Quick verification
print(df[['team', 'year', 'opp_score', 'ytd_team_allowed_max']].head(15))

   team  year  opp_score  ytd_team_allowed_max
0   ATL  2020       95.0                   0.0
1   ATL  2020      100.0                  95.0
2   ATL  2020       78.0                 100.0
3   ATL  2020       93.0                 100.0
4   ATL  2020       81.0                 100.0
5   ATL  2020       93.0                 100.0
6   ATL  2020       85.0                 100.0
7   ATL  2020       93.0                 100.0
8   ATL  2020      100.0                 100.0
9   ATL  2020       96.0                 100.0
10  ATL  2020       92.0                 100.0
11  ATL  2020       98.0                 100.0
12  ATL  2020       93.0                 100.0
13  ATL  2020       75.0                 100.0
14  ATL  2020       88.0                 100.0

In [89]:
# Define the function clearly
def correct_ytd_opp_allowed_mean(row):
    opp_allowed = df[
        (df['team'] == row['opp']) &
        (
            (df['year'] < row['year']) |
            ((df['year'] == row['year']) & (df['month'] < row['month'])) |
            ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
        )
    ]['opp_score']
    return opp_allowed.mean() if not opp_allowed.empty else 0

# Apply safely to df
df['ytd_opp_allowed_mean'] = df.apply(correct_ytd_opp_allowed_mean, axis=1)

# Quick verification
print(df[['team', 'opp', 'year', 'month', 'day', 'ytd_opp_allowed_mean']].head(15))

   team  opp  year  month   day  ytd_opp_allowed_mean
0   ATL  DAL  2020    7.0  26.0              0.000000
1   ATL  LVA  2020    7.0  29.0             88.000000
2   ATL  NYL  2020    7.0  31.0             90.000000
3   ATL  IND  2020    8.0   2.0             92.333333
4   ATL  PHO  2020    8.0   4.0             91.750000
5   ATL  SEA  2020    8.0   6.0             75.000000
6   ATL  DAL  2020    8.0   8.0             85.000000
7   ATL  CON  2020    8.0  10.0             83.571429
8   ATL  SEA  2020    8.0  12.0             75.750000
9   ATL  PHO  2020    8.0  14.0             85.444444
10  ATL  CHI  2020    8.0  16.0             83.800000
11  ATL  WAS  2020    8.0  19.0             80.900000
12  ATL  LAS  2020    8.0  21.0             78.454545
13  ATL  MIN  2020    8.0  23.0             76.250000
14  ATL  MIN  2020    8.0  28.0             76.384615

In [90]:
def correct_ytd_opp_allowed_median(row):
    opp_allowed = df[
        (df['team'] == row['opp']) &
        (
            (df['year'] < row['year']) |
            ((df['year'] == row['year']) & (df['month'] < row['month'])) |
            ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
        )
    ]['opp_score']
    return opp_allowed.median() if not opp_allowed.empty else 0

# Apply clearly
df['ytd_opp_allowed_median'] = df.apply(correct_ytd_opp_allowed_median, axis=1)

# Quick verification
print(df[['team', 'opp', 'year', 'month', 'day', 'ytd_opp_allowed_median']].head(15))

   team  opp  year  month   day  ytd_opp_allowed_median
0   ATL  DAL  2020    7.0  26.0                     0.0
1   ATL  LVA  2020    7.0  29.0                    88.0
2   ATL  NYL  2020    7.0  31.0                    90.0
3   ATL  IND  2020    8.0   2.0                   100.0
4   ATL  PHO  2020    8.0   4.0                    97.0
5   ATL  SEA  2020    8.0   6.0                    74.0
6   ATL  DAL  2020    8.0   8.0                    81.0
7   ATL  CON  2020    8.0  10.0                    81.0
8   ATL  SEA  2020    8.0  12.0                    72.5
9   ATL  PHO  2020    8.0  14.0                    86.0
10  ATL  CHI  2020    8.0  16.0                    84.5
11  ATL  WAS  2020    8.0  19.0                    82.0
12  ATL  LAS  2020    8.0  21.0                    76.0
13  ATL  MIN  2020    8.0  23.0                    80.0
14  ATL  MIN  2020    8.0  28.0                    80.0

In [91]:
def correct_ytd_opp_allowed_min(row):
    opp_allowed = df[
        (df['team'] == row['opp']) &
        (
            (df['year'] < row['year']) |
            ((df['year'] == row['year']) & (df['month'] < row['month'])) |
            ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
        )
    ]['opp_score']
    return opp_allowed.min() if not opp_allowed.empty else 0

# Apply clearly
df['ytd_opp_allowed_min'] = df.apply(correct_ytd_opp_allowed_min, axis=1)

# Quick verification
print(df[['team', 'opp', 'year', 'month', 'day', 'ytd_opp_allowed_min']].head(15))

   team  opp  year  month   day  ytd_opp_allowed_min
0   ATL  DAL  2020    7.0  26.0                  0.0
1   ATL  LVA  2020    7.0  29.0                 88.0
2   ATL  NYL  2020    7.0  31.0                 87.0
3   ATL  IND  2020    8.0   2.0                 76.0
4   ATL  PHO  2020    8.0   4.0                 67.0
5   ATL  SEA  2020    8.0   6.0                 66.0
6   ATL  DAL  2020    8.0   8.0                 73.0
7   ATL  CON  2020    8.0  10.0                 68.0
8   ATL  SEA  2020    8.0  12.0                 66.0
9   ATL  PHO  2020    8.0  14.0                 67.0
10  ATL  CHI  2020    8.0  16.0                 71.0
11  ATL  WAS  2020    8.0  19.0                 68.0
12  ATL  LAS  2020    8.0  21.0                 64.0
13  ATL  MIN  2020    8.0  23.0                 48.0
14  ATL  MIN  2020    8.0  28.0                 48.0

In [92]:
def correct_ytd_opp_allowed_max(row):
    opp_allowed = df[
        (df['team'] == row['opp']) &
        (
            (df['year'] < row['year']) |
            ((df['year'] == row['year']) & (df['month'] < row['month'])) |
            ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
        )
    ]['opp_score']
    return opp_allowed.max() if not opp_allowed.empty else 0

# Apply clearly
df['ytd_opp_allowed_max'] = df.apply(correct_ytd_opp_allowed_max, axis=1)

# Quick verification
print(df[['team', 'opp', 'year', 'month', 'day', 'ytd_opp_allowed_max']].head(15))

   team  opp  year  month   day  ytd_opp_allowed_max
0   ATL  DAL  2020    7.0  26.0                  0.0
1   ATL  LVA  2020    7.0  29.0                 88.0
2   ATL  NYL  2020    7.0  31.0                 93.0
3   ATL  IND  2020    8.0   2.0                101.0
4   ATL  PHO  2020    8.0   4.0                106.0
5   ATL  SEA  2020    8.0   6.0                 89.0
6   ATL  DAL  2020    8.0   8.0                105.0
7   ATL  CON  2020    8.0  10.0                100.0
8   ATL  SEA  2020    8.0  12.0                 92.0
9   ATL  PHO  2020    8.0  14.0                106.0
10  ATL  CHI  2020    8.0  16.0                 96.0
11  ATL  WAS  2020    8.0  19.0                 91.0
12  ATL  LAS  2020    8.0  21.0                 96.0
13  ATL  MIN  2020    8.0  23.0                 97.0
14  ATL  MIN  2020    8.0  28.0                 97.0

In [93]:
for col in df.columns:
  print(col)

team
year
home_away
opp
win_loss
team_score
opp_score
team_fg
team_fga
team_fg_pct
team_3p
team_3pa
team_3p_pct
team_ft
team_fta
team_ft_pct
team_orb
team_trb
team_ast
team_stl
team_blk
team_tov
team_pf
opponent_fg
opponent_fga
opponent_fg_pct
opponent_3p
opponent_3pa
opponent_3p_pct
opponent_ft
opponent_fta
opponent_ft_pct
opponent_orb
opponent_trb
opponent_ast
opponent_stl
opponent_blk
opponent_tov
opponent_pf
day
month
advanced_ortg
advanced_drtg
advanced_pace
advanced_ftr
advanced_3par
advanced_ts_pct
advanced_trb_pct
advanced_ast_pct
advanced_stl_pct
advanced_blk_pct
offensive_four_factors_efg_pct
offensive_four_factors_tov_pct
offensive_four_factors_orb_pct
defensive_four_factors_efg_pct
defensive_four_factors_tov_pct
defensive_four_factors_drb_pct
all_around_star
and_one_machine
catch_and_shoot
corner_3_specialist
defensive_anchor
defensive_rebounder
efficient_scorer
elite_scorer
fast_break_threat
floor_general
free_throw_generator
glass_cleaner
heave_chucker
impact_bench
midrange_sniper
offensive_hub
offensive_rebounder
playmaker
plus_minus_driver
rim_protector
self_creator
slasher
steal_artist
stretch_big
three_point_specialist
turnover_prone
volume_shooter
game_num
ytd_team_score_mean
ytd_team_score_median
ytd_team_score_min
ytd_team_score_max
ytd_opp_score_mean
ytd_opp_score_median
ytd_opp_score_min
ytd_opp_score_max
ytd_team_allowed_mean
ytd_team_allowed_median
ytd_team_allowed_min
ytd_team_allowed_max
ytd_opp_allowed_mean
ytd_opp_allowed_median
ytd_opp_allowed_min
ytd_opp_allowed_max

In [117]:
# Counting stats clearly defined (excluding pct and advanced columns)
features = [
    'team_fg', 'team_fga', 'team_3p', 'team_3pa', 'team_ft', 'team_fta',
    'team_orb', 'team_trb', 'team_ast', 'team_stl', 'team_blk', 'team_tov', 'team_pf',
    'opponent_fg', 'opponent_fga', 'opponent_3p', 'opponent_3pa',
    'opponent_ft', 'opponent_fta', 'opponent_orb', 'opponent_trb',
    'opponent_ast', 'opponent_stl', 'opponent_blk', 'opponent_tov', 'opponent_pf'
]

# Create ytd columns per game
for col in features:
    df[f'ytd_team_{col}_per_game'] = (
        df.groupby(['team', 'year'])[col]
          .transform(lambda x: x.shift().expanding().mean())
          .fillna(0)
    )

# Quick verification of a few columns
print(df[['team', 'year', 'team_fg', 'ytd_team_team_fg_per_game',
          'team_ast', 'ytd_team_team_ast_per_game']].head(15))

   team  year  team_fg  ytd_team_team_fg_per_game  team_ast  \
0   ATL  2020       34                   0.000000        19
1   ATL  2020       28                  34.000000        12
2   ATL  2020       28                  31.000000        11
3   ATL  2020       33                  30.000000        18
4   ATL  2020       29                  30.750000        15
5   ATL  2020       31                  30.400000        12
6   ATL  2020       29                  30.500000        13
7   ATL  2020       30                  30.285714        21
8   ATL  2020       27                  30.250000        18
9   ATL  2020       32                  29.888889        22
10  ATL  2020       27                  30.100000        11
11  ATL  2020       38                  29.818182        26
12  ATL  2020       33                  30.500000        27
13  ATL  2020       32                  30.692308        23
14  ATL  2020       31                  30.785714        18

    ytd_team_team_ast_per_game
0                     0.000000
1                    19.000000
2                    15.500000
3                    14.000000
4                    15.000000
5                    15.000000
6                    14.500000
7                    14.285714
8                    15.125000
9                    15.444444
10                   16.100000
11                   15.636364
12                   16.500000
13                   17.307692
14                   17.714286

In [119]:
# Fix redundant 'team_' in column names
df.columns = [col.replace('ytd_team_team_', 'ytd_team_').replace('ytd_team_opponent_', 'ytd_opponent_') for col in df.columns]

In [125]:
# All team-based percentage columns calculated from cumulative YTD totals
df['ytd_team_fg_pct'] = (df['ytd_team_fg_per_game'] / df['ytd_team_fga_per_game']).fillna(0)
df['ytd_team_3p_pct'] = (df['ytd_team_3p_per_game'] / df['ytd_team_3pa_per_game']).fillna(0)
df['ytd_team_ft_pct'] = (df['ytd_team_ft_per_game'] / df['ytd_team_fta_per_game']).fillna(0)

# Advanced calculations
df['ytd_advanced_trb_pct'] = (
    df['ytd_team_trb_per_game'] /
    (df['ytd_team_trb_per_game'] + df['ytd_opponent_trb_per_game'])
).fillna(0)

df['ytd_advanced_ast_pct'] = (
    df['ytd_team_ast_per_game'] / df['ytd_team_fg_per_game']
).fillna(0)

df['ytd_advanced_blk_pct'] = (
    df['ytd_team_blk_per_game'] / (df['ytd_opponent_fga_per_game'] - df['ytd_opponent_3pa_per_game'])
).fillna(0)

df['ytd_advanced_ftr'] = (
    df['ytd_team_fta_per_game'] / df['ytd_team_fga_per_game']
).fillna(0)

df['ytd_advanced_3par'] = (
    df['ytd_team_3pa_per_game'] / df['ytd_team_fga_per_game']
).fillna(0)

# TS% calculation
df['ytd_team_pts_per_game'] = (
    (df['ytd_team_fg_per_game'] - df['ytd_team_3p_per_game']) * 2 +
    df['ytd_team_3p_per_game'] * 3 +
    df['ytd_team_ft_per_game']
)

df['ytd_advanced_ts_pct'] = (
    df['ytd_team_pts_per_game'] / (2 * (df['ytd_team_fga_per_game'] + 0.44 * df['ytd_team_fta_per_game']))
).fillna(0)

# Quick verification of some columns
print(df[['team', 'year', 'ytd_team_fg_pct', 'ytd_team_3p_pct', 'ytd_team_ft_pct',
          'ytd_advanced_trb_pct', 'ytd_advanced_ast_pct', 'ytd_advanced_ts_pct']].head(15))

   team  year  ytd_team_fg_pct  ytd_team_3p_pct  ytd_team_ft_pct  \
0   ATL  2020         0.000000         0.000000         0.000000
1   ATL  2020         0.548387         0.411765         0.882353
2   ATL  2020         0.469697         0.266667         0.812500
3   ATL  2020         0.434783         0.272727         0.810127
4   ATL  2020         0.445652         0.287879         0.816092
5   ATL  2020         0.449704         0.291139         0.830000
6   ATL  2020         0.450739         0.311321         0.858333
7   ATL  2020         0.444444         0.328000         0.842105
8   ATL  2020         0.446494         0.363636         0.825503
9   ATL  2020         0.436688         0.348837         0.826667
10  ATL  2020         0.434971         0.354167         0.795181
11  ATL  2020         0.431579         0.339806         0.777174
12  ATL  2020         0.441496         0.348214         0.765306
13  ATL  2020         0.444321         0.353909         0.752336
14  ATL  2020         0.446632         0.356589         0.747788

    ytd_advanced_trb_pct  ytd_advanced_ast_pct  ytd_advanced_ts_pct
0               0.000000              0.000000             0.000000
1               0.539683              0.558824             0.682173
2               0.437037              0.500000             0.571447
3               0.483412              0.466667             0.535655
4               0.475836              0.487805             0.534555
5               0.483680              0.493421             0.536649
6               0.491400              0.475410             0.547079
7               0.484277              0.471698             0.538729
8               0.481618              0.500000             0.542333
9               0.480263              0.516729             0.529326
10              0.485884              0.534884             0.524156
11              0.479620              0.524390             0.516671
12              0.485607              0.540984             0.524453
13              0.485616              0.563910             0.526629
14              0.487124              0.575406             0.527507

<ipython-input-125-e26c3be54e0d>:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_advanced_ftr'] = (
<ipython-input-125-e26c3be54e0d>:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_advanced_3par'] = (
<ipython-input-125-e26c3be54e0d>:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_pts_per_game'] = (
<ipython-input-125-e26c3be54e0d>:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_advanced_ts_pct'] = (

In [126]:
for col in df.columns:
  print(col)

team
year
home_away
opp
win_loss
team_score
opp_score
team_fg
team_fga
team_fg_pct
team_3p
team_3pa
team_3p_pct
team_ft
team_fta
team_ft_pct
team_orb
team_trb
team_ast
team_stl
team_blk
team_tov
team_pf
opponent_fg
opponent_fga
opponent_fg_pct
opponent_3p
opponent_3pa
opponent_3p_pct
opponent_ft
opponent_fta
opponent_ft_pct
opponent_orb
opponent_trb
opponent_ast
opponent_stl
opponent_blk
opponent_tov
opponent_pf
day
month
advanced_ortg
advanced_drtg
advanced_pace
advanced_ftr
advanced_3par
advanced_ts_pct
advanced_trb_pct
advanced_ast_pct
advanced_stl_pct
advanced_blk_pct
offensive_four_factors_efg_pct
offensive_four_factors_tov_pct
offensive_four_factors_orb_pct
defensive_four_factors_efg_pct
defensive_four_factors_tov_pct
defensive_four_factors_drb_pct
all_around_star
and_one_machine
catch_and_shoot
corner_3_specialist
defensive_anchor
defensive_rebounder
efficient_scorer
elite_scorer
fast_break_threat
floor_general
free_throw_generator
glass_cleaner
heave_chucker
impact_bench
midrange_sniper
offensive_hub
offensive_rebounder
playmaker
plus_minus_driver
rim_protector
self_creator
slasher
steal_artist
stretch_big
three_point_specialist
turnover_prone
volume_shooter
game_num
ytd_team_score_mean
ytd_team_score_median
ytd_team_score_min
ytd_team_score_max
ytd_opp_score_mean
ytd_opp_score_median
ytd_opp_score_min
ytd_opp_score_max
ytd_team_allowed_mean
ytd_team_allowed_median
ytd_team_allowed_min
ytd_team_allowed_max
ytd_opp_allowed_mean
ytd_opp_allowed_median
ytd_opp_allowed_min
ytd_opp_allowed_max
ytd_team_fg_per_game
ytd_team_fga_per_game
ytd_team_3p_per_game
ytd_team_3pa_per_game
ytd_team_ft_per_game
ytd_team_fta_per_game
ytd_team_orb_per_game
ytd_team_trb_per_game
ytd_team_ast_per_game
ytd_team_stl_per_game
ytd_team_blk_per_game
ytd_team_tov_per_game
ytd_team_pf_per_game
ytd_opponent_fg_per_game
ytd_opponent_fga_per_game
ytd_opponent_3p_per_game
ytd_opponent_3pa_per_game
ytd_opponent_ft_per_game
ytd_opponent_fta_per_game
ytd_opponent_orb_per_game
ytd_opponent_trb_per_game
ytd_opponent_ast_per_game
ytd_opponent_stl_per_game
ytd_opponent_blk_per_game
ytd_opponent_tov_per_game
ytd_opponent_pf_per_game
ytd_team_fg_pct
ytd_team_3p_pct
ytd_team_ft_pct
ytd_advanced_trb_pct
ytd_advanced_ast_pct
ytd_advanced_blk_pct
ytd_advanced_ftr
ytd_advanced_3par
ytd_team_pts_per_game
ytd_advanced_ts_pct

In [129]:
# Offensive Four Factors
df['ytd_offensive_efg_pct'] = (
    (df['ytd_team_fg_per_game'] + 0.5 * df['ytd_team_3p_per_game']) / df['ytd_team_fga_per_game']
).fillna(0)

df['ytd_offensive_tov_pct'] = (
    df['ytd_team_tov_per_game'] /
    (df['ytd_team_fga_per_game'] + 0.44 * df['ytd_team_fta_per_game'] + df['ytd_team_tov_per_game'])
).fillna(0)

df['ytd_offensive_orb_pct'] = (
    df['ytd_team_orb_per_game'] /
    (df['ytd_team_orb_per_game'] + df['ytd_opponent_trb_per_game'] - df['ytd_opponent_orb_per_game'])
).fillna(0)

# Defensive Four Factors
df['ytd_defensive_efg_pct'] = (
    (df['ytd_opponent_fg_per_game'] + 0.5 * df['ytd_opponent_3p_per_game']) / df['ytd_opponent_fga_per_game']
).fillna(0)

df['ytd_defensive_tov_pct'] = (
    df['ytd_opponent_tov_per_game'] /
    (df['ytd_opponent_fga_per_game'] + 0.44 * df['ytd_opponent_fta_per_game'] + df['ytd_opponent_tov_per_game'])
).fillna(0)

df['ytd_defensive_drb_pct'] = (
    (df['ytd_team_trb_per_game'] - df['ytd_team_orb_per_game']) /
    (df['ytd_team_trb_per_game'] - df['ytd_team_orb_per_game'] + df['ytd_opponent_orb_per_game'])
).fillna(0)

# Quick verification
print(df[['team', 'year', 'ytd_offensive_efg_pct', 'ytd_offensive_tov_pct', 'ytd_offensive_orb_pct',
          'ytd_defensive_efg_pct', 'ytd_defensive_tov_pct', 'ytd_defensive_drb_pct']].head(15))

   team  year  ytd_offensive_efg_pct  ytd_offensive_tov_pct  \
0   ATL  2020               0.000000               0.000000
1   ATL  2020               0.604839               0.172117
2   ATL  2020               0.515152               0.172861
3   ATL  2020               0.471014               0.162765
4   ATL  2020               0.480072               0.158058
5   ATL  2020               0.483728               0.176724
6   ATL  2020               0.491379               0.177483
7   ATL  2020               0.487421               0.171688
8   ATL  2020               0.494465               0.176257
9   ATL  2020               0.485390               0.174334
10  ATL  2020               0.484104               0.169374
11  ATL  2020               0.477632               0.169799
12  ATL  2020               0.488540               0.168901
13  ATL  2020               0.492205               0.178104
14  ATL  2020               0.494301               0.177047

    ytd_offensive_orb_pct  ytd_defensive_efg_pct  ytd_defensive_tov_pct  \
0                0.000000               0.000000               0.000000
1                0.160000               0.519231               0.130261
2                0.169231               0.546980               0.159014
3                0.261682               0.511312               0.158934
4                0.244444               0.526132               0.160638
5                0.233129               0.502762               0.149800
6                0.230769               0.496552               0.143967
7                0.238298               0.501992               0.144770
8                0.233716               0.505181               0.137399
9                0.234323               0.524961               0.138650
10               0.243402               0.530453               0.136695
11               0.238845               0.538961               0.141859
12               0.251816               0.542857               0.140275
13               0.247216               0.540243               0.145950
14               0.248954               0.534289               0.146040

    ytd_defensive_drb_pct
0                0.000000
1                0.789474
2                0.685714
3                0.711538
4                0.708955
5                0.718391
6                0.731132
7                0.723140
8                0.710247
9                0.724590
10               0.734940
11               0.738028
12               0.735751
13               0.740476
14               0.737885

<ipython-input-129-6f5175938a62>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_offensive_efg_pct'] = (
<ipython-input-129-6f5175938a62>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_offensive_tov_pct'] = (
<ipython-input-129-6f5175938a62>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_offensive_orb_pct'] = (
<ipython-input-129-6f5175938a62>:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_defensive_efg_pct'] = (
<ipython-input-129-6f5175938a62>:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_defensive_tov_pct'] = (
<ipython-input-129-6f5175938a62>:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_defensive_drb_pct'] = (

In [131]:
# List of columns to rename
rename_dict = {
    'ytd_advanced_trb_pct': 'ytd_team_advanced_trb_pct',
    'ytd_advanced_ast_pct': 'ytd_team_advanced_ast_pct',
    'ytd_advanced_blk_pct': 'ytd_team_advanced_blk_pct',
    'ytd_advanced_ftr': 'ytd_team_advanced_ftr',
    'ytd_advanced_3par': 'ytd_team_advanced_3par',
    'ytd_team_pts_per_game': 'ytd_team_pts_per_game',  # this one is already good
    'ytd_advanced_ts_pct': 'ytd_team_advanced_ts_pct',
    'ytd_offensive_efg_pct': 'ytd_team_offensive_efg_pct',
    'ytd_offensive_tov_pct': 'ytd_team_offensive_tov_pct',
    'ytd_offensive_orb_pct': 'ytd_team_offensive_orb_pct',
    'ytd_defensive_efg_pct': 'ytd_team_defensive_efg_pct',
    'ytd_defensive_tov_pct': 'ytd_team_defensive_tov_pct',
    'ytd_defensive_drb_pct': 'ytd_team_defensive_drb_pct'
}

# Rename columns
df.rename(columns=rename_dict, inplace=True)

In [132]:
# Rename 'opponent' to 'opp' for all relevant columns
df.columns = [col.replace('opponent_', 'opp_') for col in df.columns]

# Verify the changes
print([col for col in df.columns if 'opp_' in col])

['opp_score', 'opp_fg', 'opp_fga', 'opp_fg_pct', 'opp_3p', 'opp_3pa', 'opp_3p_pct', 'opp_ft', 'opp_fta', 'opp_ft_pct', 'opp_orb', 'opp_trb', 'opp_ast', 'opp_stl', 'opp_blk', 'opp_tov', 'opp_pf', 'ytd_opp_score_mean', 'ytd_opp_score_median', 'ytd_opp_score_min', 'ytd_opp_score_max', 'ytd_opp_allowed_mean', 'ytd_opp_allowed_median', 'ytd_opp_allowed_min', 'ytd_opp_allowed_max', 'ytd_opp_fg_per_game', 'ytd_opp_fga_per_game', 'ytd_opp_3p_per_game', 'ytd_opp_3pa_per_game', 'ytd_opp_ft_per_game', 'ytd_opp_fta_per_game', 'ytd_opp_orb_per_game', 'ytd_opp_trb_per_game', 'ytd_opp_ast_per_game', 'ytd_opp_stl_per_game', 'ytd_opp_blk_per_game', 'ytd_opp_tov_per_game', 'ytd_opp_pf_per_game']

In [134]:
cols_to_create = [
    'ytd_team_fg_pct', 'ytd_team_3p_pct', 'ytd_team_ft_pct',
    'ytd_team_advanced_trb_pct', 'ytd_team_advanced_ast_pct', 'ytd_team_advanced_blk_pct',
    'ytd_team_advanced_ftr', 'ytd_team_advanced_3par', 'ytd_team_pts_per_game',
    'ytd_team_advanced_ts_pct', 'ytd_team_offensive_efg_pct',
    'ytd_team_offensive_tov_pct', 'ytd_team_offensive_orb_pct',
    'ytd_team_defensive_efg_pct', 'ytd_team_defensive_tov_pct',
    'ytd_team_defensive_drb_pct'
]

for col in cols_to_create:
    new_col = col.replace('ytd_team_', 'ytd_opp_')

    def get_ytd_opp(row):
        opp_data = df[
            (df['team'] == row['opp']) &
            (
                (df['year'] < row['year']) |
                ((df['year'] == row['year']) & (df['month'] < row['month'])) |
                ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
            )
        ]
        return opp_data[col].iloc[-1] if not opp_data.empty else 0

    df[new_col] = df.apply(get_ytd_opp, axis=1)

# Quick verification
print(df[['team', 'opp', 'year'] + [col.replace('ytd_team_', 'ytd_opp_') for col in cols_to_create]].head())

<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)

  team  opp  year  ytd_opp_fg_pct  ytd_opp_3p_pct  ytd_opp_ft_pct  \
0  ATL  DAL  2020        0.000000        0.000000        0.000000
1  ATL  LVA  2020        0.000000        0.000000        0.000000
2  ATL  NYL  2020        0.348485        0.214286        0.863636
3  ATL  IND  2020        0.453901        0.369565        0.880952
4  ATL  PHO  2020        0.505102        0.414286        0.698630

   ytd_opp_advanced_trb_pct  ytd_opp_advanced_ast_pct  \
0                  0.000000                  0.000000
1                  0.000000                  0.000000
2                  0.480519                  0.608696
3                  0.488889                  0.453125
4                  0.478947                  0.717172

   ytd_opp_advanced_blk_pct  ytd_opp_advanced_ftr  ytd_opp_advanced_3par  \
0                  0.000000              0.000000               0.000000
1                  0.000000              0.000000               0.000000
2                  0.092593              0.333333               0.424242
3                  0.040816              0.297872               0.326241
4                  0.090909              0.372449               0.357143

   ytd_opp_pts_per_game  ytd_opp_advanced_ts_pct  ytd_opp_offensive_efg_pct  \
0              0.000000                 0.000000                   0.000000
1              0.000000                 0.000000                   0.000000
2             71.000000                 0.469080                   0.393939
3             91.000000                 0.570604                   0.514184
4             92.666667                 0.609328                   0.579082

   ytd_opp_offensive_tov_pct  ytd_opp_offensive_orb_pct  \
0                   0.000000                   0.000000
1                   0.000000                   0.000000
2                   0.200676                   0.135135
3                   0.135516                   0.217391
4                   0.173837                   0.202020

   ytd_opp_defensive_efg_pct  ytd_opp_defensive_tov_pct  \
0                   0.000000                   0.000000
1                   0.000000                   0.000000
2                   0.487013                   0.134576
3                   0.583942                   0.115817
4                   0.569712                   0.133728

   ytd_opp_defensive_drb_pct
0                   0.000000
1                   0.000000
2                   0.800000
3                   0.772727
4                   0.780220

<ipython-input-134-8bf2c6464102>:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)

In [137]:
# YTD Advanced ORtg, DRtg, Pace (means of existing game values)
for col in ['advanced_ortg', 'advanced_drtg', 'advanced_pace']:
    df[f'ytd_team_{col}'] = (
        df.groupby(['team', 'year'])[col]
        .transform(lambda x: x.shift().expanding().mean())
        .fillna(0)
    )

# Quick verification
print(df[['team', 'year', 'advanced_ortg', 'ytd_team_advanced_ortg',
          'advanced_drtg', 'ytd_team_advanced_drtg',
          'advanced_pace', 'ytd_team_advanced_pace']].head(10))

  team  year  advanced_ortg  ytd_team_advanced_ortg  advanced_drtg  \
0  ATL  2020          119.4                0.000000          108.0
1  ATL  2020           83.0              119.400000          118.6
2  ATL  2020          102.0              101.200000           94.7
3  ATL  2020           98.4              101.466667          118.9
4  ATL  2020           89.5              100.700000           98.0
5  ATL  2020          108.4               98.460000          109.6
6  ATL  2020          100.7              100.116667          114.1
7  ATL  2020          102.4              100.200000          116.1
8  ATL  2020           82.4              100.475000          130.7
9  ATL  2020          100.9               98.466667          121.1

   ytd_team_advanced_drtg  advanced_pace  ytd_team_advanced_pace
0                0.000000           87.9                0.000000
1              108.000000           84.3               87.900000
2              113.300000           82.4               86.100000
3              107.100000           78.2               84.866667
4              110.050000           82.7               83.200000
5              107.640000           84.8               83.100000
6              107.966667           74.5               83.383333
7              108.842857           80.1               82.114286
8              109.750000           76.5               81.862500
9              112.077778           79.2               81.266667

<ipython-input-137-fab0841f5222>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_{col}'] = (
<ipython-input-137-fab0841f5222>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_{col}'] = (
<ipython-input-137-fab0841f5222>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_{col}'] = (

In [139]:
cols_to_create = ['ytd_team_advanced_ortg', 'ytd_team_advanced_drtg', 'ytd_team_advanced_pace']

for col in cols_to_create:
    new_col = col.replace('ytd_team_', 'ytd_opp_')

    def get_ytd_opp(row):
        opp_data = df[
            (df['team'] == row['opp']) &
            (
                (df['year'] < row['year']) |
                ((df['year'] == row['year']) & (df['month'] < row['month'])) |
                ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
            )
        ]
        return opp_data[col].iloc[-1] if not opp_data.empty else 0

    df[new_col] = df.apply(get_ytd_opp, axis=1)

# Quick verification
print(df[['team', 'opp', 'year', 'month', 'day'] + [col.replace('ytd_team_', 'ytd_opp_') for col in cols_to_create]].head(10))

<ipython-input-139-fe360876d4d2>:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-139-fe360876d4d2>:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)

  team  opp  year  month   day  ytd_opp_advanced_ortg  ytd_opp_advanced_drtg  \
0  ATL  DAL  2020    7.0  26.0               0.000000               0.000000
1  ATL  LVA  2020    7.0  29.0               0.000000               0.000000
2  ATL  NYL  2020    7.0  31.0              81.400000              99.800000
3  ATL  IND  2020    8.0   2.0             111.050000             122.550000
4  ATL  PHO  2020    8.0   4.0             110.833333             119.600000
5  ATL  SEA  2020    8.0   6.0             104.850000              95.900000
6  ATL  DAL  2020    8.0   8.0             102.740000             104.060000
7  ATL  CON  2020    8.0  10.0              96.333333              99.966667
8  ATL  SEA  2020    8.0  12.0             105.385714              96.528571
9  ATL  PHO  2020    8.0  14.0             106.887500             102.362500

   ytd_opp_advanced_pace
0               0.000000
1               0.000000
2              87.200000
3              82.000000
4              83.700000
5              78.875000
6              80.260000
7              80.983333
8              79.357143
9              83.012500

<ipython-input-139-fe360876d4d2>:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)

In [142]:
# List of allowed stats to create from opp columns
allowed_stats = [
    ('opp_fg', 'ytd_team_allowed_fg_per_game'),
    ('opp_fga', 'ytd_team_allowed_fga_per_game'),
    ('opp_3p', 'ytd_team_allowed_3p_per_game'),
    ('opp_3pa', 'ytd_team_allowed_3pa_per_game'),
    ('opp_ft', 'ytd_team_allowed_ft_per_game'),
    ('opp_fta', 'ytd_team_allowed_fta_per_game'),
    ('opp_orb', 'ytd_team_allowed_orb_per_game'),
    ('opp_trb', 'ytd_team_allowed_trb_per_game'),
    ('opp_ast', 'ytd_team_allowed_ast_per_game'),
    ('opp_stl', 'ytd_team_allowed_stl_per_game'),
    ('opp_blk', 'ytd_team_allowed_blk_per_game'),
    ('opp_tov', 'ytd_team_allowed_tov_per_game'),
    ('opp_pf', 'ytd_team_allowed_pf_per_game'),
    ('opp_fg_pct', 'ytd_team_allowed_fg_pct'),
    ('opp_3p_pct', 'ytd_team_allowed_3p_pct'),
    ('opp_ft_pct', 'ytd_team_allowed_ft_pct'),
    ('advanced_ts_pct', 'ytd_team_allowed_advanced_ts_pct'),
    ('advanced_ast_pct', 'ytd_team_allowed_advanced_ast_pct'),
    ('advanced_blk_pct', 'ytd_team_allowed_advanced_blk_pct'),
    ('advanced_ftr', 'ytd_team_allowed_advanced_ftr'),
    ('advanced_3par', 'ytd_team_allowed_advanced_3par'),
    ('offensive_four_factors_efg_pct', 'ytd_team_allowed_offensive_efg_pct'),
    ('offensive_four_factors_tov_pct', 'ytd_team_allowed_offensive_tov_pct'),
    ('offensive_four_factors_orb_pct', 'ytd_team_allowed_offensive_orb_pct'),
    ('defensive_four_factors_efg_pct', 'ytd_team_allowed_defensive_efg_pct'),
    ('defensive_four_factors_tov_pct', 'ytd_team_allowed_defensive_tov_pct'),
    ('defensive_four_factors_drb_pct', 'ytd_team_allowed_defensive_drb_pct')
]

# Compute YTD allowed stats per team
for original_col, new_col in allowed_stats:
    df[new_col] = (
        df.groupby(['team', 'year'])[original_col]
        .transform(lambda x: x.shift().expanding().mean())
        .fillna(0)
    )

# Verify quickly
print(df[['team', 'year'] + [new for _, new in allowed_stats]].head(10))

  team  year  ytd_team_allowed_fg_per_game  ytd_team_allowed_fga_per_game  \
0  ATL  2020                      0.000000                       0.000000
1  ATL  2020                     34.000000                      78.000000
2  ATL  2020                     36.000000                      74.500000
3  ATL  2020                     33.333333                      73.666667
4  ATL  2020                     33.500000                      71.750000
5  ATL  2020                     32.600000                      72.400000
6  ATL  2020                     32.333333                      72.500000
7  ATL  2020                     32.142857                      71.714286
8  ATL  2020                     32.625000                      72.375000
9  ATL  2020                     32.888889                      71.222222

   ytd_team_allowed_3p_per_game  ytd_team_allowed_3pa_per_game  \
0                      0.000000                       0.000000
1                     13.000000                      28.000000
2                      9.500000                      18.500000
3                      8.666667                      22.000000
4                      8.500000                      21.500000
5                      7.600000                      21.200000
6                      7.333333                      21.166667
7                      7.714286                      21.714286
8                      7.875000                      22.000000
9                      9.000000                      22.888889

   ytd_team_allowed_ft_per_game  ytd_team_allowed_fta_per_game  \
0                      0.000000                       0.000000
1                     14.000000                      20.000000
2                     16.000000                      23.000000
3                     15.666667                      21.000000
4                     16.000000                      21.000000
5                     16.600000                      21.200000
6                     18.000000                      22.166667
7                     17.285714                      21.142857
8                     16.625000                      21.000000
9                     16.111111                      20.111111

   ytd_team_allowed_orb_per_game  ytd_team_allowed_trb_per_game  ...  \
0                       0.000000                       0.000000  ...
1                       8.000000                      29.000000  ...
2                      11.000000                      38.000000  ...
3                      10.000000                      36.333333  ...
4                       9.750000                      35.250000  ...
5                       9.800000                      34.800000  ...
6                       9.500000                      34.500000  ...
7                       9.571429                      35.142857  ...
8                      10.250000                      35.250000  ...
9                       9.333333                      35.111111  ...

   ytd_team_allowed_advanced_ast_pct  ytd_team_allowed_advanced_blk_pct  \
0                           0.000000                           0.000000
1                          55.900000                           8.000000
2                          49.400000                           8.050000
3                          46.033333                           6.933333
4                          48.150000                           5.200000
5                          48.860000                           4.880000
6                          47.166667                           5.666667
7                          46.828571                           7.242857
8                          49.725000                           7.050000
9                          51.611111                           6.966667

   ytd_team_allowed_advanced_ftr  ytd_team_allowed_advanced_3par  \
0                       0.000000                        0.000000
1                       0.548000                        0.274000
2                       0.374000                        0.337000
3                       0.387000                        0.269000
4                       0.319250                        0.241500
5                       0.297400                        0.235200
6                       0.296833                        0.262167
7                       0.280571                        0.263000
8                       0.276250                        0.264750
9                       0.247111                        0.278889

   ytd_team_allowed_offensive_efg_pct  ytd_team_allowed_offensive_tov_pct  \
0                            0.000000                            0.000000
1                            0.605000                           17.200000
2                            0.520500                           17.300000
3                            0.478000                           16.366667
4                            0.485250                           15.825000
5                            0.488200                           17.740000
6                            0.495000                           17.800000
7                            0.490714                           17.185714
8                            0.497625                           17.650000
9                            0.488889                           17.444444

   ytd_team_allowed_offensive_orb_pct  ytd_team_allowed_defensive_efg_pct  \
0                            0.000000                            0.000000
1                           16.000000                            0.519000
2                           16.750000                            0.548000
3                           24.666667                            0.511333
4                           22.975000                            0.527500
5                           21.960000                            0.504600
6                           21.950000                            0.498167
7                           22.742857                            0.503714
8                           22.300000                            0.506500
9                           22.466667                            0.529111

   ytd_team_allowed_defensive_tov_pct  ytd_team_allowed_defensive_drb_pct
0                            0.000000                            0.000000
1                           13.000000                           78.900000
2                           15.850000                           67.600000
3                           15.866667                           70.566667
4                           16.050000                           70.425000
5                           14.960000                           71.340000
6                           14.383333                           72.600000
7                           14.471429                           71.757143
8                           13.725000                           70.712500
9                           13.877778                           72.955556

[10 rows x 29 columns]

<ipython-input-142-aa92a140df24>:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-142-aa92a140df24>:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-142-aa92a140df24>:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-142-aa92a140df24>:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-142-aa92a140df24>:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-142-aa92a140df24>:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (

In [143]:
cols_to_create = [
    'ytd_team_allowed_fg_per_game', 'ytd_team_allowed_fga_per_game',
    'ytd_team_allowed_3p_per_game', 'ytd_team_allowed_3pa_per_game',
    'ytd_team_allowed_ft_per_game', 'ytd_team_allowed_fta_per_game',
    'ytd_team_allowed_orb_per_game', 'ytd_team_allowed_trb_per_game',
    'ytd_team_allowed_ast_per_game', 'ytd_team_allowed_stl_per_game',
    'ytd_team_allowed_blk_per_game', 'ytd_team_allowed_tov_per_game',
    'ytd_team_allowed_pf_per_game', 'ytd_team_allowed_fg_pct',
    'ytd_team_allowed_3p_pct', 'ytd_team_allowed_ft_pct',
    'ytd_team_allowed_advanced_ts_pct', 'ytd_team_allowed_advanced_ast_pct',
    'ytd_team_allowed_advanced_blk_pct', 'ytd_team_allowed_advanced_ftr',
    'ytd_team_allowed_advanced_3par', 'ytd_team_allowed_offensive_efg_pct',
    'ytd_team_allowed_offensive_tov_pct', 'ytd_team_allowed_offensive_orb_pct',
    'ytd_team_allowed_defensive_efg_pct', 'ytd_team_allowed_defensive_tov_pct',
    'ytd_team_allowed_defensive_drb_pct'
]

for col in cols_to_create:
    new_col = col.replace('ytd_team_', 'ytd_opp_')

    def get_ytd_opp(row):
        opp_data = df[
            (df['team'] == row['opp']) &
            (
                (df['year'] < row['year']) |
                ((df['year'] == row['year']) & (df['month'] < row['month'])) |
                ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
            )
        ]
        return opp_data[col].iloc[-1] if not opp_data.empty else 0

    df[new_col] = df.apply(get_ytd_opp, axis=1)

# Verification
print(df[['team', 'opp', 'year', 'month', 'day'] + [col.replace('ytd_team_', 'ytd_opp_') for col in cols_to_create]].head(10))

<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)
<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)

  team  opp  year  month   day  ytd_opp_allowed_fg_per_game  \
0  ATL  DAL  2020    7.0  26.0                     0.000000
1  ATL  LVA  2020    7.0  29.0                     0.000000
2  ATL  NYL  2020    7.0  31.0                    34.000000
3  ATL  IND  2020    8.0   2.0                    36.000000
4  ATL  PHO  2020    8.0   4.0                    35.333333
5  ATL  SEA  2020    8.0   6.0                    26.500000
6  ATL  DAL  2020    8.0   8.0                    30.000000
7  ATL  CON  2020    8.0  10.0                    30.000000
8  ATL  SEA  2020    8.0  12.0                    27.285714
9  ATL  PHO  2020    8.0  14.0                    29.750000

   ytd_opp_allowed_fga_per_game  ytd_opp_allowed_3p_per_game  \
0                      0.000000                     0.000000
1                      0.000000                     0.000000
2                     77.000000                     7.000000
3                     68.500000                     8.000000
4                     69.333333                     8.333333
5                     69.750000                     8.250000
6                     67.600000                     6.600000
7                     68.500000                     6.833333
8                     68.857143                     7.714286
9                     69.000000                     7.750000

   ytd_opp_allowed_3pa_per_game  ytd_opp_allowed_ft_per_game  ...  \
0                      0.000000                     0.000000  ...
1                      0.000000                     0.000000  ...
2                     23.000000                    12.000000  ...
3                     19.500000                    20.500000  ...
4                     18.000000                    21.000000  ...
5                     25.500000                    14.000000  ...
6                     19.000000                    17.200000  ...
7                     21.166667                    14.000000  ...
8                     24.857143                    14.142857  ...
9                     22.000000                    17.750000  ...

   ytd_opp_allowed_advanced_ast_pct  ytd_opp_allowed_advanced_blk_pct  \
0                          0.000000                          0.000000
1                          0.000000                          0.000000
2                         60.900000                          9.300000
3                         45.050000                          4.200000
4                         72.333333                          8.800000
5                         60.325000                          8.075000
6                         44.420000                          8.940000
7                         61.916667                          5.033333
8                         62.828571                          9.185714
9                         67.737500                         11.500000

   ytd_opp_allowed_advanced_ftr  ytd_opp_allowed_advanced_3par  \
0                      0.000000                       0.000000
1                      0.000000                       0.000000
2                      0.333000                       0.424000
3                      0.298500                       0.326000
4                      0.370000                       0.360333
5                      0.231250                       0.357000
6                      0.236400                       0.360000
7                      0.351167                       0.297000
8                      0.259714                       0.344000
9                      0.352250                       0.318375

   ytd_opp_allowed_offensive_efg_pct  ytd_opp_allowed_offensive_tov_pct  \
0                           0.000000                           0.000000
1                           0.000000                           0.000000
2                           0.394000                          20.100000
3                           0.515000                          13.550000
4                           0.577667                          17.133333
5                           0.524500                          16.300000
6                           0.465400                          11.220000
7                           0.457333                          15.950000
8                           0.514714                          15.514286
9                           0.523000                          16.250000

   ytd_opp_allowed_offensive_orb_pct  ytd_opp_allowed_defensive_efg_pct  \
0                           0.000000                           0.000000
1                           0.000000                           0.000000
2                          13.500000                           0.487000
3                          23.000000                           0.584000
4                          19.200000                           0.570333
5                          22.875000                           0.434750
6                          23.520000                           0.495200
7                          23.550000                           0.488333
8                          23.114286                           0.449714
9                          20.875000                           0.489500

   ytd_opp_allowed_defensive_tov_pct  ytd_opp_allowed_defensive_drb_pct
0                           0.000000                           0.000000
1                           0.000000                           0.000000
2                          13.500000                          80.000000
3                          11.600000                          77.150000
4                          13.400000                          77.633333
5                          16.275000                          71.600000
6                          17.220000                          71.580000
7                          15.816667                          76.916667
8                          16.957143                          73.814286
9                          16.037500                          76.612500

[10 rows x 32 columns]

<ipython-input-143-8618f64d6216>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_ytd_opp, axis=1)

In [145]:
# Basic shooting percentages
df['ytd_team_allowed_fg_pct'] = (
    df['ytd_team_allowed_fg_per_game'] / df['ytd_team_allowed_fga_per_game']
).fillna(0)

df['ytd_team_allowed_3p_pct'] = (
    df['ytd_team_allowed_3p_per_game'] / df['ytd_team_allowed_3pa_per_game']
).fillna(0)

df['ytd_team_allowed_ft_pct'] = (
    df['ytd_team_allowed_ft_per_game'] / df['ytd_team_allowed_fta_per_game']
).fillna(0)

df['ytd_opp_allowed_fg_pct'] = (
    df['ytd_opp_allowed_fg_per_game'] / df['ytd_opp_allowed_fga_per_game']
).fillna(0)

df['ytd_opp_allowed_3p_pct'] = (
    df['ytd_opp_allowed_3p_per_game'] / df['ytd_opp_allowed_3pa_per_game']
).fillna(0)

df['ytd_opp_allowed_ft_pct'] = (
    df['ytd_opp_allowed_ft_per_game'] / df['ytd_opp_allowed_fta_per_game']
).fillna(0)

# Advanced/Four Factors - Team Allowed
df['ytd_team_allowed_offensive_efg_pct'] = (
    (df['ytd_team_allowed_fg_per_game'] + 0.5 * df['ytd_team_allowed_3p_per_game']) / df['ytd_team_allowed_fga_per_game']
).fillna(0)

df['ytd_team_allowed_offensive_tov_pct'] = (
    df['ytd_team_allowed_tov_per_game'] /
    (df['ytd_team_allowed_fga_per_game'] + 0.44 * df['ytd_team_allowed_fta_per_game'] + df['ytd_team_allowed_tov_per_game'])
).fillna(0)

df['ytd_team_allowed_offensive_orb_pct'] = (
    df['ytd_team_allowed_orb_per_game'] /
    (df['ytd_team_allowed_orb_per_game'] + df['ytd_opp_allowed_trb_per_game'] - df['ytd_opp_allowed_orb_per_game'])
).fillna(0)

df['ytd_team_allowed_defensive_efg_pct'] = (
    (df['ytd_opp_allowed_fg_per_game'] + 0.5 * df['ytd_opp_allowed_3p_per_game']) / df['ytd_opp_allowed_fga_per_game']
).fillna(0)

df['ytd_team_allowed_defensive_tov_pct'] = (
    df['ytd_opp_allowed_tov_per_game'] /
    (df['ytd_opp_allowed_fga_per_game'] + 0.44 * df['ytd_opp_allowed_fta_per_game'] + df['ytd_opp_allowed_tov_per_game'])
).fillna(0)

df['ytd_team_allowed_defensive_drb_pct'] = (
    (df['ytd_team_allowed_trb_per_game'] - df['ytd_team_allowed_orb_per_game']) /
    (df['ytd_team_allowed_trb_per_game'] - df['ytd_team_allowed_orb_per_game'] + df['ytd_opp_allowed_orb_per_game'])
).fillna(0)

# Advanced/Four Factors - Opponent Allowed
df['ytd_opp_allowed_offensive_efg_pct'] = (
    (df['ytd_opp_allowed_fg_per_game'] + 0.5 * df['ytd_opp_allowed_3p_per_game']) / df['ytd_opp_allowed_fga_per_game']
).fillna(0)

df['ytd_opp_allowed_offensive_tov_pct'] = (
    df['ytd_opp_allowed_tov_per_game'] /
    (df['ytd_opp_allowed_fga_per_game'] + 0.44 * df['ytd_opp_allowed_fta_per_game'] + df['ytd_opp_allowed_tov_per_game'])
).fillna(0)

df['ytd_opp_allowed_offensive_orb_pct'] = (
    df['ytd_opp_allowed_orb_per_game'] /
    (df['ytd_opp_allowed_orb_per_game'] + df['ytd_team_allowed_trb_per_game'] - df['ytd_team_allowed_orb_per_game'])
).fillna(0)

df['ytd_opp_allowed_defensive_efg_pct'] = (
    (df['ytd_team_allowed_fg_per_game'] + 0.5 * df['ytd_team_allowed_3p_per_game']) / df['ytd_team_allowed_fga_per_game']
).fillna(0)

df['ytd_opp_allowed_defensive_tov_pct'] = (
    df['ytd_team_allowed_tov_per_game'] /
    (df['ytd_team_allowed_fga_per_game'] + 0.44 * df['ytd_team_allowed_fta_per_game'] + df['ytd_team_allowed_tov_per_game'])
).fillna(0)

df['ytd_opp_allowed_defensive_drb_pct'] = (
    (df['ytd_opp_allowed_trb_per_game'] - df['ytd_opp_allowed_orb_per_game']) /
    (df['ytd_opp_allowed_trb_per_game'] - df['ytd_opp_allowed_orb_per_game'] + df['ytd_team_allowed_orb_per_game'])
).fillna(0)

# Quick check on recalculated columns
print(df[['team', 'year', 'ytd_team_allowed_fg_pct', 'ytd_team_allowed_offensive_efg_pct',
          'ytd_opp_allowed_fg_pct', 'ytd_opp_allowed_defensive_efg_pct']].head(10))

  team  year  ytd_team_allowed_fg_pct  ytd_team_allowed_offensive_efg_pct  \
0  ATL  2020                 0.000000                            0.000000
1  ATL  2020                 0.435897                            0.519231
2  ATL  2020                 0.483221                            0.546980
3  ATL  2020                 0.452489                            0.511312
4  ATL  2020                 0.466899                            0.526132
5  ATL  2020                 0.450276                            0.502762
6  ATL  2020                 0.445977                            0.496552
7  ATL  2020                 0.448207                            0.501992
8  ATL  2020                 0.450777                            0.505181
9  ATL  2020                 0.461778                            0.524961

   ytd_opp_allowed_fg_pct  ytd_opp_allowed_defensive_efg_pct
0                0.000000                           0.000000
1                0.000000                           0.519231
2                0.441558                           0.546980
3                0.525547                           0.511312
4                0.509615                           0.526132
5                0.379928                           0.502762
6                0.443787                           0.496552
7                0.437956                           0.501992
8                0.396266                           0.505181
9                0.431159                           0.524961

In [148]:
# Team YTD
df['ytd_team_advanced_stl_pct'] = (
    df.groupby(['team', 'year'])['advanced_stl_pct']
      .transform(lambda x: x.shift().expanding().mean())
      .fillna(0)
)

# Opponent YTD (mapping from team's YTD above)
def get_ytd_opp_stl_pct(row):
    opp_data = df[
        (df['team'] == row['opp']) &
        (
            (df['year'] < row['year']) |
            ((df['year'] == row['year']) & (df['month'] < row['month'])) |
            ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
        )
    ]
    return opp_data['ytd_team_advanced_stl_pct'].iloc[-1] if not opp_data.empty else 0

df['ytd_opp_advanced_stl_pct'] = df.apply(get_ytd_opp_stl_pct, axis=1)

# Corrected Team Allowed (using opponent's advanced_stl_pct)
df['ytd_team_allowed_advanced_stl_pct'] = (
    df.groupby(['team', 'year'])['advanced_stl_pct']
      .transform(lambda x: x.shift().expanding().mean())
      .fillna(0)
)

# Corrected Opponent Allowed (mapping team's allowed correctly)
def get_ytd_opp_allowed_stl_pct(row):
    opp_data = df[
        (df['team'] == row['opp']) &
        (
            (df['year'] < row['year']) |
            ((df['year'] == row['year']) & (df['month'] < row['month'])) |
            ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
        )
    ]
    return opp_data['ytd_team_allowed_advanced_stl_pct'].iloc[-1] if not opp_data.empty else 0

df['ytd_opp_allowed_advanced_stl_pct'] = df.apply(get_ytd_opp_allowed_stl_pct, axis=1)

# Verify carefully now:
print(df[['team', 'year', 'advanced_stl_pct',
          'ytd_team_advanced_stl_pct',
          'ytd_team_allowed_advanced_stl_pct',
          'ytd_opp_allowed_advanced_stl_pct']].head(10))

  team  year  advanced_stl_pct  ytd_team_advanced_stl_pct  \
0  ATL  2020               8.0                   0.000000
1  ATL  2020              14.2                   8.000000
2  ATL  2020               9.7                  11.100000
3  ATL  2020               7.7                  10.633333
4  ATL  2020               8.5                   9.900000
5  ATL  2020               8.3                   9.620000
6  ATL  2020               5.4                   9.400000
7  ATL  2020               3.7                   8.828571
8  ATL  2020               7.8                   8.187500
9  ATL  2020               6.3                   8.144444

   ytd_team_allowed_advanced_stl_pct  ytd_opp_allowed_advanced_stl_pct
0                           0.000000                          0.000000
1                           8.000000                          0.000000
2                          11.100000                          5.700000
3                          10.633333                          5.450000
4                           9.900000                          7.933333
5                           9.620000                         11.850000
6                           9.400000                         10.960000
7                           8.828571                         11.366667
8                           8.187500                         12.671429
9                           8.144444                          8.875000

In [149]:
cols_to_drop = [
    'ytd_team_allowed_fg_per_game',
    'ytd_team_allowed_fga_per_game',
    'ytd_team_allowed_3p_per_game',
    'ytd_team_allowed_3pa_per_game',
    'ytd_team_allowed_ft_per_game',
    'ytd_team_allowed_fta_per_game',
    'ytd_team_allowed_orb_per_game',
    'ytd_team_allowed_trb_per_game',
    'ytd_team_allowed_ast_per_game',
    'ytd_team_allowed_stl_per_game',
    'ytd_team_allowed_blk_per_game',
    'ytd_team_allowed_tov_per_game',
    'ytd_team_allowed_pf_per_game',
    'ytd_team_allowed_fg_pct',
    'ytd_team_allowed_3p_pct',
    'ytd_team_allowed_ft_pct',
    'ytd_team_allowed_advanced_ts_pct',
    'ytd_team_allowed_advanced_ast_pct',
    'ytd_team_allowed_advanced_blk_pct',
    'ytd_team_allowed_advanced_ftr',
    'ytd_team_allowed_advanced_3par',
    'ytd_team_allowed_offensive_efg_pct',
    'ytd_team_allowed_offensive_tov_pct',
    'ytd_team_allowed_offensive_orb_pct',
    'ytd_team_allowed_defensive_efg_pct',
    'ytd_team_allowed_defensive_tov_pct',
    'ytd_team_allowed_defensive_drb_pct',
    'ytd_opp_allowed_fg_per_game',
    'ytd_opp_allowed_fga_per_game',
    'ytd_opp_allowed_3p_per_game',
    'ytd_opp_allowed_3pa_per_game',
    'ytd_opp_allowed_ft_per_game',
    'ytd_opp_allowed_fta_per_game',
    'ytd_opp_allowed_orb_per_game',
    'ytd_opp_allowed_trb_per_game',
    'ytd_opp_allowed_ast_per_game',
    'ytd_opp_allowed_stl_per_game',
    'ytd_opp_allowed_blk_per_game',
    'ytd_opp_allowed_tov_per_game',
    'ytd_opp_allowed_pf_per_game',
    'ytd_opp_allowed_fg_pct',
    'ytd_opp_allowed_3p_pct',
    'ytd_opp_allowed_ft_pct',
    'ytd_opp_allowed_advanced_ts_pct',
    'ytd_opp_allowed_advanced_ast_pct',
    'ytd_opp_allowed_advanced_blk_pct',
    'ytd_opp_allowed_advanced_ftr',
    'ytd_opp_allowed_advanced_3par',
    'ytd_opp_allowed_offensive_efg_pct',
    'ytd_opp_allowed_offensive_tov_pct',
    'ytd_opp_allowed_offensive_orb_pct',
    'ytd_opp_allowed_defensive_efg_pct',
    'ytd_opp_allowed_defensive_tov_pct',
    'ytd_opp_allowed_defensive_drb_pct'
]

df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

In [152]:
df.drop(columns=['ytd_team_allowed_advanced_stl_pct', 'ytd_opp_allowed_advanced_stl_pct'], inplace=True, errors='ignore')

# Confirm the drop
print([col for col in df.columns if '_allowed_' in col])

['ytd_team_allowed_mean', 'ytd_team_allowed_median', 'ytd_team_allowed_min', 'ytd_team_allowed_max', 'ytd_opp_allowed_mean', 'ytd_opp_allowed_median', 'ytd_opp_allowed_min', 'ytd_opp_allowed_max']

In [155]:
# Create ytd_team_allowed_fg_per_game
df['ytd_team_allowed_fg_per_game'] = (
    df.groupby(['team', 'year'])['opp_fg']
      .transform(lambda x: x.shift().expanding().mean())
      .fillna(0)
)

# Verify carefully (first 10 rows for one team)
print(
    df[df['team'] == 'ATL'][['team', 'year', 'opp', 'opp_fg', 'ytd_team_allowed_fg_per_game']].head(10)
)

  team  year  opp  opp_fg  ytd_team_allowed_fg_per_game
0  ATL  2020  DAL      34                      0.000000
1  ATL  2020  LVA      38                     34.000000
2  ATL  2020  NYL      28                     36.000000
3  ATL  2020  IND      34                     33.333333
4  ATL  2020  PHO      29                     33.500000
5  ATL  2020  SEA      31                     32.600000
6  ATL  2020  DAL      31                     32.333333
7  ATL  2020  CON      36                     32.142857
8  ATL  2020  SEA      35                     32.625000
9  ATL  2020  PHO      32                     32.888889

<ipython-input-155-f035bb47e46a>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_fg_per_game'] = (

In [156]:
# counting stats including advanced_stl_pct
counting_cols = [
    'opp_fga', 'opp_3p', 'opp_3pa', 'opp_ft', 'opp_fta',
    'opp_orb', 'opp_trb', 'opp_ast', 'opp_stl', 'opp_blk',
    'opp_tov', 'opp_pf', 'advanced_stl_pct'
]

# loop and create allowed columns
for col in counting_cols:
    df[f'ytd_team_allowed_{col}_per_game'] = (
        df.groupby(['team', 'year'])[col]
          .transform(lambda x: x.shift().expanding().mean())
          .fillna(0)
    )

# quick verification
print(df[df['team'] == 'ATL'][['team', 'year', 'opp', 'opp_fga', 'ytd_team_allowed_opp_fga_per_game', 'opp_ast', 'ytd_team_allowed_opp_ast_per_game', 'advanced_stl_pct', 'ytd_team_allowed_advanced_stl_pct_per_game']].head(10))

<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (

  team  year  opp  opp_fga  ytd_team_allowed_opp_fga_per_game  opp_ast  \
0  ATL  2020  DAL       78                           0.000000       18
1  ATL  2020  LVA       71                          78.000000       16
2  ATL  2020  NYL       72                          74.500000       13
3  ATL  2020  IND       66                          73.666667       26
4  ATL  2020  PHO       75                          71.750000       19
5  ATL  2020  SEA       73                          72.400000       21
6  ATL  2020  DAL       67                          72.500000       17
7  ATL  2020  CON       77                          71.714286       19
8  ATL  2020  SEA       62                          72.375000       31
9  ATL  2020  PHO       65                          71.222222       24

   ytd_team_allowed_opp_ast_per_game  advanced_stl_pct  \
0                           0.000000               8.0
1                          18.000000              14.2
2                          17.000000               9.7
3                          15.666667               7.7
4                          18.250000               8.5
5                          18.400000               8.3
6                          18.833333               5.4
7                          18.571429               3.7
8                          18.625000               7.8
9                          20.000000               6.3

   ytd_team_allowed_advanced_stl_pct_per_game
0                                    0.000000
1                                    8.000000
2                                   11.100000
3                                   10.633333
4                                    9.900000
5                                    9.620000
6                                    9.400000
7                                    8.828571
8                                    8.187500
9                                    8.144444

<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (
<ipython-input-156-ae951d87fa77>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ytd_team_allowed_{col}_per_game'] = (

In [157]:
# Calculated allowed percentages
df['ytd_team_allowed_fg_pct'] = (
    df['ytd_team_allowed_fg_per_game'] / df['ytd_team_allowed_opp_fga_per_game']
).fillna(0)

df['ytd_team_allowed_3p_pct'] = (
    df['ytd_team_allowed_opp_3p_per_game'] / df['ytd_team_allowed_opp_3pa_per_game']
).fillna(0)

df['ytd_team_allowed_ft_pct'] = (
    df['ytd_team_allowed_opp_ft_per_game'] / df['ytd_team_allowed_opp_fta_per_game']
).fillna(0)

df['ytd_team_allowed_advanced_ts_pct'] = (
    df['ytd_team_allowed_fg_per_game'] /
    (2 * (df['ytd_team_allowed_opp_fga_per_game'] + 0.44 * df['ytd_team_allowed_opp_fta_per_game']))
).fillna(0)

df['ytd_team_allowed_offensive_efg_pct'] = (
    (df['ytd_team_allowed_fg_per_game'] + 0.5 * df['ytd_team_allowed_opp_3p_per_game']) /
    df['ytd_team_allowed_opp_fga_per_game']
).fillna(0)

df['ytd_team_allowed_offensive_tov_pct'] = (
    df['ytd_team_allowed_opp_tov_per_game'] /
    (df['ytd_team_allowed_opp_fga_per_game'] + 0.44 * df['ytd_team_allowed_opp_fta_per_game'] + df['ytd_team_allowed_opp_tov_per_game'])
).fillna(0)

df['ytd_team_allowed_offensive_orb_pct'] = (
    df['ytd_team_allowed_opp_orb_per_game'] /
    (df['ytd_team_allowed_opp_orb_per_game'] + df['ytd_team_trb_per_game'] - df['ytd_team_orb_per_game'])
).fillna(0)

df['ytd_team_allowed_defensive_efg_pct'] = (
    (df['ytd_team_fg_per_game'] + 0.5 * df['ytd_team_3p_per_game']) / df['ytd_team_fga_per_game']
).fillna(0)

df['ytd_team_allowed_defensive_tov_pct'] = (
    df['ytd_team_tov_per_game'] /
    (df['ytd_team_fga_per_game'] + 0.44 * df['ytd_team_fta_per_game'] + df['ytd_team_tov_per_game'])
).fillna(0)

df['ytd_team_allowed_defensive_drb_pct'] = (
    (df['ytd_team_allowed_opp_trb_per_game'] - df['ytd_team_allowed_opp_orb_per_game']) /
    (df['ytd_team_allowed_opp_trb_per_game'] - df['ytd_team_allowed_opp_orb_per_game'] + df['ytd_team_orb_per_game'])
).fillna(0)

# Quick verification
print(df[df['team'] == 'ATL'][[
    'team', 'year', 'ytd_team_allowed_fg_pct', 'ytd_team_allowed_3p_pct',
    'ytd_team_allowed_ft_pct', 'ytd_team_allowed_offensive_efg_pct',
    'ytd_team_allowed_offensive_tov_pct', 'ytd_team_allowed_offensive_orb_pct'
]].head(10))

  team  year  ytd_team_allowed_fg_pct  ytd_team_allowed_3p_pct  \
0  ATL  2020                 0.000000                 0.000000
1  ATL  2020                 0.435897                 0.464286
2  ATL  2020                 0.483221                 0.513514
3  ATL  2020                 0.452489                 0.393939
4  ATL  2020                 0.466899                 0.395349
5  ATL  2020                 0.450276                 0.358491
6  ATL  2020                 0.445977                 0.346457
7  ATL  2020                 0.448207                 0.355263
8  ATL  2020                 0.450777                 0.357955
9  ATL  2020                 0.461778                 0.393204

   ytd_team_allowed_ft_pct  ytd_team_allowed_offensive_efg_pct  \
0                 0.000000                            0.000000
1                 0.700000                            0.519231
2                 0.695652                            0.546980
3                 0.746032                            0.511312
4                 0.761905                            0.526132
5                 0.783019                            0.502762
6                 0.812030                            0.496552
7                 0.817568                            0.501992
8                 0.791667                            0.505181
9                 0.801105                            0.524961

   ytd_team_allowed_offensive_tov_pct  ytd_team_allowed_offensive_orb_pct
0                            0.000000                            0.000000
1                            0.130261                            0.210526
2                            0.159014                            0.314286
3                            0.158934                            0.288462
4                            0.160638                            0.291045
5                            0.149800                            0.281609
6                            0.143967                            0.268868
7                            0.144770                            0.276860
8                            0.137399                            0.289753
9                            0.138650                            0.275410

<ipython-input-157-301d53cf1e08>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_fg_pct'] = (
<ipython-input-157-301d53cf1e08>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_3p_pct'] = (
<ipython-input-157-301d53cf1e08>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_ft_pct'] = (
<ipython-input-157-301d53cf1e08>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_advanced_ts_pct'] = (
<ipython-input-157-301d53cf1e08>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_offensive_efg_pct'] = (
<ipython-input-157-301d53cf1e08>:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_offensive_tov_pct'] = (
<ipython-input-157-301d53cf1e08>:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_offensive_orb_pct'] = (
<ipython-input-157-301d53cf1e08>:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_defensive_efg_pct'] = (
<ipython-input-157-301d53cf1e08>:38: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_defensive_tov_pct'] = (
<ipython-input-157-301d53cf1e08>:43: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ytd_team_allowed_defensive_drb_pct'] = (

In [158]:
# Quick verification with actual columns included
print(df[df['team'] == 'ATL'][[
    'team', 'year',
    'opp_fg_pct', 'ytd_team_allowed_fg_pct',
    'opp_3p_pct', 'ytd_team_allowed_3p_pct',
    'opp_ft_pct', 'ytd_team_allowed_ft_pct',
    'offensive_four_factors_efg_pct', 'ytd_team_allowed_offensive_efg_pct',
    'offensive_four_factors_tov_pct', 'ytd_team_allowed_offensive_tov_pct',
    'offensive_four_factors_orb_pct', 'ytd_team_allowed_offensive_orb_pct'
]].head(10))

  team  year  opp_fg_pct  ytd_team_allowed_fg_pct  opp_3p_pct  \
0  ATL  2020       0.436                 0.000000       0.464
1  ATL  2020       0.535                 0.435897       0.667
2  ATL  2020       0.389                 0.483221       0.241
3  ATL  2020       0.515                 0.452489       0.400
4  ATL  2020       0.387                 0.466899       0.200
5  ATL  2020       0.425                 0.450276       0.286
6  ATL  2020       0.463                 0.445977       0.400
7  ATL  2020       0.468                 0.448207       0.375
8  ATL  2020       0.565                 0.450777       0.600
9  ATL  2020       0.492                 0.461778       0.480

   ytd_team_allowed_3p_pct  opp_ft_pct  ytd_team_allowed_ft_pct  \
0                 0.000000       0.700                 0.000000
1                 0.464286       0.692                 0.700000
2                 0.513514       0.882                 0.695652
3                 0.393939       0.810                 0.746032
4                 0.395349       0.864                 0.761905
5                 0.358491       0.926                 0.783019
6                 0.346457       0.867                 0.812030
7                 0.355263       0.600                 0.817568
8                 0.357955       0.923                 0.791667
9                 0.393204       0.870                 0.801105

   offensive_four_factors_efg_pct  ytd_team_allowed_offensive_efg_pct  \
0                           0.605                            0.000000
1                           0.436                            0.519231
2                           0.393                            0.546980
3                           0.507                            0.511312
4                           0.500                            0.526132
5                           0.529                            0.502762
6                           0.465                            0.496552
7                           0.546                            0.501992
8                           0.419                            0.505181
9                           0.474                            0.524961

   offensive_four_factors_tov_pct  ytd_team_allowed_offensive_tov_pct  \
0                            17.2                            0.000000
1                            17.4                            0.130261
2                            14.5                            0.159014
3                            14.2                            0.158934
4                            25.4                            0.160638
5                            18.1                            0.149800
6                            13.5                            0.143967
7                            20.9                            0.144770
8                            15.8                            0.137399
9                            12.6                            0.138650

   offensive_four_factors_orb_pct  ytd_team_allowed_offensive_orb_pct
0                            16.0                            0.000000
1                            17.5                            0.210526
2                            40.5                            0.314286
3                            17.9                            0.288462
4                            17.9                            0.291045
5                            21.9                            0.281609
6                            27.5                            0.268868
7                            19.2                            0.276860
8                            23.8                            0.289753
9                            31.6                            0.275410

In [159]:
# Loop over ALL ytd_team_allowed_ columns to create ytd_opp_allowed_
allowed_cols = [col for col in df.columns if col.startswith('ytd_team_allowed_')]

for col in allowed_cols:
    new_col = col.replace('ytd_team_allowed_', 'ytd_opp_allowed_')

    def map_team_to_opp(row):
        opp_data = df[
            (df['team'] == row['opp']) &
            (
                (df['year'] < row['year']) |
                ((df['year'] == row['year']) & (df['month'] < row['month'])) |
                ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
            )
        ]
        return opp_data[col].iloc[-1] if not opp_data.empty else 0

    df[new_col] = df.apply(map_team_to_opp, axis=1)

# Quick verification
print(df[['team', 'opp', 'year', 'month', 'day'] + [c.replace('ytd_team_allowed_', 'ytd_opp_allowed_') for c in allowed_cols]].head(15))

<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)

   team  opp  year  month   day  ytd_opp_allowed_mean  ytd_opp_allowed_median  \
0   ATL  DAL  2020    7.0  26.0              0.000000                     0.0
1   ATL  LVA  2020    7.0  29.0              0.000000                     0.0
2   ATL  NYL  2020    7.0  31.0             87.000000                    87.0
3   ATL  IND  2020    8.0   2.0            100.500000                   100.5
4   ATL  PHO  2020    8.0   4.0            100.000000                    99.0
5   ATL  SEA  2020    8.0   6.0             75.250000                    73.0
6   ATL  DAL  2020    8.0   8.0             83.800000                    80.0
7   ATL  CON  2020    8.0  10.0             80.833333                    79.5
8   ATL  SEA  2020    8.0  12.0             76.428571                    74.0
9   ATL  PHO  2020    8.0  14.0             85.000000                    82.5
10  ATL  CHI  2020    8.0  16.0             84.555556                    86.0
11  ATL  WAS  2020    8.0  19.0             80.111111                    81.0
12  ATL  LAS  2020    8.0  21.0             78.900000                    77.0
13  ATL  MIN  2020    8.0  23.0             75.909091                    80.0
14  ATL  MIN  2020    8.0  28.0             76.250000                    80.0

    ytd_opp_allowed_min  ytd_opp_allowed_max  ytd_opp_allowed_fg_per_game  \
0                   0.0                  0.0                     0.000000
1                   0.0                  0.0                     0.000000
2                  87.0                 87.0                    34.000000
3                 100.0                101.0                    36.000000
4                  95.0                106.0                    35.333333
5                  66.0                 89.0                    26.500000
6                  73.0                105.0                    30.000000
7                  68.0                 94.0                    30.000000
8                  66.0                 92.0                    27.285714
9                  67.0                106.0                    29.750000
10                 71.0                 96.0                    31.777778
11                 68.0                 91.0                    28.444444
12                 64.0                 96.0                    28.000000
13                 48.0                 97.0                    27.454545
14                 48.0                 97.0                    27.250000

    ...  ytd_opp_allowed_fg_pct  ytd_opp_allowed_3p_pct  \
0   ...                0.000000                0.000000
1   ...                0.000000                0.000000
2   ...                0.441558                0.304348
3   ...                0.525547                0.410256
4   ...                0.509615                0.462963
5   ...                0.379928                0.323529
6   ...                0.443787                0.347368
7   ...                0.437956                0.322835
8   ...                0.396266                0.310345
9   ...                0.431159                0.352273
10  ...                0.464286                0.397516
11  ...                0.445217                0.354167
12  ...                0.439560                0.360190
13  ...                0.422378                0.323770
14  ...                0.421935                0.316176

    ytd_opp_allowed_ft_pct  ytd_opp_allowed_advanced_ts_pct  \
0                 0.000000                         0.000000
1                 0.000000                         0.000000
2                 0.800000                         0.203349
3                 0.773585                         0.224551
4                 0.875000                         0.221128
5                 0.861538                         0.172302
6                 0.826923                         0.195435
7                 0.763636                         0.195908
8                 0.860870                         0.179309
9                 0.850299                         0.190254
10                0.748503                         0.207403
11                0.762162                         0.195003
12                0.788660                         0.193809
13                0.767677                         0.188251
14                0.770925                         0.186883

    ytd_opp_allowed_offensive_efg_pct  ytd_opp_allowed_offensive_tov_pct  \
0                            0.000000                           0.000000
1                            0.000000                           0.000000
2                            0.487013                           0.134576
3                            0.583942                           0.115817
4                            0.569712                           0.133728
5                            0.439068                           0.163221
6                            0.492604                           0.172503
7                            0.487835                           0.159224
8                            0.452282                           0.169888
9                            0.487319                           0.159843
10                           0.516234                           0.167777
11                           0.504348                           0.174755
12                           0.499215                           0.204765
13                           0.477622                           0.174026
14                           0.477419                           0.173769

    ytd_opp_allowed_offensive_orb_pct  ytd_opp_allowed_defensive_efg_pct  \
0                            0.000000                           0.000000
1                            0.000000                           0.000000
2                            0.200000                           0.393939
3                            0.227273                           0.514184
4                            0.219780                           0.579082
5                            0.277027                           0.522140
6                            0.296970                           0.465054
7                            0.227053                           0.456576
8                            0.256917                           0.512658
9                            0.232727                           0.520446
10                           0.221122                           0.548520
11                           0.227723                           0.478793
12                           0.240625                           0.544444
13                           0.254011                           0.503477
14                           0.248768                           0.505148

    ytd_opp_allowed_defensive_tov_pct  ytd_opp_allowed_defensive_drb_pct
0                            0.000000                           0.000000
1                            0.000000                           0.000000
2                            0.200676                           0.864865
3                            0.135516                           0.782609
4                            0.173837                           0.797980
5                            0.162793                           0.768657
6                            0.112379                           0.761421
7                            0.159120                           0.763889
8                            0.155170                           0.767932
9                            0.163134                           0.785978
10                           0.183815                           0.745520
11                           0.151084                           0.804348
12                           0.163626                           0.814815
13                           0.171303                           0.687500
14                           0.170393                           0.691906

[15 rows x 33 columns]

<ipython-input-159-3abda3510e5a>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)

In [162]:
# 10-game rolling average for team_score
df['rolling_10_team_score_mean'] = (
    df.groupby(['team', 'year'])['team_score']
      .transform(lambda x: x.shift().rolling(window=10, min_periods=1).mean())
      .fillna(0)
)

# Quick verification
print(df[['team', 'year', 'team_score', 'rolling_10_team_score_mean']].head(30))

    team  year  team_score  rolling_10_team_score_mean
0    ATL  2020       105.0                    0.000000
1    ATL  2020        70.0                  105.000000
2    ATL  2020        84.0                   87.500000
3    ATL  2020        77.0                   86.333333
4    ATL  2020        74.0                   84.000000
5    ATL  2020        92.0                   82.000000
6    ATL  2020        75.0                   83.666667
7    ATL  2020        82.0                   82.428571
8    ATL  2020        63.0                   82.375000
9    ATL  2020        80.0                   80.222222
10   ATL  2020        67.0                   80.200000
11   ATL  2020        91.0                   76.400000
12   ATL  2020        85.0                   78.500000
13   ATL  2020        78.0                   78.600000
14   ATL  2020        79.0                   78.700000
15   ATL  2020        79.0                   79.200000
16   ATL  2020       102.0                   77.900000
17   ATL  2020        62.0                   80.600000
18   ATL  2020        79.0                   78.600000
19   ATL  2020        97.0                   80.200000
20   ATL  2020        82.0                   81.900000
21   ATL  2020        78.0                   83.400000
264  ATL  2021        67.0                    0.000000
265  ATL  2021        77.0                   67.000000
266  ATL  2021        83.0                   72.000000
267  ATL  2021        90.0                   75.666667
268  ATL  2021       101.0                   79.250000
269  ATL  2021        90.0                   83.600000
270  ATL  2021        84.0                   84.666667
271  ATL  2021        80.0                   84.571429

In [167]:
# Calculate rolling 10-game median for team_score (excluding current game)
df['rolling_10_team_score_median'] = (
    df.groupby(['team', 'year'])['team_score']
      .transform(lambda x: x.shift().rolling(10, min_periods=1).median())
      .fillna(0)
)

# Quick verification
print(df[['team', 'year', 'team_score', 'rolling_10_team_score_median']].head(15))

   team  year  team_score  rolling_10_team_score_median
0   ATL  2020       105.0                           0.0
1   ATL  2020        70.0                         105.0
2   ATL  2020        84.0                          87.5
3   ATL  2020        77.0                          84.0
4   ATL  2020        74.0                          80.5
5   ATL  2020        92.0                          77.0
6   ATL  2020        75.0                          80.5
7   ATL  2020        82.0                          77.0
8   ATL  2020        63.0                          79.5
9   ATL  2020        80.0                          77.0
10  ATL  2020        67.0                          78.5
11  ATL  2020        91.0                          76.0
12  ATL  2020        85.0                          78.5
13  ATL  2020        78.0                          78.5
14  ATL  2020        79.0                          79.0

<ipython-input-167-fe67c48dd3ef>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_score_median'] = (

In [168]:
# Calculate rolling 10-game minimum for team_score (excluding current game)
df['rolling_10_team_score_min'] = (
    df.groupby(['team', 'year'])['team_score']
      .transform(lambda x: x.shift().rolling(10, min_periods=1).min())
      .fillna(0)
)

# Quick verification
print(df[['team', 'year', 'team_score', 'rolling_10_team_score_min']].head(15))

   team  year  team_score  rolling_10_team_score_min
0   ATL  2020       105.0                        0.0
1   ATL  2020        70.0                      105.0
2   ATL  2020        84.0                       70.0
3   ATL  2020        77.0                       70.0
4   ATL  2020        74.0                       70.0
5   ATL  2020        92.0                       70.0
6   ATL  2020        75.0                       70.0
7   ATL  2020        82.0                       70.0
8   ATL  2020        63.0                       70.0
9   ATL  2020        80.0                       63.0
10  ATL  2020        67.0                       63.0
11  ATL  2020        91.0                       63.0
12  ATL  2020        85.0                       63.0
13  ATL  2020        78.0                       63.0
14  ATL  2020        79.0                       63.0

<ipython-input-168-e3072310eb89>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_score_min'] = (

In [169]:
# Calculate rolling 10-game maximum for team_score (excluding current game)
df['rolling_10_team_score_max'] = (
    df.groupby(['team', 'year'])['team_score']
      .transform(lambda x: x.shift().rolling(10, min_periods=1).max())
      .fillna(0)
)

# Quick verification
print(df[['team', 'year', 'team_score', 'rolling_10_team_score_max']].head(15))

   team  year  team_score  rolling_10_team_score_max
0   ATL  2020       105.0                        0.0
1   ATL  2020        70.0                      105.0
2   ATL  2020        84.0                      105.0
3   ATL  2020        77.0                      105.0
4   ATL  2020        74.0                      105.0
5   ATL  2020        92.0                      105.0
6   ATL  2020        75.0                      105.0
7   ATL  2020        82.0                      105.0
8   ATL  2020        63.0                      105.0
9   ATL  2020        80.0                      105.0
10  ATL  2020        67.0                      105.0
11  ATL  2020        91.0                       92.0
12  ATL  2020        85.0                       92.0
13  ATL  2020        78.0                       92.0
14  ATL  2020        79.0                       92.0

<ipython-input-169-adb1154c31bb>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_score_max'] = (

In [171]:
# List of columns to map from team to opp
team_cols = [
    'rolling_10_team_score_mean',
    'rolling_10_team_score_median',
    'rolling_10_team_score_min',
    'rolling_10_team_score_max'
]

for col in team_cols:
    opp_col = col.replace('team', 'opp')

    # Map rolling team stats to opponent clearly (excluding current game)
    def get_rolling_opp(row):
        opp_data = df[
            (df['team'] == row['opp']) &
            (
                (df['year'] < row['year']) |
                ((df['year'] == row['year']) & (df['month'] < row['month'])) |
                ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
            )
        ]
        return opp_data[col].iloc[-1] if not opp_data.empty else 0

    df[opp_col] = df.apply(get_rolling_opp, axis=1)

# Quick verification
print(df[['team', 'opp', 'year', 'month', 'day'] + [c.replace('team', 'opp') for c in team_cols]].head(15))

<ipython-input-171-cfc8b62088f4>:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_opp, axis=1)
<ipython-input-171-cfc8b62088f4>:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_opp, axis=1)
<ipython-input-171-cfc8b62088f4>:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_opp, axis=1)

   team  opp  year  month   day  rolling_10_opp_score_mean  \
0   ATL  DAL  2020    7.0  26.0                   0.000000
1   ATL  LVA  2020    7.0  29.0                   0.000000
2   ATL  NYL  2020    7.0  31.0                  71.000000
3   ATL  IND  2020    8.0   2.0                  91.000000
4   ATL  PHO  2020    8.0   4.0                  92.666667
5   ATL  SEA  2020    8.0   6.0                  82.250000
6   ATL  DAL  2020    8.0   8.0                  82.600000
7   ATL  CON  2020    8.0  10.0                  78.000000
8   ATL  SEA  2020    8.0  12.0                  83.285714
9   ATL  PHO  2020    8.0  14.0                  88.750000
10  ATL  CHI  2020    8.0  16.0                  86.777778
11  ATL  WAS  2020    8.0  19.0                  78.777778
12  ATL  LAS  2020    8.0  21.0                  86.200000
13  ATL  MIN  2020    8.0  23.0                  81.700000
14  ATL  MIN  2020    8.0  28.0                  84.100000

    rolling_10_opp_score_median  rolling_10_opp_score_min  \
0                           0.0                       0.0
1                           0.0                       0.0
2                          71.0                      71.0
3                          91.0                      76.0
4                         100.0                      76.0
5                          84.0                      71.0
6                          79.0                      70.0
7                          75.0                      69.0
8                          87.0                      71.0
9                          93.5                      68.0
10                         88.0                      71.0
11                         84.0                      48.0
12                         84.0                      75.0
13                         82.0                      66.0
14                         85.0                      68.0

    rolling_10_opp_score_max
0                        0.0
1                        0.0
2                       71.0
3                      106.0
4                      102.0
5                       90.0
6                       95.0
7                       91.0
8                       93.0
9                      102.0
10                     100.0
11                     101.0
12                      99.0
13                      94.0
14                      94.0

<ipython-input-171-cfc8b62088f4>:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_opp, axis=1)

In [173]:
# Corrected counting columns (percentages removed)
counting_cols = [
    'team_fg', 'team_fga', 'team_3p', 'team_3pa',
    'team_ft', 'team_fta', 'team_orb', 'team_trb',
    'team_ast', 'team_stl', 'team_blk', 'team_tov',
    'team_pf', 'advanced_stl_pct'
]

# Loop for team counting cols, rolling 10-game averages
for col in counting_cols:
    df[f'rolling_10_{col}'] = (
        df.groupby(['team', 'year'])[col]
          .transform(lambda x: x.shift().rolling(window=10, min_periods=1).mean())
          .fillna(0)
    )

# Quick verification
print(df[['team', 'year'] + [f'rolling_10_{col}' for col in counting_cols]].head(15))

<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (

   team  year  rolling_10_team_fg  rolling_10_team_fga  rolling_10_team_3p  \
0   ATL  2020            0.000000             0.000000            0.000000
1   ATL  2020           34.000000            62.000000            7.000000
2   ATL  2020           31.000000            66.000000            6.000000
3   ATL  2020           30.000000            69.000000            5.000000
4   ATL  2020           30.750000            69.000000            4.750000
5   ATL  2020           30.400000            67.600000            4.600000
6   ATL  2020           30.500000            67.666667            5.500000
7   ATL  2020           30.285714            68.142857            5.857143
8   ATL  2020           30.250000            67.750000            6.500000
9   ATL  2020           29.888889            68.444444            6.666667
10  ATL  2020           30.100000            69.200000            6.800000
11  ATL  2020           29.400000            69.800000            6.300000
12  ATL  2020           30.400000            69.700000            6.600000
13  ATL  2020           30.900000            69.100000            7.100000
14  ATL  2020           30.800000            68.900000            7.300000

    rolling_10_team_3pa  rolling_10_team_ft  rolling_10_team_fta  \
0              0.000000            0.000000             0.000000
1             17.000000           30.000000            34.000000
2             22.500000           19.500000            24.000000
3             18.333333           21.333333            26.333333
4             16.500000           17.750000            21.750000
5             15.800000           16.600000            20.000000
6             17.666667           17.166667            20.000000
7             17.857143           16.000000            19.000000
8             17.875000           15.375000            18.625000
9             19.111111           13.777778            16.666667
10            19.200000           13.200000            16.600000
11            18.900000           11.300000            15.000000
12            17.900000           11.100000            14.800000
13            18.800000            9.700000            13.500000
14            19.200000            9.800000            13.900000

    rolling_10_team_orb  rolling_10_team_trb  rolling_10_team_ast  \
0              0.000000             0.000000             0.000000
1              4.000000            34.000000            19.000000
2              5.500000            29.500000            15.500000
3              9.333333            34.000000            14.000000
4              8.250000            32.000000            15.000000
5              7.600000            32.600000            15.000000
6              7.500000            33.333333            14.500000
7              8.000000            33.000000            14.285714
8              7.625000            32.750000            15.125000
9              7.888889            32.444444            15.444444
10             8.300000            32.700000            16.100000
11             8.700000            31.900000            15.300000
12             9.300000            32.900000            16.700000
13             8.300000            32.000000            18.300000
14             8.600000            32.600000            18.800000

    rolling_10_team_stl  rolling_10_team_blk  rolling_10_team_tov  \
0              0.000000             0.000000             0.000000
1              7.000000             4.000000            16.000000
2              9.500000             4.500000            16.000000
3              9.000000             3.666667            15.666667
4              8.250000             2.750000            14.750000
5              8.000000             2.600000            16.400000
6              7.833333             3.000000            16.500000
7              7.285714             3.571429            15.857143
8              6.750000             3.500000            16.250000
9              6.666667             3.333333            16.000000
10             6.500000             3.800000            15.600000
11             6.400000             3.600000            15.600000
12             5.700000             3.300000            15.400000
13             6.100000             3.200000            16.800000
14             6.300000             3.600000            17.000000

    rolling_10_team_pf  rolling_10_advanced_stl_pct
0             0.000000                     0.000000
1            21.000000                     8.000000
2            22.500000                    11.100000
3            21.666667                    10.633333
4            21.750000                     9.900000
5            22.400000                     9.620000
6            22.333333                     9.400000
7            21.000000                     8.828571
8            20.500000                     8.187500
9            19.555556                     8.144444
10           19.400000                     7.960000
11           18.600000                     7.900000
12           18.000000                     7.140000
13           18.700000                     7.440000
14           18.000000                     7.730000

<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (
<ipython-input-173-03cffa1132a1>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'rolling_10_{col}'] = (

In [175]:
df.rename(columns={'rolling_10_advanced_stl_pct': 'rolling_10_team_advanced_stl_pct'}, inplace=True)

In [177]:
# Only correct counting columns to create
counting_cols = [
    ('advanced_ortg', 'rolling_10_team_advanced_ortg'),
    ('advanced_drtg', 'rolling_10_team_advanced_drtg'),
    ('advanced_pace', 'rolling_10_team_advanced_pace')
]

for original_col, new_col in counting_cols:
    df[new_col] = (
        df.groupby(['team', 'year'])[original_col]
          .transform(lambda x: x.shift().rolling(window=10, min_periods=1).mean())
          .fillna(0)
    )

# Quick verification
print(df[['team', 'year', 'advanced_ortg', 'rolling_10_team_advanced_ortg',
          'advanced_drtg', 'rolling_10_team_advanced_drtg',
          'advanced_pace', 'rolling_10_team_advanced_pace']].head(15))

   team  year  advanced_ortg  rolling_10_team_advanced_ortg  advanced_drtg  \
0   ATL  2020          119.4                       0.000000          108.0
1   ATL  2020           83.0                     119.400000          118.6
2   ATL  2020          102.0                     101.200000           94.7
3   ATL  2020           98.4                     101.466667          118.9
4   ATL  2020           89.5                     100.700000           98.0
5   ATL  2020          108.4                      98.460000          109.6
6   ATL  2020          100.7                     100.116667          114.1
7   ATL  2020          102.4                     100.200000          116.1
8   ATL  2020           82.4                     100.475000          130.7
9   ATL  2020          100.9                      98.466667          121.1
10  ATL  2020           82.7                      98.710000          113.6
11  ATL  2020          119.4                      95.040000          128.6
12  ATL  2020           89.7                      98.680000           98.1
13  ATL  2020          103.7                      97.450000           99.8
14  ATL  2020           94.9                      97.980000          105.7

    rolling_10_team_advanced_drtg  advanced_pace  \
0                        0.000000           87.9
1                      108.000000           84.3
2                      113.300000           82.4
3                      107.100000           78.2
4                      110.050000           82.7
5                      107.640000           84.8
6                      107.966667           74.5
7                      108.842857           80.1
8                      109.750000           76.5
9                      112.077778           79.2
10                     112.980000           81.0
11                     113.540000           76.2
12                     114.540000           84.2
13                     114.880000           75.2
14                     112.970000           83.2

    rolling_10_team_advanced_pace
0                        0.000000
1                       87.900000
2                       86.100000
3                       84.866667
4                       83.200000
5                       83.100000
6                       83.383333
7                       82.114286
8                       81.862500
9                       81.266667
10                      81.060000
11                      80.370000
12                      79.560000
13                      79.740000
14                      79.440000

<ipython-input-177-fd28489a7d10>:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-177-fd28489a7d10>:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-177-fd28489a7d10>:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (

In [180]:
cols_to_create = [
    'rolling_10_team_fg',
    'rolling_10_team_fga',
    'rolling_10_team_3p',
    'rolling_10_team_3pa',
    'rolling_10_team_ft',
    'rolling_10_team_fta',
    'rolling_10_team_orb',
    'rolling_10_team_trb',
    'rolling_10_team_ast',
    'rolling_10_team_stl',
    'rolling_10_team_blk',
    'rolling_10_team_tov',
    'rolling_10_team_pf',
    'rolling_10_team_advanced_stl_pct',
    'rolling_10_team_advanced_ortg',
    'rolling_10_team_advanced_drtg',
    'rolling_10_team_advanced_pace',
    'rolling_10_team_fg_pct',
    'rolling_10_team_3p_pct',
    'rolling_10_team_ft_pct',
    'rolling_10_team_offensive_efg_pct',
    'rolling_10_team_offensive_tov_pct'
]

for col in cols_to_create:
    opp_col = col.replace('rolling_10_team_', 'rolling_10_opp_')

    def get_rolling_10_opp(row):
        opp_data = df[
            (df['team'] == row['opp']) &
            (
                (df['year'] < row['year']) |
                ((df['year'] == row['year']) & (df['month'] < row['month'])) |
                ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
            )
        ]
        return opp_data[col].iloc[-1] if not opp_data.empty else 0

    df[opp_col] = df.apply(get_rolling_10_opp, axis=1)

# Quick verification
print(df[['team', 'opp', 'year', 'month', 'day'] + [col.replace('rolling_10_team_', 'rolling_10_opp_') for col in cols_to_create]].head(10))

<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)
<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)

  team  opp  year  month   day  rolling_10_opp_fg  rolling_10_opp_fga  \
0  ATL  DAL  2020    7.0  26.0           0.000000            0.000000
1  ATL  LVA  2020    7.0  29.0           0.000000            0.000000
2  ATL  NYL  2020    7.0  31.0          23.000000           66.000000
3  ATL  IND  2020    8.0   2.0          32.000000           70.500000
4  ATL  PHO  2020    8.0   4.0          33.000000           65.333333
5  ATL  SEA  2020    8.0   6.0          31.500000           67.750000
6  ATL  DAL  2020    8.0   8.0          30.600000           74.400000
7  ATL  CON  2020    8.0  10.0          27.833333           67.166667
8  ATL  SEA  2020    8.0  12.0          30.428571           67.714286
9  ATL  PHO  2020    8.0  14.0          31.375000           67.250000

   rolling_10_opp_3p  rolling_10_opp_3pa  rolling_10_opp_ft  ...  \
0           0.000000            0.000000           0.000000  ...
1           0.000000            0.000000           0.000000  ...
2           6.000000           28.000000          19.000000  ...
3           8.500000           23.000000          18.500000  ...
4           9.666667           23.333333          17.000000  ...
5           7.750000           24.000000          11.500000  ...
6           8.000000           26.800000          13.400000  ...
7           5.666667           19.833333          16.666667  ...
8           8.571429           23.142857          13.857143  ...
9           7.250000           21.250000          18.750000  ...

   rolling_10_opp_pf  rolling_10_opp_advanced_stl_pct  \
0           0.000000                         0.000000
1           0.000000                         0.000000
2          15.000000                         5.700000
3          22.000000                         5.450000
4          23.000000                         7.933333
5          18.000000                        11.850000
6          20.800000                        10.960000
7          19.500000                        11.366667
8          17.714286                        12.671429
9          21.000000                         8.875000

   rolling_10_opp_advanced_ortg  rolling_10_opp_advanced_drtg  \
0                      0.000000                      0.000000
1                      0.000000                      0.000000
2                     81.400000                     99.800000
3                    111.050000                    122.550000
4                    110.833333                    119.600000
5                    104.850000                     95.900000
6                    102.740000                    104.060000
7                     96.333333                     99.966667
8                    105.385714                     96.528571
9                    106.887500                    102.362500

   rolling_10_opp_advanced_pace  rolling_10_opp_fg_pct  rolling_10_opp_3p_pct  \
0                      0.000000               0.000000               0.000000
1                      0.000000               0.000000               0.000000
2                     87.200000               0.348485               0.214286
3                     82.000000               0.453901               0.369565
4                     83.700000               0.505102               0.414286
5                     78.875000               0.464945               0.322917
6                     80.260000               0.411290               0.298507
7                     80.983333               0.414392               0.285714
8                     79.357143               0.449367               0.370370
9                     83.012500               0.466543               0.341176

   rolling_10_opp_ft_pct  rolling_10_opp_offensive_efg_pct  \
0               0.000000                          0.000000
1               0.000000                          0.000000
2               0.863636                          0.393939
3               0.880952                          0.514184
4               0.698630                          0.579082
5               0.741935                          0.522140
6               0.761364                          0.465054
7               0.709220                          0.456576
8               0.788618                          0.512658
9               0.797872                          0.520446

   rolling_10_opp_offensive_tov_pct
0                          0.000000
1                          0.000000
2                          0.200676
3                          0.135516
4                          0.173837
5                          0.162793
6                          0.112379
7                          0.159120
8                          0.155170
9                          0.163134

[10 rows x 27 columns]

<ipython-input-180-b5f2753d9571>:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[opp_col] = df.apply(get_rolling_10_opp, axis=1)

In [185]:
# Calculate rolling 10 game percentages and advanced metrics
df['rolling_10_team_fg_pct'] = (
    df['rolling_10_team_fg'] / df['rolling_10_team_fga']
).fillna(0)

df['rolling_10_team_3p_pct'] = (
    df['rolling_10_team_3p'] / df['rolling_10_team_3pa']
).fillna(0)

df['rolling_10_team_ft_pct'] = (
    df['rolling_10_team_ft'] / df['rolling_10_team_fta']
).fillna(0)

df['rolling_10_team_offensive_efg_pct'] = (
    (df['rolling_10_team_fg'] + 0.5 * df['rolling_10_team_3p']) / df['rolling_10_team_fga']
).fillna(0)

df['rolling_10_team_offensive_tov_pct'] = (
    df['rolling_10_team_tov'] /
    (df['rolling_10_team_fga'] + 0.44 * df['rolling_10_team_fta'] + df['rolling_10_team_tov'])
).fillna(0)

df['rolling_10_team_offensive_orb_pct'] = (
    df['rolling_10_team_orb'] /
    (df['rolling_10_team_orb'] + df['rolling_10_opp_trb'] - df['rolling_10_opp_orb'])
).fillna(0)

df['rolling_10_team_defensive_efg_pct'] = (
    (df['rolling_10_opp_fg'] + 0.5 * df['rolling_10_opp_3p']) / df['rolling_10_opp_fga']
).fillna(0)

df['rolling_10_team_defensive_tov_pct'] = (
    df['rolling_10_opp_tov'] /
    (df['rolling_10_opp_fga'] + 0.44 * df['rolling_10_opp_fta'] + df['rolling_10_opp_tov'])
).fillna(0)

df['rolling_10_team_defensive_drb_pct'] = (
    (df['rolling_10_team_trb'] - df['rolling_10_team_orb']) /
    (df['rolling_10_team_trb'] - df['rolling_10_team_orb'] + df['rolling_10_opp_orb'])
).fillna(0)

df['rolling_10_team_advanced_ts_pct'] = (
    df['rolling_10_team_score_mean'] / (2 * (df['rolling_10_team_fga'] + 0.44 * df['rolling_10_team_fta']))
).fillna(0)

df['rolling_10_team_advanced_trb_pct'] = (
    df['rolling_10_team_trb'] / (df['rolling_10_team_trb'] + df['rolling_10_opp_trb'])
).fillna(0)

df['rolling_10_team_advanced_ast_pct'] = (
    df['rolling_10_team_ast'] / df['rolling_10_team_fg']
).fillna(0)

df['rolling_10_team_advanced_blk_pct'] = (
    df['rolling_10_team_blk'] / df['rolling_10_opp_fga']
).fillna(0)

df['rolling_10_team_advanced_ftr'] = (
    df['rolling_10_team_fta'] / df['rolling_10_team_fga']
).fillna(0)

df['rolling_10_team_advanced_3par'] = (
    df['rolling_10_team_3pa'] / df['rolling_10_team_fga']
).fillna(0)

# Quick verification
cols = [
    'team', 'year', 'rolling_10_team_fg_pct', 'rolling_10_team_3p_pct',
    'rolling_10_team_ft_pct', 'rolling_10_team_offensive_efg_pct',
    'rolling_10_team_defensive_efg_pct', 'rolling_10_team_advanced_ts_pct'
]
print(df[cols].head(15))

   team  year  rolling_10_team_fg_pct  rolling_10_team_3p_pct  \
0   ATL  2020                0.000000                0.000000
1   ATL  2020                0.548387                0.411765
2   ATL  2020                0.469697                0.266667
3   ATL  2020                0.434783                0.272727
4   ATL  2020                0.445652                0.287879
5   ATL  2020                0.449704                0.291139
6   ATL  2020                0.450739                0.311321
7   ATL  2020                0.444444                0.328000
8   ATL  2020                0.446494                0.363636
9   ATL  2020                0.436688                0.348837
10  ATL  2020                0.434971                0.354167
11  ATL  2020                0.421203                0.333333
12  ATL  2020                0.436155                0.368715
13  ATL  2020                0.447178                0.377660
14  ATL  2020                0.447025                0.380208

    rolling_10_team_ft_pct  rolling_10_team_offensive_efg_pct  \
0                 0.000000                           0.000000
1                 0.882353                           0.604839
2                 0.812500                           0.515152
3                 0.810127                           0.471014
4                 0.816092                           0.480072
5                 0.830000                           0.483728
6                 0.858333                           0.491379
7                 0.842105                           0.487421
8                 0.825503                           0.494465
9                 0.826667                           0.485390
10                0.795181                           0.484104
11                0.753333                           0.466332
12                0.750000                           0.483501
13                0.718519                           0.498553
14                0.705036                           0.500000

    rolling_10_team_defensive_efg_pct  rolling_10_team_advanced_ts_pct
0                            0.000000                         0.000000
1                            0.000000                         0.682173
2                            0.393939                         0.571447
3                            0.514184                         0.535655
4                            0.579082                         0.534555
5                            0.522140                         0.536649
6                            0.465054                         0.547079
7                            0.456576                         0.538729
8                            0.512658                         0.542333
9                            0.520446                         0.529326
10                           0.548520                         0.524156
11                           0.478793                         0.500000
12                           0.544444                         0.515011
13                           0.509202                         0.523721
14                           0.523148                         0.524555

<ipython-input-185-dd314c62010e>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_fg_pct'] = (
<ipython-input-185-dd314c62010e>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_3p_pct'] = (
<ipython-input-185-dd314c62010e>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_ft_pct'] = (
<ipython-input-185-dd314c62010e>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_offensive_efg_pct'] = (
<ipython-input-185-dd314c62010e>:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_offensive_tov_pct'] = (
<ipython-input-185-dd314c62010e>:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_offensive_orb_pct'] = (
<ipython-input-185-dd314c62010e>:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_defensive_efg_pct'] = (
<ipython-input-185-dd314c62010e>:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_defensive_tov_pct'] = (
<ipython-input-185-dd314c62010e>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_defensive_drb_pct'] = (
<ipython-input-185-dd314c62010e>:42: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_advanced_ts_pct'] = (
<ipython-input-185-dd314c62010e>:46: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_advanced_trb_pct'] = (
<ipython-input-185-dd314c62010e>:50: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_advanced_ast_pct'] = (
<ipython-input-185-dd314c62010e>:54: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_advanced_blk_pct'] = (
<ipython-input-185-dd314c62010e>:58: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_advanced_ftr'] = (
<ipython-input-185-dd314c62010e>:62: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_advanced_3par'] = (

In [187]:
# List of columns for which we need opp-side rolling features
cols_team_to_opp = [
    'rolling_10_team_fg_pct',
    'rolling_10_team_3p_pct',
    'rolling_10_team_ft_pct',
    'rolling_10_team_offensive_efg_pct',
    'rolling_10_team_offensive_tov_pct',
    'rolling_10_team_offensive_orb_pct',
    'rolling_10_team_defensive_efg_pct',
    'rolling_10_team_defensive_tov_pct',
    'rolling_10_team_defensive_drb_pct',
    'rolling_10_team_advanced_ts_pct',
    'rolling_10_team_advanced_trb_pct',
    'rolling_10_team_advanced_ast_pct',
    'rolling_10_team_advanced_blk_pct',
    'rolling_10_team_advanced_ftr',
    'rolling_10_team_advanced_3par'
]

# Create rolling_10_opp_ versions
for col in cols_team_to_opp:
    new_col = col.replace('rolling_10_team_', 'rolling_10_opp_')

    def get_opp_rolling_10(row):
        # Get opponent previous games data
        opp_data = df[
            (df['team'] == row['opp']) &
            (
                (df['year'] < row['year']) |
                ((df['year'] == row['year']) & (df['month'] < row['month'])) |
                ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
            )
        ]
        # Return the most recent rolling value or 0 if none
        return opp_data[col].iloc[-1] if not opp_data.empty else 0

    df[new_col] = df.apply(get_opp_rolling_10, axis=1)

# Quick verification
print(df[['team', 'opp', 'year', 'month', 'day'] + [c.replace('rolling_10_team_', 'rolling_10_opp_') for c in cols_team_to_opp]].head(10))

<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)
<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)

  team  opp  year  month   day  rolling_10_opp_fg_pct  rolling_10_opp_3p_pct  \
0  ATL  DAL  2020    7.0  26.0               0.000000               0.000000
1  ATL  LVA  2020    7.0  29.0               0.000000               0.000000
2  ATL  NYL  2020    7.0  31.0               0.348485               0.214286
3  ATL  IND  2020    8.0   2.0               0.453901               0.369565
4  ATL  PHO  2020    8.0   4.0               0.505102               0.414286
5  ATL  SEA  2020    8.0   6.0               0.464945               0.322917
6  ATL  DAL  2020    8.0   8.0               0.411290               0.298507
7  ATL  CON  2020    8.0  10.0               0.414392               0.285714
8  ATL  SEA  2020    8.0  12.0               0.449367               0.370370
9  ATL  PHO  2020    8.0  14.0               0.466543               0.341176

   rolling_10_opp_ft_pct  rolling_10_opp_offensive_efg_pct  \
0               0.000000                          0.000000
1               0.000000                          0.000000
2               0.863636                          0.393939
3               0.880952                          0.514184
4               0.698630                          0.579082
5               0.741935                          0.522140
6               0.761364                          0.465054
7               0.709220                          0.456576
8               0.788618                          0.512658
9               0.797872                          0.520446

   rolling_10_opp_offensive_tov_pct  rolling_10_opp_offensive_orb_pct  \
0                          0.000000                          0.000000
1                          0.000000                          0.000000
2                          0.200676                          1.000000
3                          0.135516                          0.263158
4                          0.173837                          0.174672
5                          0.162793                          0.205298
6                          0.112379                          0.256480
7                          0.159120                          0.226667
8                          0.155170                          0.220147
9                          0.163134                          0.211679

   rolling_10_opp_defensive_efg_pct  rolling_10_opp_defensive_tov_pct  \
0                          0.000000                          0.000000
1                          0.000000                          0.000000
2                          0.000000                          0.000000
3                          0.519231                          0.130261
4                          0.442446                          0.193758
5                          0.419512                          0.152926
6                          0.417910                          0.159033
7                          0.552857                          0.165504
8                          0.547619                          0.171158
9                          0.555439                          0.179050

   rolling_10_opp_defensive_drb_pct  rolling_10_opp_advanced_ts_pct  \
0                          0.000000                        0.000000
1                          0.000000                        0.000000
2                          1.000000                        0.469080
3                          0.761194                        0.570604
4                          0.724490                        0.609328
5                          0.748252                        0.551495
6                          0.726135                        0.502776
7                          0.796813                        0.503183
8                          0.777931                        0.551958
9                          0.776959                        0.571916

   rolling_10_opp_advanced_trb_pct  rolling_10_opp_advanced_ast_pct  \
0                         0.000000                         0.000000
1                         0.000000                         0.000000
2                         1.000000                         0.608696
3                         0.532258                         0.453125
4                         0.428235                         0.717172
5                         0.469388                         0.603175
6                         0.475219                         0.450980
7                         0.495538                         0.622754
8                         0.494405                         0.624413
9                         0.493061                         0.677291

   rolling_10_opp_advanced_blk_pct  rolling_10_opp_advanced_ftr  \
0                         0.000000                     0.000000
1                         0.000000                     0.000000
2                              inf                     0.333333
3                         0.025641                     0.297872
4                         0.067146                     0.372449
5                         0.051220                     0.228782
6                         0.065672                     0.236559
7                         0.033333                     0.349876
8                         0.057143                     0.259494
9                         0.076883                     0.349442

   rolling_10_opp_advanced_3par
0                      0.000000
1                      0.000000
2                      0.424242
3                      0.326241
4                      0.357143
5                      0.354244
6                      0.360215
7                      0.295285
8                      0.341772
9                      0.315985

<ipython-input-187-0810c3f34574>:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(get_opp_rolling_10, axis=1)

In [189]:
# fix redundant '_opp_' in allowed columns
rename_dict = {
    'ytd_team_allowed_opp_fga_per_game': 'ytd_team_allowed_fga_per_game',
    'ytd_team_allowed_opp_3p_per_game': 'ytd_team_allowed_3p_per_game',
    'ytd_team_allowed_opp_3pa_per_game': 'ytd_team_allowed_3pa_per_game',
    'ytd_team_allowed_opp_ft_per_game': 'ytd_team_allowed_ft_per_game',
    'ytd_team_allowed_opp_fta_per_game': 'ytd_team_allowed_fta_per_game',
    'ytd_team_allowed_opp_orb_per_game': 'ytd_team_allowed_orb_per_game',
    'ytd_team_allowed_opp_trb_per_game': 'ytd_team_allowed_trb_per_game',
    'ytd_team_allowed_opp_ast_per_game': 'ytd_team_allowed_ast_per_game',
    'ytd_team_allowed_opp_stl_per_game': 'ytd_team_allowed_stl_per_game',
    'ytd_team_allowed_opp_blk_per_game': 'ytd_team_allowed_blk_per_game',
    'ytd_team_allowed_opp_tov_per_game': 'ytd_team_allowed_tov_per_game',
    'ytd_team_allowed_opp_pf_per_game': 'ytd_team_allowed_pf_per_game',
    'ytd_opp_allowed_opp_fga_per_game': 'ytd_opp_allowed_fga_per_game',
    'ytd_opp_allowed_opp_3p_per_game': 'ytd_opp_allowed_3p_per_game',
    'ytd_opp_allowed_opp_3pa_per_game': 'ytd_opp_allowed_3pa_per_game',
    'ytd_opp_allowed_opp_ft_per_game': 'ytd_opp_allowed_ft_per_game',
    'ytd_opp_allowed_opp_fta_per_game': 'ytd_opp_allowed_fta_per_game',
    'ytd_opp_allowed_opp_orb_per_game': 'ytd_opp_allowed_orb_per_game',
    'ytd_opp_allowed_opp_trb_per_game': 'ytd_opp_allowed_trb_per_game',
    'ytd_opp_allowed_opp_ast_per_game': 'ytd_opp_allowed_ast_per_game',
    'ytd_opp_allowed_opp_stl_per_game': 'ytd_opp_allowed_stl_per_game',
    'ytd_opp_allowed_opp_blk_per_game': 'ytd_opp_allowed_blk_per_game',
    'ytd_opp_allowed_opp_tov_per_game': 'ytd_opp_allowed_tov_per_game',
    'ytd_opp_allowed_opp_pf_per_game': 'ytd_opp_allowed_pf_per_game'
}

df.rename(columns=rename_dict, inplace=True)

In [191]:
# Counting columns to create rolling-10 allowed
counting_cols = [
    'opp_fg', 'opp_fga', 'opp_3p', 'opp_3pa', 'opp_ft', 'opp_fta',
    'opp_orb', 'opp_trb', 'opp_ast', 'opp_stl', 'opp_blk',
    'opp_tov', 'opp_pf', 'advanced_stl_pct'
]

# Create rolling-10 allowed columns (fixing naming redundancy)
for col in counting_cols:
    clean_col = col.replace('opp_', '') if col.startswith('opp_') else col
    new_col = f'rolling_10_team_allowed_{clean_col}_per_game'
    df[new_col] = (
        df.groupby(['team', 'year'])[col]
          .transform(lambda x: x.shift().rolling(window=10, min_periods=1).mean())
          .fillna(0)
    )

# Quick verification on one team
print(df[df['team'] == 'ATL'][[
    'team', 'year', 'opp_fg', 'rolling_10_team_allowed_fg_per_game',
    'opp_ast', 'rolling_10_team_allowed_ast_per_game',
    'advanced_stl_pct', 'rolling_10_team_allowed_advanced_stl_pct_per_game'
]].head(15))

<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (
<ipython-input-191-5304e9ce6bed>:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = (

   team  year  opp_fg  rolling_10_team_allowed_fg_per_game  opp_ast  \
0   ATL  2020      34                             0.000000       18
1   ATL  2020      38                            34.000000       16
2   ATL  2020      28                            36.000000       13
3   ATL  2020      34                            33.333333       26
4   ATL  2020      29                            33.500000       19
5   ATL  2020      31                            32.600000       21
6   ATL  2020      31                            32.333333       17
7   ATL  2020      36                            32.142857       19
8   ATL  2020      35                            32.625000       31
9   ATL  2020      32                            32.888889       24
10  ATL  2020      37                            32.800000       25
11  ATL  2020      35                            33.100000       27
12  ATL  2020      30                            32.800000       21
13  ATL  2020      29                            33.000000       16
14  ATL  2020      29                            32.500000       22

    rolling_10_team_allowed_ast_per_game  advanced_stl_pct  \
0                               0.000000               8.0
1                              18.000000              14.2
2                              17.000000               9.7
3                              15.666667               7.7
4                              18.250000               8.5
5                              18.400000               8.3
6                              18.833333               5.4
7                              18.571429               3.7
8                              18.625000               7.8
9                              20.000000               6.3
10                             20.400000               7.4
11                             21.100000               6.6
12                             22.200000              12.7
13                             23.000000              10.6
14                             22.000000               6.0

    rolling_10_team_allowed_advanced_stl_pct_per_game
0                                            0.000000
1                                            8.000000
2                                           11.100000
3                                           10.633333
4                                            9.900000
5                                            9.620000
6                                            9.400000
7                                            8.828571
8                                            8.187500
9                                            8.144444
10                                           7.960000
11                                           7.900000
12                                           7.140000
13                                           7.440000
14                                           7.730000

In [193]:
# rolling-10 allowed percentage columns
df['rolling_10_team_allowed_fg_pct'] = (
    df['rolling_10_team_allowed_fg_per_game'] / df['rolling_10_team_allowed_fga_per_game']
).fillna(0)

df['rolling_10_team_allowed_3p_pct'] = (
    df['rolling_10_team_allowed_3p_per_game'] / df['rolling_10_team_allowed_3pa_per_game']
).fillna(0)

df['rolling_10_team_allowed_ft_pct'] = (
    df['rolling_10_team_allowed_ft_per_game'] / df['rolling_10_team_allowed_fta_per_game']
).fillna(0)

df['rolling_10_team_allowed_advanced_ts_pct'] = (
    df['rolling_10_team_allowed_fg_per_game'] /
    (2 * (df['rolling_10_team_allowed_fga_per_game'] + 0.44 * df['rolling_10_team_allowed_fta_per_game']))
).fillna(0)

df['rolling_10_team_allowed_offensive_efg_pct'] = (
    (df['rolling_10_team_allowed_fg_per_game'] + 0.5 * df['rolling_10_team_allowed_3p_per_game']) /
    df['rolling_10_team_allowed_fga_per_game']
).fillna(0)

df['rolling_10_team_allowed_offensive_tov_pct'] = (
    df['rolling_10_team_allowed_tov_per_game'] /
    (df['rolling_10_team_allowed_fga_per_game'] + 0.44 * df['rolling_10_team_allowed_fta_per_game'] + df['rolling_10_team_allowed_tov_per_game'])
).fillna(0)

df['rolling_10_team_allowed_offensive_orb_pct'] = (
    df['rolling_10_team_allowed_orb_per_game'] /
    (df['rolling_10_team_allowed_orb_per_game'] + df['rolling_10_team_trb'] - df['rolling_10_team_orb'])
).fillna(0)

df['rolling_10_team_allowed_defensive_efg_pct'] = (
    (df['rolling_10_team_fg'] + 0.5 * df['rolling_10_team_3p']) / df['rolling_10_team_fga']
).fillna(0)

df['rolling_10_team_allowed_defensive_tov_pct'] = (
    df['rolling_10_team_tov'] /
    (df['rolling_10_team_fga'] + 0.44 * df['rolling_10_team_fta'] + df['rolling_10_team_tov'])
).fillna(0)

df['rolling_10_team_allowed_defensive_drb_pct'] = (
    (df['rolling_10_team_allowed_trb_per_game'] - df['rolling_10_team_allowed_orb_per_game']) /
    (df['rolling_10_team_allowed_trb_per_game'] - df['rolling_10_team_allowed_orb_per_game'] + df['rolling_10_team_orb'])
).fillna(0)

# Quick verification
print(df[df['team'] == 'ATL'][[
    'team', 'year',
    'rolling_10_team_allowed_fg_pct', 'rolling_10_team_allowed_3p_pct',
    'rolling_10_team_allowed_ft_pct', 'rolling_10_team_allowed_offensive_efg_pct',
    'rolling_10_team_allowed_offensive_tov_pct', 'rolling_10_team_allowed_offensive_orb_pct'
]].head(15))

   team  year  rolling_10_team_allowed_fg_pct  rolling_10_team_allowed_3p_pct  \
0   ATL  2020                        0.000000                        0.000000
1   ATL  2020                        0.435897                        0.464286
2   ATL  2020                        0.483221                        0.513514
3   ATL  2020                        0.452489                        0.393939
4   ATL  2020                        0.466899                        0.395349
5   ATL  2020                        0.450276                        0.358491
6   ATL  2020                        0.445977                        0.346457
7   ATL  2020                        0.448207                        0.355263
8   ATL  2020                        0.450777                        0.357955
9   ATL  2020                        0.461778                        0.393204
10  ATL  2020                        0.464589                        0.402597
11  ATL  2020                        0.478324                        0.400922
12  ATL  2020                        0.474674                        0.384298
13  ATL  2020                        0.481050                        0.406926
14  ATL  2020                        0.471014                        0.389831

    rolling_10_team_allowed_ft_pct  rolling_10_team_allowed_offensive_efg_pct  \
0                         0.000000                                   0.000000
1                         0.700000                                   0.519231
2                         0.695652                                   0.546980
3                         0.746032                                   0.511312
4                         0.761905                                   0.526132
5                         0.783019                                   0.502762
6                         0.812030                                   0.496552
7                         0.817568                                   0.501992
8                         0.791667                                   0.505181
9                         0.801105                                   0.524961
10                        0.808824                                   0.530453
11                        0.826531                                   0.541185
12                        0.842105                                   0.541968
13                        0.837438                                   0.549563
14                        0.845361                                   0.537681

    rolling_10_team_allowed_offensive_tov_pct  \
0                                    0.000000
1                                    0.130261
2                                    0.159014
3                                    0.158934
4                                    0.160638
5                                    0.149800
6                                    0.143967
7                                    0.144770
8                                    0.137399
9                                    0.138650
10                                   0.136695
11                                   0.143134
12                                   0.136070
13                                   0.141700
14                                   0.139789

    rolling_10_team_allowed_offensive_orb_pct
0                                    0.000000
1                                    0.210526
2                                    0.314286
3                                    0.288462
4                                    0.291045
5                                    0.281609
6                                    0.268868
7                                    0.276860
8                                    0.289753
9                                    0.275410
10                                   0.265060
11                                   0.268139
12                                   0.253165
13                                   0.250000
14                                   0.250000

<ipython-input-193-9aebc02c5d93>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_allowed_fg_pct'] = (
<ipython-input-193-9aebc02c5d93>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_allowed_3p_pct'] = (
<ipython-input-193-9aebc02c5d93>:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_allowed_ft_pct'] = (
<ipython-input-193-9aebc02c5d93>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_allowed_advanced_ts_pct'] = (
<ipython-input-193-9aebc02c5d93>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_allowed_offensive_efg_pct'] = (
<ipython-input-193-9aebc02c5d93>:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_allowed_offensive_tov_pct'] = (
<ipython-input-193-9aebc02c5d93>:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_allowed_offensive_orb_pct'] = (
<ipython-input-193-9aebc02c5d93>:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_allowed_defensive_efg_pct'] = (
<ipython-input-193-9aebc02c5d93>:38: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_allowed_defensive_tov_pct'] = (
<ipython-input-193-9aebc02c5d93>:43: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['rolling_10_team_allowed_defensive_drb_pct'] = (

In [195]:
# get list of rolling-10 team allowed columns
allowed_cols = [col for col in df.columns if col.startswith('rolling_10_team_allowed_')]

# loop to create rolling-10 opp allowed columns
for col in allowed_cols:
    new_col = col.replace('rolling_10_team_allowed_', 'rolling_10_opp_allowed_')

    def map_team_to_opp(row):
        opp_data = df[
            (df['team'] == row['opp']) &
            (
                (df['year'] < row['year']) |
                ((df['year'] == row['year']) & (df['month'] < row['month'])) |
                ((df['year'] == row['year']) & (df['month'] == row['month']) & (df['day'] < row['day']))
            )
        ]
        return opp_data[col].iloc[-1] if not opp_data.empty else 0

    df[new_col] = df.apply(map_team_to_opp, axis=1)

# Quick verification
print(df[['team', 'opp', 'year', 'month', 'day'] + [c.replace('rolling_10_team_allowed_', 'rolling_10_opp_allowed_') for c in allowed_cols]].head(15))

<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)
<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)

   team  opp  year  month   day  rolling_10_opp_allowed_fg_per_game  \
0   ATL  DAL  2020    7.0  26.0                            0.000000
1   ATL  LVA  2020    7.0  29.0                            0.000000
2   ATL  NYL  2020    7.0  31.0                           34.000000
3   ATL  IND  2020    8.0   2.0                           36.000000
4   ATL  PHO  2020    8.0   4.0                           35.333333
5   ATL  SEA  2020    8.0   6.0                           26.500000
6   ATL  DAL  2020    8.0   8.0                           30.000000
7   ATL  CON  2020    8.0  10.0                           30.000000
8   ATL  SEA  2020    8.0  12.0                           27.285714
9   ATL  PHO  2020    8.0  14.0                           29.750000
10  ATL  CHI  2020    8.0  16.0                           31.777778
11  ATL  WAS  2020    8.0  19.0                           28.444444
12  ATL  LAS  2020    8.0  21.0                           28.000000
13  ATL  MIN  2020    8.0  23.0                           27.900000
14  ATL  MIN  2020    8.0  28.0                           26.900000

    rolling_10_opp_allowed_fga_per_game  rolling_10_opp_allowed_3p_per_game  \
0                              0.000000                            0.000000
1                              0.000000                            0.000000
2                             77.000000                            7.000000
3                             68.500000                            8.000000
4                             69.333333                            8.333333
5                             69.750000                            8.250000
6                             67.600000                            6.600000
7                             68.500000                            6.833333
8                             68.857143                            7.714286
9                             69.000000                            7.750000
10                            68.444444                            7.111111
11                            63.888889                            7.555556
12                            63.700000                            7.600000
13                            64.900000                            7.700000
14                            64.300000                            7.300000

    rolling_10_opp_allowed_3pa_per_game  rolling_10_opp_allowed_ft_per_game  \
0                              0.000000                            0.000000
1                              0.000000                            0.000000
2                             23.000000                           12.000000
3                             19.500000                           20.500000
4                             18.000000                           21.000000
5                             25.500000                           14.000000
6                             19.000000                           17.200000
7                             21.166667                           14.000000
8                             24.857143                           14.142857
9                             22.000000                           17.750000
10                            17.888889                           13.888889
11                            21.333333                           15.666667
12                            21.100000                           15.300000
13                            22.500000                           13.100000
14                            22.800000                           14.500000

    ...  rolling_10_opp_allowed_fg_pct  rolling_10_opp_allowed_3p_pct  \
0   ...                       0.000000                       0.000000
1   ...                       0.000000                       0.000000
2   ...                       0.441558                       0.304348
3   ...                       0.525547                       0.410256
4   ...                       0.509615                       0.462963
5   ...                       0.379928                       0.323529
6   ...                       0.443787                       0.347368
7   ...                       0.437956                       0.322835
8   ...                       0.396266                       0.310345
9   ...                       0.431159                       0.352273
10  ...                       0.464286                       0.397516
11  ...                       0.445217                       0.354167
12  ...                       0.439560                       0.360190
13  ...                       0.429892                       0.342222
14  ...                       0.418351                       0.320175

    rolling_10_opp_allowed_ft_pct  rolling_10_opp_allowed_advanced_ts_pct  \
0                        0.000000                                0.000000
1                        0.000000                                0.000000
2                        0.800000                                0.203349
3                        0.773585                                0.224551
4                        0.875000                                0.221128
5                        0.861538                                0.172302
6                        0.826923                                0.195435
7                        0.763636                                0.195908
8                        0.860870                                0.179309
9                        0.850299                                0.190254
10                       0.748503                                0.207403
11                       0.762162                                0.195003
12                       0.788660                                0.193809
13                       0.779762                                0.192967
14                       0.788043                                0.185784

    rolling_10_opp_allowed_offensive_efg_pct  \
0                                   0.000000
1                                   0.000000
2                                   0.487013
3                                   0.583942
4                                   0.569712
5                                   0.439068
6                                   0.492604
7                                   0.487835
8                                   0.452282
9                                   0.487319
10                                  0.516234
11                                  0.504348
12                                  0.499215
13                                  0.489214
14                                  0.475117

    rolling_10_opp_allowed_offensive_tov_pct  \
0                                   0.000000
1                                   0.000000
2                                   0.134576
3                                   0.115817
4                                   0.133728
5                                   0.163221
6                                   0.172503
7                                   0.159224
8                                   0.169888
9                                   0.159843
10                                  0.167777
11                                  0.174755
12                                  0.204765
13                                  0.176554
14                                  0.180076

    rolling_10_opp_allowed_offensive_orb_pct  \
0                                   0.000000
1                                   0.000000
2                                   0.200000
3                                   0.227273
4                                   0.219780
5                                   0.277027
6                                   0.296970
7                                   0.227053
8                                   0.256917
9                                   0.232727
10                                  0.221122
11                                  0.227723
12                                  0.240625
13                                  0.261261
14                                  0.256716

    rolling_10_opp_allowed_defensive_efg_pct  \
0                                   0.000000
1                                   0.000000
2                                   0.393939
3                                   0.514184
4                                   0.579082
5                                   0.522140
6                                   0.465054
7                                   0.456576
8                                   0.512658
9                                   0.520446
10                                  0.548520
11                                  0.478793
12                                  0.544444
13                                  0.509202
14                                  0.523148

    rolling_10_opp_allowed_defensive_tov_pct  \
0                                   0.000000
1                                   0.000000
2                                   0.200676
3                                   0.135516
4                                   0.173837
5                                   0.162793
6                                   0.112379
7                                   0.159120
8                                   0.155170
9                                   0.163134
10                                  0.183815
11                                  0.151084
12                                  0.163626
13                                  0.172940
14                                  0.167861

    rolling_10_opp_allowed_defensive_drb_pct
0                                   0.000000
1                                   0.000000
2                                   0.864865
3                                   0.782609
4                                   0.797980
5                                   0.768657
6                                   0.761421
7                                   0.763889
8                                   0.767932
9                                   0.785978
10                                  0.745520
11                                  0.804348
12                                  0.814815
13                                  0.675079
14                                  0.696203

[15 rows x 29 columns]

<ipython-input-195-81a14a453263>:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[new_col] = df.apply(map_team_to_opp, axis=1)

In [198]:
# Dictionary for renaming rolling averages clearly to include '_per_game'
rename_dict = {
    'rolling_10_team_fg': 'rolling_10_team_fg_per_game',
    'rolling_10_team_fga': 'rolling_10_team_fga_per_game',
    'rolling_10_team_3p': 'rolling_10_team_3p_per_game',
    'rolling_10_team_3pa': 'rolling_10_team_3pa_per_game',
    'rolling_10_team_ft': 'rolling_10_team_ft_per_game',
    'rolling_10_team_fta': 'rolling_10_team_fta_per_game',
    'rolling_10_team_orb': 'rolling_10_team_orb_per_game',
    'rolling_10_team_trb': 'rolling_10_team_trb_per_game',
    'rolling_10_team_ast': 'rolling_10_team_ast_per_game',
    'rolling_10_team_stl': 'rolling_10_team_stl_per_game',
    'rolling_10_team_blk': 'rolling_10_team_blk_per_game',
    'rolling_10_team_tov': 'rolling_10_team_tov_per_game',
    'rolling_10_team_pf': 'rolling_10_team_pf_per_game',
    'rolling_10_opp_fg': 'rolling_10_opp_fg_per_game',
    'rolling_10_opp_fga': 'rolling_10_opp_fga_per_game',
    'rolling_10_opp_3p': 'rolling_10_opp_3p_per_game',
    'rolling_10_opp_3pa': 'rolling_10_opp_3pa_per_game',
    'rolling_10_opp_ft': 'rolling_10_opp_ft_per_game',
    'rolling_10_opp_fta': 'rolling_10_opp_fta_per_game',
    'rolling_10_opp_orb': 'rolling_10_opp_orb_per_game',
    'rolling_10_opp_trb': 'rolling_10_opp_trb_per_game',
    'rolling_10_opp_ast': 'rolling_10_opp_ast_per_game',
    'rolling_10_opp_stl': 'rolling_10_opp_stl_per_game',
    'rolling_10_opp_blk': 'rolling_10_opp_blk_per_game',
    'rolling_10_opp_tov': 'rolling_10_opp_tov_per_game',
    'rolling_10_opp_pf': 'rolling_10_opp_pf_per_game',
    'rolling_10_team_advanced_ortg': 'rolling_10_team_advanced_ortg_per_game',
    'rolling_10_team_advanced_drtg': 'rolling_10_team_advanced_drtg_per_game',
    'rolling_10_team_advanced_pace': 'rolling_10_team_advanced_pace_per_game',
    'rolling_10_opp_advanced_ortg': 'rolling_10_opp_advanced_ortg_per_game',
    'rolling_10_opp_advanced_drtg': 'rolling_10_opp_advanced_drtg_per_game',
    'rolling_10_opp_advanced_pace': 'rolling_10_opp_advanced_pace_per_game'
}

# Apply renaming
df.rename(columns=rename_dict, inplace=True)

# Quick verification of renaming
print([col for col in df.columns if 'rolling_10_' in col and '_per_game' in col])

['rolling_10_team_fg_per_game', 'rolling_10_team_fga_per_game', 'rolling_10_team_3p_per_game', 'rolling_10_team_3pa_per_game', 'rolling_10_team_ft_per_game', 'rolling_10_team_fta_per_game', 'rolling_10_team_orb_per_game', 'rolling_10_team_trb_per_game', 'rolling_10_team_ast_per_game', 'rolling_10_team_stl_per_game', 'rolling_10_team_blk_per_game', 'rolling_10_team_tov_per_game', 'rolling_10_team_pf_per_game', 'rolling_10_team_advanced_ortg_per_game', 'rolling_10_team_advanced_drtg_per_game', 'rolling_10_team_advanced_pace_per_game', 'rolling_10_opp_fg_per_game', 'rolling_10_opp_fga_per_game', 'rolling_10_opp_3p_per_game', 'rolling_10_opp_3pa_per_game', 'rolling_10_opp_ft_per_game', 'rolling_10_opp_fta_per_game', 'rolling_10_opp_orb_per_game', 'rolling_10_opp_trb_per_game', 'rolling_10_opp_ast_per_game', 'rolling_10_opp_stl_per_game', 'rolling_10_opp_blk_per_game', 'rolling_10_opp_tov_per_game', 'rolling_10_opp_pf_per_game', 'rolling_10_opp_advanced_ortg_per_game', 'rolling_10_opp_advanced_drtg_per_game', 'rolling_10_opp_advanced_pace_per_game', 'rolling_10_team_allowed_fg_per_game', 'rolling_10_team_allowed_fga_per_game', 'rolling_10_team_allowed_3p_per_game', 'rolling_10_team_allowed_3pa_per_game', 'rolling_10_team_allowed_ft_per_game', 'rolling_10_team_allowed_fta_per_game', 'rolling_10_team_allowed_orb_per_game', 'rolling_10_team_allowed_trb_per_game', 'rolling_10_team_allowed_ast_per_game', 'rolling_10_team_allowed_stl_per_game', 'rolling_10_team_allowed_blk_per_game', 'rolling_10_team_allowed_tov_per_game', 'rolling_10_team_allowed_pf_per_game', 'rolling_10_team_allowed_advanced_stl_pct_per_game', 'rolling_10_opp_allowed_fg_per_game', 'rolling_10_opp_allowed_fga_per_game', 'rolling_10_opp_allowed_3p_per_game', 'rolling_10_opp_allowed_3pa_per_game', 'rolling_10_opp_allowed_ft_per_game', 'rolling_10_opp_allowed_fta_per_game', 'rolling_10_opp_allowed_orb_per_game', 'rolling_10_opp_allowed_trb_per_game', 'rolling_10_opp_allowed_ast_per_game', 'rolling_10_opp_allowed_stl_per_game', 'rolling_10_opp_allowed_blk_per_game', 'rolling_10_opp_allowed_tov_per_game', 'rolling_10_opp_allowed_pf_per_game', 'rolling_10_opp_allowed_advanced_stl_pct_per_game']

In [200]:
# Step 1: Create unique game IDs for easy matching
df['game_id'] = df['team'] + '_' + df['opp'] + '_' + df['year'].astype(str) + '_' + df['month'].astype(str) + '_' + df['day'].astype(str)
df['opp_game_id'] = df['opp'] + '_' + df['team'] + '_' + df['year'].astype(str) + '_' + df['month'].astype(str) + '_' + df['day'].astype(str)

# Quick verify
print(df[['team', 'opp', 'game_id', 'opp_game_id']].head())

  team  opp                game_id            opp_game_id
0  ATL  DAL  ATL_DAL_2020_7.0_26.0  DAL_ATL_2020_7.0_26.0
1  ATL  LVA  ATL_LVA_2020_7.0_29.0  LVA_ATL_2020_7.0_29.0
2  ATL  NYL  ATL_NYL_2020_7.0_31.0  NYL_ATL_2020_7.0_31.0
3  ATL  IND   ATL_IND_2020_8.0_2.0   IND_ATL_2020_8.0_2.0
4  ATL  PHO   ATL_PHO_2020_8.0_4.0   PHO_ATL_2020_8.0_4.0

<ipython-input-200-2643cc858837>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['game_id'] = df['team'] + '_' + df['opp'] + '_' + df['year'].astype(str) + '_' + df['month'].astype(str) + '_' + df['day'].astype(str)
<ipython-input-200-2643cc858837>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['opp_game_id'] = df['opp'] + '_' + df['team'] + '_' + df['year'].astype(str) + '_' + df['month'].astype(str) + '_' + df['day'].astype(str)

In [201]:
# Step 2: Define the persona columns
persona_cols = [
    'all_around_star', 'and_one_machine', 'catch_and_shoot', 'corner_3_specialist',
    'defensive_anchor', 'defensive_rebounder', 'efficient_scorer', 'elite_scorer',
    'fast_break_threat', 'floor_general', 'free_throw_generator', 'glass_cleaner',
    'heave_chucker', 'impact_bench', 'midrange_sniper', 'offensive_hub',
    'offensive_rebounder', 'playmaker', 'plus_minus_driver', 'rim_protector',
    'self_creator', 'slasher', 'steal_artist', 'stretch_big',
    'three_point_specialist', 'turnover_prone', 'volume_shooter'
]

# Create temporary df for opponent personas
opp_personas = df[['game_id'] + persona_cols].copy()

# Rename columns for merging clearly
opp_personas.rename(columns={col: f'opp_{col}' for col in persona_cols}, inplace=True)
opp_personas.rename(columns={'game_id': 'opp_game_id'}, inplace=True)

# Merge to get opp_ columns in original df
df = df.merge(opp_personas, on='opp_game_id', how='left')

# Drop temporary columns if desired (or keep for verification)
df.drop(['game_id', 'opp_game_id'], axis=1, inplace=True)

# Quick verification
verify_cols = ['team', 'opp', 'year', 'month', 'day', 'stretch_big', 'opp_stretch_big']
print(df[verify_cols].head(10))

  team  opp  year  month   day  stretch_big  opp_stretch_big
0  ATL  DAL  2020    7.0  26.0          0.0              0.0
1  ATL  LVA  2020    7.0  29.0          0.0              0.0
2  ATL  NYL  2020    7.0  31.0          0.0              1.0
3  ATL  IND  2020    8.0   2.0          0.0              0.0
4  ATL  PHO  2020    8.0   4.0          0.0              0.0
5  ATL  SEA  2020    8.0   6.0          0.0              0.0
6  ATL  DAL  2020    8.0   8.0          0.0              0.0
7  ATL  CON  2020    8.0  10.0          0.0              0.0
8  ATL  SEA  2020    8.0  12.0          0.0              0.0
9  ATL  PHO  2020    8.0  14.0          0.0              0.0

In [202]:
for col in df.columns:
  print(col)

team
year
home_away
opp
win_loss
team_score
opp_score
team_fg
team_fga
team_fg_pct
team_3p
team_3pa
team_3p_pct
team_ft
team_fta
team_ft_pct
team_orb
team_trb
team_ast
team_stl
team_blk
team_tov
team_pf
opp_fg
opp_fga
opp_fg_pct
opp_3p
opp_3pa
opp_3p_pct
opp_ft
opp_fta
opp_ft_pct
opp_orb
opp_trb
opp_ast
opp_stl
opp_blk
opp_tov
opp_pf
day
month
advanced_ortg
advanced_drtg
advanced_pace
advanced_ftr
advanced_3par
advanced_ts_pct
advanced_trb_pct
advanced_ast_pct
advanced_stl_pct
advanced_blk_pct
offensive_four_factors_efg_pct
offensive_four_factors_tov_pct
offensive_four_factors_orb_pct
defensive_four_factors_efg_pct
defensive_four_factors_tov_pct
defensive_four_factors_drb_pct
all_around_star
and_one_machine
catch_and_shoot
corner_3_specialist
defensive_anchor
defensive_rebounder
efficient_scorer
elite_scorer
fast_break_threat
floor_general
free_throw_generator
glass_cleaner
heave_chucker
impact_bench
midrange_sniper
offensive_hub
offensive_rebounder
playmaker
plus_minus_driver
rim_protector
self_creator
slasher
steal_artist
stretch_big
three_point_specialist
turnover_prone
volume_shooter
game_num
ytd_team_score_mean
ytd_team_score_median
ytd_team_score_min
ytd_team_score_max
ytd_opp_score_mean
ytd_opp_score_median
ytd_opp_score_min
ytd_opp_score_max
ytd_team_allowed_mean
ytd_team_allowed_median
ytd_team_allowed_min
ytd_team_allowed_max
ytd_opp_allowed_mean
ytd_opp_allowed_median
ytd_opp_allowed_min
ytd_opp_allowed_max
ytd_team_fg_per_game
ytd_team_fga_per_game
ytd_team_3p_per_game
ytd_team_3pa_per_game
ytd_team_ft_per_game
ytd_team_fta_per_game
ytd_team_orb_per_game
ytd_team_trb_per_game
ytd_team_ast_per_game
ytd_team_stl_per_game
ytd_team_blk_per_game
ytd_team_tov_per_game
ytd_team_pf_per_game
ytd_opp_fg_per_game
ytd_opp_fga_per_game
ytd_opp_3p_per_game
ytd_opp_3pa_per_game
ytd_opp_ft_per_game
ytd_opp_fta_per_game
ytd_opp_orb_per_game
ytd_opp_trb_per_game
ytd_opp_ast_per_game
ytd_opp_stl_per_game
ytd_opp_blk_per_game
ytd_opp_tov_per_game
ytd_opp_pf_per_game
ytd_team_fg_pct
ytd_team_3p_pct
ytd_team_ft_pct
ytd_team_advanced_trb_pct
ytd_team_advanced_ast_pct
ytd_team_advanced_blk_pct
ytd_team_advanced_ftr
ytd_team_advanced_3par
ytd_team_pts_per_game
ytd_team_advanced_ts_pct
ytd_team_offensive_efg_pct
ytd_team_offensive_tov_pct
ytd_team_offensive_orb_pct
ytd_team_defensive_efg_pct
ytd_team_defensive_tov_pct
ytd_team_defensive_drb_pct
ytd_opp_fg_pct
ytd_opp_3p_pct
ytd_opp_ft_pct
ytd_opp_advanced_trb_pct
ytd_opp_advanced_ast_pct
ytd_opp_advanced_blk_pct
ytd_opp_advanced_ftr
ytd_opp_advanced_3par
ytd_opp_pts_per_game
ytd_opp_advanced_ts_pct
ytd_opp_offensive_efg_pct
ytd_opp_offensive_tov_pct
ytd_opp_offensive_orb_pct
ytd_opp_defensive_efg_pct
ytd_opp_defensive_tov_pct
ytd_opp_defensive_drb_pct
ytd_team_advanced_ortg
ytd_team_advanced_drtg
ytd_team_advanced_pace
ytd_opp_advanced_ortg
ytd_opp_advanced_drtg
ytd_opp_advanced_pace
ytd_team_advanced_stl_pct
ytd_opp_advanced_stl_pct
ytd_team_allowed_fg_per_game
ytd_team_allowed_fga_per_game
ytd_team_allowed_3p_per_game
ytd_team_allowed_3pa_per_game
ytd_team_allowed_ft_per_game
ytd_team_allowed_fta_per_game
ytd_team_allowed_orb_per_game
ytd_team_allowed_trb_per_game
ytd_team_allowed_ast_per_game
ytd_team_allowed_stl_per_game
ytd_team_allowed_blk_per_game
ytd_team_allowed_tov_per_game
ytd_team_allowed_pf_per_game
ytd_team_allowed_advanced_stl_pct_per_game
ytd_team_allowed_fg_pct
ytd_team_allowed_3p_pct
ytd_team_allowed_ft_pct
ytd_team_allowed_advanced_ts_pct
ytd_team_allowed_offensive_efg_pct
ytd_team_allowed_offensive_tov_pct
ytd_team_allowed_offensive_orb_pct
ytd_team_allowed_defensive_efg_pct
ytd_team_allowed_defensive_tov_pct
ytd_team_allowed_defensive_drb_pct
ytd_opp_allowed_fg_per_game
ytd_opp_allowed_fga_per_game
ytd_opp_allowed_3p_per_game
ytd_opp_allowed_3pa_per_game
ytd_opp_allowed_ft_per_game
ytd_opp_allowed_fta_per_game
ytd_opp_allowed_orb_per_game
ytd_opp_allowed_trb_per_game
ytd_opp_allowed_ast_per_game
ytd_opp_allowed_stl_per_game
ytd_opp_allowed_blk_per_game
ytd_opp_allowed_tov_per_game
ytd_opp_allowed_pf_per_game
ytd_opp_allowed_advanced_stl_pct_per_game
ytd_opp_allowed_fg_pct
ytd_opp_allowed_3p_pct
ytd_opp_allowed_ft_pct
ytd_opp_allowed_advanced_ts_pct
ytd_opp_allowed_offensive_efg_pct
ytd_opp_allowed_offensive_tov_pct
ytd_opp_allowed_offensive_orb_pct
ytd_opp_allowed_defensive_efg_pct
ytd_opp_allowed_defensive_tov_pct
ytd_opp_allowed_defensive_drb_pct
rolling_10_team_score_mean
rolling_10_team_score_median
rolling_10_team_score_min
rolling_10_team_score_max
rolling_10_opp_score_mean
rolling_10_opp_score_median
rolling_10_opp_score_min
rolling_10_opp_score_max
rolling_10_team_fg_per_game
rolling_10_team_fga_per_game
rolling_10_team_3p_per_game
rolling_10_team_3pa_per_game
rolling_10_team_ft_per_game
rolling_10_team_fta_per_game
rolling_10_team_orb_per_game
rolling_10_team_trb_per_game
rolling_10_team_ast_per_game
rolling_10_team_stl_per_game
rolling_10_team_blk_per_game
rolling_10_team_tov_per_game
rolling_10_team_pf_per_game
rolling_10_team_advanced_stl_pct
rolling_10_team_advanced_ortg_per_game
rolling_10_team_advanced_drtg_per_game
rolling_10_team_advanced_pace_per_game
rolling_10_opp_fg_per_game
rolling_10_opp_fga_per_game
rolling_10_opp_3p_per_game
rolling_10_opp_3pa_per_game
rolling_10_opp_ft_per_game
rolling_10_opp_fta_per_game
rolling_10_opp_orb_per_game
rolling_10_opp_trb_per_game
rolling_10_opp_ast_per_game
rolling_10_opp_stl_per_game
rolling_10_opp_blk_per_game
rolling_10_opp_tov_per_game
rolling_10_opp_pf_per_game
rolling_10_opp_advanced_stl_pct
rolling_10_opp_advanced_ortg_per_game
rolling_10_opp_advanced_drtg_per_game
rolling_10_opp_advanced_pace_per_game
rolling_10_team_fg_pct
rolling_10_team_3p_pct
rolling_10_team_ft_pct
rolling_10_team_offensive_efg_pct
rolling_10_team_offensive_tov_pct
rolling_10_team_offensive_orb_pct
rolling_10_team_defensive_efg_pct
rolling_10_team_defensive_tov_pct
rolling_10_team_defensive_drb_pct
rolling_10_team_advanced_ts_pct
rolling_10_team_advanced_trb_pct
rolling_10_team_advanced_ast_pct
rolling_10_team_advanced_blk_pct
rolling_10_team_advanced_ftr
rolling_10_team_advanced_3par
rolling_10_opp_fg_pct
rolling_10_opp_3p_pct
rolling_10_opp_ft_pct
rolling_10_opp_offensive_efg_pct
rolling_10_opp_offensive_tov_pct
rolling_10_opp_offensive_orb_pct
rolling_10_opp_defensive_efg_pct
rolling_10_opp_defensive_tov_pct
rolling_10_opp_defensive_drb_pct
rolling_10_opp_advanced_ts_pct
rolling_10_opp_advanced_trb_pct
rolling_10_opp_advanced_ast_pct
rolling_10_opp_advanced_blk_pct
rolling_10_opp_advanced_ftr
rolling_10_opp_advanced_3par
rolling_10_team_allowed_fg_per_game
rolling_10_team_allowed_fga_per_game
rolling_10_team_allowed_3p_per_game
rolling_10_team_allowed_3pa_per_game
rolling_10_team_allowed_ft_per_game
rolling_10_team_allowed_fta_per_game
rolling_10_team_allowed_orb_per_game
rolling_10_team_allowed_trb_per_game
rolling_10_team_allowed_ast_per_game
rolling_10_team_allowed_stl_per_game
rolling_10_team_allowed_blk_per_game
rolling_10_team_allowed_tov_per_game
rolling_10_team_allowed_pf_per_game
rolling_10_team_allowed_advanced_stl_pct_per_game
rolling_10_team_allowed_fg_pct
rolling_10_team_allowed_3p_pct
rolling_10_team_allowed_ft_pct
rolling_10_team_allowed_advanced_ts_pct
rolling_10_team_allowed_offensive_efg_pct
rolling_10_team_allowed_offensive_tov_pct
rolling_10_team_allowed_offensive_orb_pct
rolling_10_team_allowed_defensive_efg_pct
rolling_10_team_allowed_defensive_tov_pct
rolling_10_team_allowed_defensive_drb_pct
rolling_10_opp_allowed_fg_per_game
rolling_10_opp_allowed_fga_per_game
rolling_10_opp_allowed_3p_per_game
rolling_10_opp_allowed_3pa_per_game
rolling_10_opp_allowed_ft_per_game
rolling_10_opp_allowed_fta_per_game
rolling_10_opp_allowed_orb_per_game
rolling_10_opp_allowed_trb_per_game
rolling_10_opp_allowed_ast_per_game
rolling_10_opp_allowed_stl_per_game
rolling_10_opp_allowed_blk_per_game
rolling_10_opp_allowed_tov_per_game
rolling_10_opp_allowed_pf_per_game
rolling_10_opp_allowed_advanced_stl_pct_per_game
rolling_10_opp_allowed_fg_pct
rolling_10_opp_allowed_3p_pct
rolling_10_opp_allowed_ft_pct
rolling_10_opp_allowed_advanced_ts_pct
rolling_10_opp_allowed_offensive_efg_pct
rolling_10_opp_allowed_offensive_tov_pct
rolling_10_opp_allowed_offensive_orb_pct
rolling_10_opp_allowed_defensive_efg_pct
rolling_10_opp_allowed_defensive_tov_pct
rolling_10_opp_allowed_defensive_drb_pct
opp_all_around_star
opp_and_one_machine
opp_catch_and_shoot
opp_corner_3_specialist
opp_defensive_anchor
opp_defensive_rebounder
opp_efficient_scorer
opp_elite_scorer
opp_fast_break_threat
opp_floor_general
opp_free_throw_generator
opp_glass_cleaner
opp_heave_chucker
opp_impact_bench
opp_midrange_sniper
opp_offensive_hub
opp_offensive_rebounder
opp_playmaker
opp_plus_minus_driver
opp_rim_protector
opp_self_creator
opp_slasher
opp_steal_artist
opp_stretch_big
opp_three_point_specialist
opp_turnover_prone
opp_volume_shooter

In [203]:
# Save DataFrame as CSV file locally in Colab
df.to_csv('wnba_final_df.csv', index=False)

# Download directly to your local machine
from google.colab import files
files.download('wnba_final_df.csv')